### ISSUE TITLE
support consul as sync data center impl

### ISSUE THREAD

**Issue by leohou0430** [apache/incubator-shenyu#1146]
## Feature Request

add consul to support sync-data-center impl

#### Additional context

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by yu199195** [comment]
consul, and etcd become register center  a better way to do it

**Comment by leohou0430** [comment]
> consul, and etcd become register center a better way to do it

we will use grpc and consul as soa component in future，in data-sync-center to replace websocket protocl.
And i will implement consul become register center to

**Comment by yu199195** [comment]
good luck to you

**Comment by XiBeiWaQiang** [comment]
consul register type can not Check the service is alive if the service is deded the getway can still request this service node

**Comment by midnight2104** [comment]
shenyu can support consul for data synchronization, please refer https://shenyu.apache.org/docs/design/data-sync
