### ISSUE TITLE
springcloud timeout config

### ISSUE THREAD

**Issue by naah69** [apache/incubator-shenyu#1196]
## Question

default of springcloud timeout is 3000ms.

i can set default springcloud timeout  in soul-admin > BasicConfig > Plugin Handler.

but when i use `SoulSpringCloudClient` in code.the timeout always be 3000ms.

is there some config item can set it in springcloud？

**Comment by yu199195** [comment]
maybe the next version is optimized

**Comment by naah69** [comment]
maybe it need global http timeout config and annotatiopn http timeout config.

**Comment by midnight2104** [comment]
pls see https://shenyu.apache.org/docs/plugin-center/proxy/spring-cloud-plugin
