### ISSUE TITLE
how to exclude url in rule

### ISSUE THREAD

**Issue by naah69** [apache/incubator-shenyu#1198]
## Question

// your question here;

how to exclude url in rule?

i didn't find the way to exclude the url in rule

**Comment by naah69** [comment]
Is it possible to add intercept field of PluginHandle in Rules.

and judge it in `org.dromara.soul.plugin.base.AbstractSoulPlugin#execute`

**Comment by yu199195** [comment]
why need exclude url？

**Comment by naah69** [comment]
such as sign scene.

we match /seed/**,but some path needn't sign.

In this case，we need exclude path

**Comment by yu199195** [comment]
not match， also not need sign

**Comment by naah69** [comment]
but when there are many many api,add api one by one will make we crash

**Comment by yu199195** [comment]
What is your requirements scenario?     Doesn't it have a prefix？

**Comment by naah69** [comment]
Of course, we do have api prefix,
but we are dismantling service now,the api is so much.
we want smooth transition,so we need exclude api.
why addn’t the function?
This can also meet the needs of others

**Comment by yu199195** [comment]
you can fix it

**Comment by naah69** [comment]
what’s meaning？

fix soul-admin config or fix the code

**Comment by kenWu-github** [comment]
@yu199195 I always have this quesion .Is there a plan to develop this feature?

**Comment by naah69** [comment]
> @yu199195 I always have this quesion .Is there a plan to develop this feature?

i had write it，rewrite plugin and make soul admin metadata can implement it

**Comment by tuohai666** [comment]
@naah69 Do you mean add a condition here named exclude?

![image](https://user-images.githubusercontent.com/24643893/115106493-c2ae1a00-9f97-11eb-8d9a-538a7b9cd1b9.png)

**Comment by naah69** [comment]
> @naah69 Do you mean add a condition here named exclude?
> 
> ![image](https://user-images.githubusercontent.com/24643893/115106493-c2ae1a00-9f97-11eb-8d9a-538a7b9cd1b9.png)

a easier way that is by add match rule rule order and config switch  of whether intercept ，then rewrite AbstractSoulPlugin.execute

**Comment by tuohai666** [comment]
I believe we need this feature if my understanding is correct.

Example:

All the APIs
/seed/**  (assume 100 APIs)

We want 99 of the APIs intercepted by sign plugin, except this one
/seed/abc (1 API need to be excluded)

For now, we have to config 99 rules instead of one or two rules.

If so, an exclude condition may work.

@naah69 Can you show some details in your easier solution?

**Comment by naah69** [comment]
> I believe we need this feature if my understanding is correct.
> 
> Example:
> 
> All the APIs
> /seed/**  (assume 100 APIs)
> 
> We want 99 of the APIs intercepted by sign plugin, except this one
> /seed/abc (1 API need to be excluded)
> 
> For now, we have to config 99 rules instead of one or two rules.
> 
> If so, an exclude condition may work.
> 
> @naah69 Can you show some details in your easier solution?
> 
> 

yes，it is right. we add the feture in our soul, do i need pr it？

**Comment by tuohai666** [comment]
Please feel free to submit a pr.

**Comment by tuohai666** [comment]
@naah69 I'd like to review the pr when you submit.

**Comment by tuohai666** [comment]
> > @naah69 Do you mean add a condition here named exclude?
> a easier way that is by add match rule rule order and config switch of whether intercept ，then rewrite AbstractSoulPlugin.execute

What if add an exclude strategy in the rules handler?

![image](https://user-images.githubusercontent.com/24643893/115542932-61f24a80-a2d3-11eb-8820-2f21313f8933.png)

**Comment by naah69** [comment]
> @naah69 I'd like to review the pr when you submit.

we just add exclue url in rule handler，and set this rule is passed,final set order small than the others.

order is important, for rule match

**Comment by naah69** [comment]
> > > @naah69 Do you mean add a condition here named exclude?
> > a easier way that is by add match rule rule order and config switch of whether intercept ，then rewrite AbstractSoulPlugin.execute
> 
> What if add an exclude strategy in the rules handler?
> 
> ![image](https://user-images.githubusercontent.com/24643893/115542932-61f24a80-a2d3-11eb-8820-2f21313f8933.png)
> 

I had merge it to master in my local git today, I will test it tomorrow, then pr it

**Comment by naah69** [comment]
> > > @naah69 Do you mean add a condition here named exclude?
> > a easier way that is by add match rule rule order and config switch of whether intercept ，then rewrite AbstractSoulPlugin.execute
> 
> What if add an exclude strategy in the rules handler?
> 
> ![image](https://user-images.githubusercontent.com/24643893/115542932-61f24a80-a2d3-11eb-8820-2f21313f8933.png)
> 

sry，i didn't get what u meant before some minutes.

do u mean that add match exclude strategy in rule handle?

I think that is chaos and the better is that chicken is  chicken and duck is  duck. it is more in line with single responsibility principle

**Comment by tuohai666** [comment]
Agree. Looking forward to your pr.

> sry，i didn't get what u meant before some minutes.
> 
> do u mean that add match exclude strategy in rule handle?
> 
> I think that is chaos and the better is that chicken is chicken and duck is duck. it is more in line with single responsibility principle

**Comment by midnight2104** [comment]
pls see https://shenyu.apache.org/docs/user-guide/admin-usage/selector-and-rule
