### ISSUE TITLE
add soul-plugin-permission

### ISSUE THREAD

**Issue by naah69** [apache/incubator-shenyu#1199]
#### Is your feature request related to a problem? Please describe

developer can implement permission auth it in gateway.

i had wrote it.can i pr it?

#### Describe the solution you'd like

add a permission plugin.

#### Describe alternatives you've considered

auth permission in sign plugin,but i think that is not a good idea

**Comment by dengliming** [comment]
We can discuss it before submiting the pr. You can join our wechat group. [https://camo.githubusercontent.com/eb438a7866579ef45424d32c4bd231fc363b3e2fd64f6e789fa9705a7aec0ab1/68747470733a2f2f79753139393139352e6769746875622e696f2f696d616765732f7075626c69632e6a7067](https://camo.githubusercontent.com/eb438a7866579ef45424d32c4bd231fc363b3e2fd64f6e789fa9705a7aec0ab1/68747470733a2f2f79753139393139352e6769746875622e696f2f696d616765732f7075626c69632e6a7067)

**Comment by naah69** [comment]
yeah，but the qr code is wechat official account，not group

**Comment by naah69** [comment]
How can I contact you

**Comment by dengliming** [comment]
If you don't mind, you can provide your WeChat. I will invite you to join our WeChat group.

**Comment by naah69** [comment]
ok.
my wechat is naah6996

**Comment by plutokaito** [comment]
Is this [pr](https://github.com/dromara/shenyu/pull/1349)  similar to this issue?

**Comment by yu199195** [comment]
@plutokaito  hi 

> Is this pr similar to this issue?

#1255  this pr is datapermission  is shenyu-admin

this issue is mean Third Party auth

**Comment by plutokaito** [comment]
tnx,  now i see,  and  I am interested in this issue.

**Comment by midnight2104** [comment]
pls see https://shenyu.apache.org/docs/user-guide/admin-usage/data-permission
