### ISSUE TITLE
Next version TODOLIST

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1233]
Hi all guys

In next version, we should Complete the following featrues

- [x] Integration Nepxion impl Gray released to spring cloud  @yu199195 
- [x]  add performance test project @tuohai666 
- [x]  support motan rpc @tydhot 
- [x]  support brpc  @SaberSola 
- [x]  Enhance the monitor plugin and make all kinds of charts in Soul-Admin such as QPS  @fengzhenbing 
- [x] support  Gray released to dubbo  @prFor 
- [x] add integration test project @dmsolr 
- [x] add data access for soul-admin @nuo-promise 
- [x] springboot hot loading plugin @dengliming 
- [x] To optimize the grpc and tars plugin @tydhot @SaberSola 
- [x]  To optimize the springcloud plugin init   @huangxfchn

**Comment by Redick01** [comment]
springboot hot loading plugin

**Comment by xxiancheng** [comment]
To optimize the springcloud plugin init

**Comment by Zhoutzzz** [comment]
support brpc and motan rpc

**Comment by nuo-promise** [comment]
get

**Comment by Trafalgar-YuI** [comment]
support brpc and motan rpc

**Comment by MarcusJiang1306** [comment]
integration test

**Comment by onlyonezhongjinhui** [comment]
springboot hot loading plugin

**Comment by onlyonezhongjinhui** [comment]
add performance test project

**Comment by onlyonezhongjinhui** [comment]
integration test

**Comment by midnight2104** [comment]
To optimize the grpc

**Comment by plutokaito** [comment]
add data access

**Comment by zenglinhui** [comment]
springboot hot loading plugin

**Comment by ttttangzhen** [comment]
springboot hot loading plugin

**Comment by songyuequan** [comment]
springboot hot loading plugin

**Comment by lxl910128** [comment]
I want try "springboot hot loading plugin" or "add data access for soul-admin "

**Comment by zhaiweij** [comment]
Enhance the monitor plugin and make all kinds of charts in Soul-Admin such as QPS

**Comment by wangdazhong001** [comment]
When is it expected to be released

**Comment by wangdazhong001** [comment]
Gateway log, interface statistics (support by appid), call record, real-time call data, response time
