### ISSUE TITLE
consul register type  Service exploration

### ISSUE THREAD

**Issue by XiBeiWaQiang** [apache/incubator-shenyu#1261]
use consul register type the soul admin do not soupport Service exploration  i see only use http register type can do this

**Comment by XiBeiWaQiang** [comment]
consul register type can not Check the service is alive if the service is deded the getway can still request this service node

**Comment by yu199195** [comment]
consul register ， can not to check ，it listenner by consul

**Comment by MarcusJiang1306** [comment]
Soul just moritor the consul service nodes, will not check the health check, so if the servier unavailable in unexpected(without deregiser to consul) will get invalid service from consul
