### ISSUE TITLE
Can it be supported in the new version, call log view, it is best to visualize, view all AppKey call status, each interface request status

### ISSUE THREAD

**Issue by wangdazhong001** [apache/incubator-shenyu#1268]
## Feature Request

example:  http://demo.fizzgate.com/
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Additional context

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by dengliming** [comment]
We'll try to add it. Meanwhile, feel free to submit a PR.
