### ISSUE TITLE
request response 503 code how to trigger hystrix fallback

### ISSUE THREAD

**Issue by linchuyao** [apache/incubator-shenyu#1269]

**Comment by dengliming** [comment]
Please describe it in detail.

**Comment by linchuyao** [comment]
My downstream service is SLB. The soul gateway requests the downstream service, and the downstream service returns 503 error. I hope this error can be sensed by hystrix and fused, so that my downstream service can start smoothly under the request of large traffic

**Comment by dengliming** [comment]
We already support to config FallbackUri. (default [`/fallback/hystrix`](https://github.com/dromara/soul/blob/ffa5c105e7639c7385dcc3b395a27b2cae701bd8/soul-web/src/main/java/org/dromara/soul/web/fallback/DefaultFallbackController.java#L42))  Does it not working?

**Comment by linchuyao** [comment]
but slb response 503 will not trigger onFallback method

**Comment by linchuyao** [comment]
I need to have a place to configure which situations need to be executed onFallBackMethod . for example i can config will response 502、503 errorCode  will excuted onFallBackMethod.

**Comment by dengliming** [comment]
That seems to be no exception for the `5xx ` now. Maybe we should handle the 5xx errorCode and throws an exception to trigger the hystrix fallback.

**Comment by linchuyao** [comment]
Yes, this is how I deal with it at present. When the webclientresponseplugin judges clientResponse is error and hystrix plugin is open i will  throws an exception.

**Comment by linchuyao** [comment]
Yes, this is how I deal with it at present. When the webclientresponseplugin judges clientResponse is error and hystrix plugin is open i will  throws an exception and generateError i will try this exception to handler response

if (clientResponse.statusCode().isError()) {
                if (Boolean.TRUE.equals(exchange.getAttributes().get(Constants.ENABLE_HYSTRIX_PLUGIN))) {
                    //throw exception make hystrix count 4xx or txx error
                    throw new HystrixMarkException(clientResponse.statusCode().getReasonPhrase());
                }
                Object error = SoulResultWrap.error(SoulResultEnum.SERVICE_RESULT_ERROR.getCode(), SoulResultEnum.SERVICE_RESULT_ERROR.getMsg(), null);
                return WebFluxResultUtils.result(exchange, error);
            }


if (exception instanceof HystrixMarkException) {
            DingTalkUtils.addMessage2Queue(buildDingTalkPushMessage(exchange, Boolean.FALSE));
            HystrixMarkException hystrixMarkException = (HystrixMarkException) exception;
            exchange.getResponse().setStatusCode(hystrixMarkException.getHttpStatus());
            error = SoulResultWrap.error(SoulResultEnum.SERVICE_RESULT_ERROR.getCode(), SoulResultEnum.SERVICE_RESULT_ERROR.getMsg(), null);
        }

**Comment by yu199195** [comment]
can you provider pr to fix ？

**Comment by linchuyao** [comment]
> 你可以提供公关来修理吗？

It's my pleasure ， i want to do it

**Comment by yu199195** [comment]
>It's my pleasure ， i want to do it

Ok

**Comment by midnight2104** [comment]
Hi, does this question still exist? If there is still a problem, please resubmit the issue.
