### ISSUE TITLE
Add Response Plugin

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1292]
## feature

1. add  response header 
2. remove response header
3. set response header
4. set response status

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by xiaoshen11** [comment]
get

**Comment by xiaoshen11** [comment]
this pr is create  a new plugin like soul-plugin-divide?

**Comment by yu199195** [comment]
yes ..

**Comment by kimmking** [comment]
any improvement？ @xiaoshen11

**Comment by xiaoshen11** [comment]
> any improvement？ @xiaoshen11
I don’t know how to display the configuration header and status on the front-end page
