### ISSUE TITLE
dubbo plugin's Exception expose service's environment information

### ISSUE THREAD

**Issue by starslau** [apache/incubator-shenyu#1303]
route defined by Wrong request ths gateway will expose the environment information of back-end services.
I request the route defined in soul-admin without parameters , which exposes the environment information of back-end services,
I hope the environment information of back-end services can be hidden.
`{
    "code": 500,
    "message": "Internal Server Error",
    "data": "Failed to invoke the method $invoke in the service com.alibaba.dubbo.rpc.service.GenericService. Tried 3 times of the providers [x.x.x.x:38897, x.x.x.x:32197] (2/2) from the registry x.x.x.x:2181 on the consumer x.x.x.x using the dubbo version 2.5.3. Last error is: Failed to invoke remote method: $invoke, provider: dubbo://x.x.x.x:32197/com.bnq.jz.dcmall.api.dcmall.service.AppIntentOrderApi?anyhost=true&application=soul_proxy&check=false&dubbo=2.5.3&generic=true&interface=com.bnq.jz.dcmall.api.dcmall.service.AppIntentOrderApi&loadbalance=random&methods=appointCreate&pid=22316&protocol=dubbo&retries=2&revision=1.0.0&side=consumer&timeout=3000&timestamp=1619088876207&version=1.0.0, cause: message can not send, because channel is closed . url:dubbo://x.x.x.x:32197/com.bnq.jz.dcmall.api.dcmall.service.SysUserApi?anyhost=true&application=soul_proxy&check=false&codec=dubbo&dubbo=2.5.3&generic=true&heartbeat=60000&interface=com.bnq.jz.dcmall.api.dcmall.service.SysUserApi&loadbalance=random&methods=getUserByShopCodeAndRole,getAll,getPersonnelOrgnizeByUser,getUser,getShopCodeList,queryByMobile,getUserByStatus,queryById,queryByMobileList&pid=22316&protocol=dubbo&retries=2&revision=1.0.0&side=consumer&timeout=3000&timestamp=1619088853847&validation=true&version=1.0.0"
}`

**Comment by dengliming** [comment]
You can do it in `GlobalErrorHandler`. But we can't hide all Exception message since we have some custom exceptions of parameter check.

**Comment by midnight2104** [comment]
If there are still questions, please resubmit issue.
