### ISSUE TITLE
dubbo plugin: hope the request method of the API can be defined

### ISSUE THREAD

**Issue by starslau** [apache/incubator-shenyu#1304]
If the gateway as a part of the middle station, provides capabilities to the third party, I think it is very important to define the request method of routes instead of being accessible by any request method to routes

**Comment by dengliming** [comment]
Can you provide an example?

**Comment by KevinClair** [comment]
Do you mean the gateway should support different request methods？such as `post`,`get` and `put`, and so on.

**Comment by midnight2104** [comment]
If there are still questions, please resubmit issue.
