### ISSUE TITLE
There is no incremental change in the initial script associated with the upgrade of the soul version

### ISSUE THREAD

**Issue by best-one** [apache/incubator-shenyu#1338]
When I plan to upgrade the version, I will find an error reminder for missing SQL fields. Can I provide incremental SQL for version change to guide quick upgrade?

**Comment by yu199195** [comment]
we will add sql_version file to help upgrade..

**Comment by plutokaito** [comment]
may i ask a question? if we do this, what version of sql file can be depended? in other way, after what version to add sql_version file ?

**Comment by midnight2104** [comment]
pls see https://github.com/apache/incubator-shenyu/pull/2526
