### ISSUE TITLE
Failed to build soul according to the steps of official website

### ISSUE THREAD

**Issue by haohao1121** [apache/incubator-shenyu#1366]
安装官网上搭建soul环境时到最后搭建自己的网关引入依赖后启动报错：
The bean 'errorWebExceptionHandler', defined in class path resource [org/dromara/soul/web/configuration/ErrorHandlerConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/error/ErrorWebFluxAutoConfiguration.class] and overriding is disabled.

**Comment by yu199195** [comment]
please in english

**Comment by haohao1121** [comment]
The bean 'errorWebExceptionHandler', defined in class path resource [org/dromara/soul/web/configuration/ErrorHandlerConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/web/reactive/error/ErrorWebFluxAutoConfiguration.class] and overriding is disabled.

**Comment by yu199195** [comment]
spring:
   main:
     allow-bean-definition-overriding: true

**Comment by haohao1121** [comment]
It's already configured, but it doesn't work

**Comment by AhahaGe** [comment]
I have the same issue when start ShenyuBootstrapApplication, and checked the application-local.yml and below is detail:
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: shenyu-bootstrap
