### ISSUE TITLE
Renamed Apache ShenYu(incubator) Task

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1394]
# Sign Apache ICLA 

- [ ] the contributors :  https://shimo.im/sheets/rPqtJcWPDPV9wWPd/MODOC
- [x]  the  process :  https://dromara.org/projects/soul/icla/

# Docs
- [x]  Create ShenYu website  @yu199195 
- [ ]  modify document and website @fengzhenbing @dengliming  @0x12FD16B @nuo-promise 

# Renamed soul to ShenYu

- [x]  renamed soul project to ShenYu @yu199195 
- [x]  renamed  soul class  to ShenYu  @kimmking 
- [x] 1.renamed  soul spring boot prefix  to ShenYu  
- [x] 2.renamed  soul in spring mvc path
- [x] 3.update ascii logo to shenyu
- [x] 4.renamed  soul in admin dto and sql @renzhuyan
- [ ] 5.renamed  soul in frontend files
- [x] 6.remove all authors and modify soul in comments @Trafalgar-YuI 
- [x] 7.renamed  soul in examples @kimmking

**Comment by hubao-1125** [comment]
get task 5

**Comment by zhaiweij** [comment]
get task 4 renamed soul in admin dto and sql

**Comment by WYUSIG** [comment]
get task 7 renamed soul in examples

**Comment by Trafalgar-YuI** [comment]
get task 6 remove all authors and modify soul in comments

**Comment by wuudongdong** [comment]
get task 2 renamed soul in spring mvc path

**Comment by songyuequan** [comment]
get task 1 renamed soul spring boot prefix to ShenYu

**Comment by fengzhenbing** [comment]
5.renamed soul in frontend files

**Comment by plutokaito** [comment]
May I get the second task in Renamed soul to ShenYu?

**Comment by SaberSola** [comment]
get task 2 and and I finished it on Sunday
