### ISSUE TITLE
Add authorized feature for Shenyu

### ISSUE THREAD

**Issue by Zhoutzzz** [apache/incubator-shenyu#1401]
## Feature Request
It is planned to add a plug-in for authorization authentication in shenyu. Currently, the tools that can be integrated are WebFlux Security or sa-token. I want to discuss the specific integration plan in the community. If there are other better suggestions, I hope you can put forward them. For reference, if the integration scheme is determined, I plan to implement it with @jinze1107.If you are interested in this, you can also join us to develop.

**Comment by WYUSIG** [comment]
I want to join you

**Comment by qixiaobo** [comment]
@Zhoutzzz @WYUSIG How about the progress

**Comment by Zhoutzzz** [comment]
> @Zhoutzzz @WYUSIG How about the progress

https://shenyu.apache.org/zh/docs/plugin-center/authority-and-certification/oauth2-plugin

**Comment by midnight2104** [comment]
done
