### ISSUE TITLE
New resource "Menu Test" does not work and cannot be displayed properly

### ISSUE THREAD

**Issue by huangcanhui2018** [apache/incubator-shenyu#1440]
## Steps

Follow these steps to add resources:
1)Add a new resource "Menu Test" and add a button to this resource
![1](https://user-images.githubusercontent.com/45359999/117913872-c4f46180-b314-11eb-963e-83c9a05f0ec9.png)

2)Assign resource Menu Test operation permissions to roles
![2](https://user-images.githubusercontent.com/45359999/117913942-e81f1100-b314-11eb-9484-f99e3a536f5d.png)

3)Associate roles for users
![3](https://user-images.githubusercontent.com/45359999/117913969-f8cf8700-b314-11eb-95a7-89c608059ef7.png)

## Question
Following the above steps, the newly added resources cannot be displayed in the menu after the user logs in again. The same goes for new user reoperations. How should we configure the new resources to take effect?

**Comment by nuo-promise** [comment]
Received！


xiaoyu ***@***.***> 于2021年5月12日周三 上午11:44写道：

**Comment by nuo-promise** [comment]
The current basic configuration, the resources under the system management module do not support automatic creation, the plugin module is supported, you can test it @huangcanhui2018

**Comment by huangcanhui2018** [comment]
> The current basic configuration, the resources under the system management module do not support automatic creation, the plugin module is supported, you can test it @huangcanhui2018

However, in the newly added resource, the drop-down "Plugins List" option of the parent menu is disabled and cannot be operated. @nuo-promise
![4](https://user-images.githubusercontent.com/45359999/117957368-972b0f00-b34c-11eb-9ed2-4bc64d1be865.png)

**Comment by midnight2104** [comment]
Hi, does this question still exist? If there is still a problem, please resubmit the issue.
