### ISSUE TITLE
Enhance shenyu-web module unit test

### ISSUE THREAD

**Issue by qiaoqia** [apache/incubator-shenyu#1456]
## Task

Task List
 - [ ] Enhance shenyu-web module unit test，make its coverage rate is more than 80%

**Comment by wyc192273** [comment]
Please assign to me Enhance shenyu-web module unit test task.

**Comment by wyc192273** [comment]
I will finish this. in this weekend. I've been a little busy lately.

**Comment by songyuequan** [comment]
> I will finish this. in this weekend. I've been a little busy lately.

Hi~ what is the progress? @wyc192273

**Comment by plutokaito** [comment]
Hi, is anyone do this? if no one, plz assign to me, thank you.

**Comment by songyuequan** [comment]
> Hi, is anyone do this? if no one, plz assign to me, thank you.

I think no body do this for a long time . 
And In order to improve our UT Coverage .  you cat just do it .  thank you.
