### ISSUE TITLE
Enhance shenyu-sync-data-center module unit test

### ISSUE THREAD

**Issue by qiaoqia** [apache/incubator-shenyu#1458]
## Task

A clear and concise description of Task

Task List:

- [ ]  Enhance shenyu-sync-data-websocket module unit test，make its coverage rate is more than 80%
- [ ] Enhance shenyu-sync-data-nacos module unit test，make its coverage rate is more than 80%

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by realcalu** [comment]
I want Enhance shenyu-sync-data-websocket module unit test

**Comment by renzhuyan** [comment]
I want Enhance shenyu-sync-data-nacos module unit test，make its coverage rate is more than 80%
