### ISSUE TITLE
CLAs signed status of the major contributors

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shenyu#1461]
The following table shows the CLAs signed status, including:

1. All the initial committers;
2. The major contributors who submit codes more than 300 lines. ([The code line count statistics by GitHub](https://github.com/dromara/shenyu/graphs/contributors?from=2018-07-08&to=2021-05-26&type=a))

Full Name | GitHub ID | ICLA signed | ICLA receipt | CCLA signed | CCLA receipt | email in the CLA file
-- | -- | -- | -- | -- | -- | --
肖宇 | yu199195 | ✅ | ✅ | ✅ | ✅ | xiaoyu@apache.org
张永伦 | tuohai666 | ✅ | ✅ | ✅ | ✅ | zhangyonglun@apache.org
秦金卫 | kimmking | ✅ | ✅ | &nbsp; | &nbsp; | kimmking@apache.org
邓力铭 | dengliming | ✅ | ✅ | &nbsp; | &nbsp; | dengliming@apache.org
丁剑明 | nuo-promise | ✅ | ✅ | ✅ | ✅ | nuoyan@apache.org
汤煜冬 | tydhot | ✅ | ✅ | &nbsp; | &nbsp; | tydhot@apache.org
冯振兵 | fengzhenbing | ✅ | ✅ | &nbsp; | &nbsp; | fengzhenbing@apache.org
杨泽 | Asxing | ✅ | ✅ | &nbsp; | &nbsp; | asxing@apache.org
张磊 | SaberSola | ✅ | ✅ | &nbsp; | &nbsp; | sabersola@apache.org
黄晓峰 | huangxfchn | ✅ | ✅ | &nbsp; | &nbsp; | huangxfchn@apache.org
王婷婷 | fightingting | ✅ | ✅ | &nbsp; | &nbsp; | fightingting@apache.org
刘伟 | lw1243925457 | ✅ | ✅ | &nbsp; | &nbsp; | lw1243925457@apache.org
刘艺 | Trafalgar-YuI | ✅ | ✅ | &nbsp; | &nbsp; | yui@apache.org
刘伟 | 0x12FD16B | ✅ | ✅ | &nbsp; | &nbsp; | hex12fd16b@apache.org
宋明杰 | KevinClair | ✅ | ✅ | &nbsp; | &nbsp; | kevinclair@apache.org
蒋晓峰 | SteNicholas | ✅ | ✅ | &nbsp; | &nbsp; | nicholasjiang@apache.org
陈咸君 | CCLooMi | ✅ | ✅ | &nbsp; | &nbsp; | ccloomi@apache.org
高猛 | xlgm | ✅ | ✅ | &nbsp; | &nbsp; | zjntgao@apache.org
吴东东 | wuudongdong | ✅ | ✅ | &nbsp; | &nbsp; | wuudongdong@gmail.com
吴雨宸 | wyc192273 | ✅ | ✅ | &nbsp; | &nbsp; | wyczk@sina.com
江伟楷 | MarcusJiang1306 | ✅ | ✅ | &nbsp; | &nbsp; | jiang950526@qq.com
王真先 | zendwang | ✅ | ✅ | &nbsp; | &nbsp; | zendawang@dromara.org
刘朋辉 | Redick01 | ✅ | ✅ | &nbsp; | &nbsp; | 11090829@qq.com
汪鹏 | BetterWp | ✅ | ✅ | &nbsp; | &nbsp; | wp513920@qq.com
钟彦骏 | Severezh | ✅ | ✅ | &nbsp; | &nbsp; | severez@163.com
伊文龙 | yiwenlong | ✅ | ✅ | &nbsp; | &nbsp; | wlong.yi@gmail.com
胡文强 | Wincher | ✅ | ✅ | &nbsp; | &nbsp; | wincher.hoo@gmail.com
许晓东 | xxd763795151 | ✅ | ✅ | &nbsp; | &nbsp; | 763795151@qq.com
梁自强 | 241600489 | ✅ | ✅ | &nbsp; | &nbsp; | 2416004895@qq.com
刘良 | midnight2104 | ✅ | ✅ | &nbsp; | &nbsp; | midnight2104@foxmail.com
李菡 | wuliendan | ✅ | ✅ | &nbsp; | &nbsp; | lhan7295@163.com
&nbsp; | feixue2008 | could not be reached | &nbsp; | &nbsp; | &nbsp; | &nbsp;
薛永龙 | xxl115 | ✅ | ✅ | &nbsp; | &nbsp; | xxl115@163.com
王振武 | cocoZwwang | ✅ | ✅ | &nbsp; | &nbsp; | zwwang_cool@163.com
夏文涛 | kminjava | ✅ | ✅ | &nbsp; | &nbsp; | summerwit2020@outlook.com
李明昊 | lmhmhl | ✅ | ✅ | &nbsp; | &nbsp; | lmhlmhtju@163.com
&nbsp; | cottom | could not be reached | &nbsp; | &nbsp; | &nbsp; | &nbsp;
乔帝鸽 | strawberry-crisis | ✅ | ✅ | &nbsp; | &nbsp; | qiaodige@hotmail.com
骆潇龙 | lxl910128 | ✅ | ✅ | &nbsp; | &nbsp; | lxl910128@126.com
刘耿华 | kennhua | ✅ | ✅ | &nbsp; | &nbsp; | kennhua@126.com
钟金辉 | onlyonezhongjinhui | ✅ | ✅ | &nbsp; | &nbsp; | 13005454311@163.com
杜宇航 | xiaoshen11 | ✅ | ✅ | &nbsp; | &nbsp; | 347418287@qq.com
范金鹏 | hellboy0621 | ✅ | ✅ | &nbsp; | &nbsp; | hero0621@126.com
林宽 | Lin1nGithub | ✅ | ✅ | &nbsp; | &nbsp; | linkuan1994@gamil.com
帅仕 | plutokaito | ✅ | ✅ | &nbsp; | &nbsp; | kaito78@163.com
周庭兆 | Zhoutzzz | ✅ | ✅ | &nbsp; | &nbsp; | zhoutzzzzz@gmail.com
那焱 | naah69 | ✅ | ✅ | &nbsp; | &nbsp; | nayan3480232@163.com
拱晓晨 | magicalxiaochen | ✅ | ✅ | &nbsp; | &nbsp; | magicalxiaochen@gmail.com
周国栋 | FocusZhouGD | ✅ | ✅ | &nbsp; | &nbsp; | 18513080058@163.com
唐烨君 | tyjwan | ✅ | ✅ | &nbsp; | &nbsp; | 1003166540@qq.com
宋跃全 | songyuequan | ✅ | ✅ | &nbsp; | &nbsp; | songyuequangit@163.com
窦虎 | hubao-1125 | ✅ | ✅ | &nbsp; | &nbsp; | douhuhu1125@gmail.com
唐甜 | tangtian8 | ✅ | ✅ | &nbsp; | &nbsp; | sctangtian@qq.com
唐震 | ttttangzhen | ✅ | ✅ | &nbsp; | &nbsp; | 281578668@qq.com
沈祥俊 | stephenshen1993 | ✅ | ✅ | &nbsp; | &nbsp; | 15810813994@163.com
Liu Ying | marina432 | ✅ | ✅ | &nbsp; | &nbsp; | Mona432@163.com

For the two contributors who could not be reached, we removed and refactored theirs codes.

All the commits of **cottom** https://github.com/dromara/shenyu/commits?author=cottom
The codes remove and refactor: 
https://github.com/dromara/shenyu/commit/4aa398a

All the commits of **feixue2008**  https://github.com/dromara/shenyu/commits?author=feixue2008
The codes remove and refactor: 
https://github.com/dromara/shenyu/commit/a972d63
https://github.com/dromara/shenyu/commit/4a624e5
https://github.com/dromara/shenyu/commit/c58b12d
https://github.com/dromara/shenyu/commit/4a70413
https://github.com/dromara/shenyu/commit/abcc02e

**Comment by WillemJiang** [comment]
I just have a quick check with the icla signed information. I cannot find the these emails into the icla.txt.
Please check update the email with the one which sign the iCLA.

wuudongdong@gmail.com
jiang950526@gmail.com
LL2104@163.com
11090829@qq.com

**Comment by midnight2104** [comment]
hi, I'm sorry, the `LL2104@163.com` is error, and the right email for send ical is `midnight2104@foxmail.com`.

**Comment by WillemJiang** [comment]
> hi, I'm sorry, the `LL2104@163.com` is error, and the right email for send ical is `midnight2104@foxmail.com`.

Thx, I found iCLA record with midnight2104@foxmail.com.

**Comment by tuohai666** [comment]
Hi @WillemJiang,
For **jiang950526@gmail.com** and  **11090829@qq.com**, we can search the email address in private@shenyu.apache.org where the receipt ack can be found. I think they should in the icla.txt if there are  acknowledgments.
Can you help to double check these emails? Maybe they are missed.

**Comment by tuohai666** [comment]
jiang950526@gmail.com sent the icla file, but jiang950526@qq.com is written in the icla.pdf. So use jiang950526@qq.com to search in the icla.txt may find the item. jiang950526@qq.com is a valid mail address.

**Comment by tuohai666** [comment]
11090829@qq.com sent the icla file, but 11090289@qq.com is written in the icla.pdf. 11090289@qq.com is not a valid mail address because of typo. I suggested him to update the icla.pdf and re-send.

**Comment by Redick01** [comment]
I am so sorry, the 11090289@qq.com is error,  my correct email is 11090829@qq.com

**Comment by MarcusJiang1306** [comment]
> [jiang950526@gmail.com](mailto:jiang950526@gmail.com) sent the icla file, but [jiang950526@qq.com](mailto:jiang950526@qq.com) is written in the icla.pdf. So use [jiang950526@qq.com](mailto:jiang950526@qq.com) to search in the icla.txt may find the item. [jiang950526@qq.com](mailto:jiang950526@qq.com) is a valid mail address.

yes, 2 email addresses are valid, I used [jiang950526@gmail.com](mailto:jiang950526@gmail.com) sent the icla file, but [jiang950526@qq.com](mailto:jiang950526@qq.com) is written in the icla.pdf

**Comment by wuudongdong** [comment]
> I just have a quick check with the icla signed information. I cannot find the these emails into the icla.txt.
> Please check update the email with the one which sign the iCLA.
> 
> [wuudongdong@gmail.com](mailto:wuudongdong@gmail.com)
> [jiang950526@gmail.com](mailto:jiang950526@gmail.com)
> [LL2104@163.com](mailto:LL2104@163.com)
> [11090829@qq.com](mailto:11090829@qq.com)

I am so sorry, I sent a email which attachment appears to be unsigned. I have sent another email, but there is no reply.

**Comment by WillemJiang** [comment]
> I am so sorry, the [11090289@qq.com](mailto:11090289@qq.com) is error, my correct email is [11090829@qq.com](mailto:11090829@qq.com)

Please resend the iCLA with right email address with it.

**Comment by WillemJiang** [comment]
> > [jiang950526@gmail.com](mailto:jiang950526@gmail.com) sent the icla file, but [jiang950526@qq.com](mailto:jiang950526@qq.com) is written in the icla.pdf. So use [jiang950526@qq.com](mailto:jiang950526@qq.com) to search in the icla.txt may find the item. [jiang950526@qq.com](mailto:jiang950526@qq.com) is a valid mail address.
> 
> yes, 2 email addresses are valid, I used [jiang950526@gmail.com](mailto:jiang950526@gmail.com) sent the icla file, but [jiang950526@qq.com](mailto:jiang950526@qq.com) is written in the icla.pdf

Please resend the iCLA with right email address with it.

**Comment by WillemJiang** [comment]
> > I just have a quick check with the icla signed information. I cannot find the these emails into the icla.txt.
> > Please check update the email with the one which sign the iCLA.
> > [wuudongdong@gmail.com](mailto:wuudongdong@gmail.com)
> > [jiang950526@gmail.com](mailto:jiang950526@gmail.com)
> > [LL2104@163.com](mailto:LL2104@163.com)
> > [11090829@qq.com](mailto:11090829@qq.com)
> 
> I am so sorry, I sent a email which attachment appears to be unsigned. I have sent another email, but there is no reply.

Could you send the iCLA again?

**Comment by Redick01** [comment]
OK，I was sent the correct icla pdf



发自我的iPhone


------------------ Original ------------------
From: Willem Jiang ***@***.***&gt;
Date: Mon,May 31,2021 8:59 PM
To: dromara/shenyu ***@***.***&gt;
Cc: liupenghui ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [dromara/shenyu] CLAs signed status of the major contributors (#1461)





  
I am so sorry, the ***@***.*** is error, my correct email is ***@***.***
  
Please resend the iCLA with right email address with it.

**Comment by WillemJiang** [comment]
> > [jiang950526@gmail.com](mailto:jiang950526@gmail.com) sent the icla file, but [jiang950526@qq.com](mailto:jiang950526@qq.com) is written in the icla.pdf. So use [jiang950526@qq.com](mailto:jiang950526@qq.com) to search in the icla.txt may find the item. [jiang950526@qq.com](mailto:jiang950526@qq.com) is a valid mail address.
> 
> yes, 2 email addresses are valid, I used [jiang950526@gmail.com](mailto:jiang950526@gmail.com) sent the icla file, but [jiang950526@qq.com](mailto:jiang950526@qq.com) is written in the icla.pdf

I can find the jiang950526@qq.com in the icla.txt file, if you are using this mailbox, we just need to update the table file for it.

**Comment by tuohai666** [comment]
Thanks for the help of WillemJiang and the ASF secretary,  all of the problems have been solved:

For 1 & 2, Willem confirmed these two by alternative emails.
For 3 & 4, The ASF secretary received the iclas and sent the receipt acknowledgement.

- [ ] 1. LL2104@163.com is another email of Liang Liu. While the email signed in icla is midnight2104@foxmail.com .
- [ ] 2. jiang950526@gmail.com sent the icla file, but jiang950526@qq.com is written in the icla.pdf. 
- [ ] 3. 11090829@qq.com sent the icla file, but 11090289@qq.com is written in the icla.pdf. 11090289@qq.com is not a valid mail address because of a typo. I suggested Penghui Liu update the icla.pdf and re-send.
- [ ] 4. wuudongdong@gmail.com Dongdong Wu signed his name typed in a script font that does not constitute a signature. I suggested that he update the icla.pdf and re-send.

**Comment by WillemJiang** [comment]
I just checked the iclas.txt file, this below emails are in the iclas.txt
"midnight2104@foxmail.com",
"jiang950526@qq.com",
"11090829@qq.com"
"wuudongdong@gmail.com"

**Comment by WillemJiang** [comment]
@tuohai666  Please update those emails into the table.

**Comment by tuohai666** [comment]
@WillemJiang Done. I have just update those emails into the table.
