### ISSUE TITLE
used Java regular expressions to rewrite uri in rewrite plugin

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1494]
Hi Community：

Programs ：

in  org.apache.shenyu.common.dto.convert.RewriteHandle mybe  like this 

```

    /**
     * rewrite uri.
     */
    private String rewriteURI;
    
    private String regex;  
    
    private String replace;
```

then in RewritePlugin

```
String path =  exchange.getRequest().getURI().getRawPath()
String rewritePath = path.replaceAll(regex, replace);
```

In shenyu-admin , insert regex and replace sql into plugin_handler 

#### Additional context

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by lahmXu** [comment]
ok
