### ISSUE TITLE
Shenyu Admin hold the metadata persistently？

### ISSUE THREAD

**Issue by zhangjh** [apache/incubator-shenyu#1504]
## Question

If the dubbo provider doesnot online already(may be service restarting, maybe service crashed...), the admin console will not refresh the registed metadata automatically? How does sheyu admin handle the "service discovery"?
I read the source code, it seems only handled service registration logic, no service  offline logic？

**Comment by yu199195** [comment]
used by dubbo-client。。

**Comment by zhangjh** [comment]
> used by dubbo-client。。

yes, I know. But the question is, if the dubbo provider lost, the request feels the error when call dubbo rpc failed, however if gateway remove the effectiveless metadata in that scene, the request feels the error immediately, so it doesn't need to call the none exist dubbo service again.

**Comment by KevinClair** [comment]
Do you mean there is necessary to check heartbeat like `divide plugin`?

**Comment by zhangjh** [comment]
> Do you mean there is necessary to check heartbeat like `divide plugin`?

No, What I mean is that when the service is down, the metadata is still there, and the gateway reports an error message that the service provider does not exist. 
Can it be changed to delete the metadata when the service goes offline, so that the gateway can directly perceive the error message and no longer need to To call the service.

我是说，当dubbo服务挂掉的时候，网关是不是可以直接感知到，而不需要再去调用rpc的时候才发现服务不存在提供者了。现在貌似元数据信息是持久化的？服务不在线了，但是路由映射还是存在？

**Comment by KevinClair** [comment]
> > Do you mean there is necessary to check heartbeat like `divide plugin`?
> 
> No, What I mean is that when the service is down, the metadata is still there, and the gateway reports an error message that the service provider does not exist.
> Can it be changed to delete the metadata when the service goes offline, so that the gateway can directly perceive the error message and no longer need to To call the service.
> 
> 我是说，当dubbo服务挂掉的时候，网关是不是可以直接感知到，而不需要再去调用rpc的时候才发现服务不存在提供者了。现在貌似元数据信息是持久化的？服务不在线了，但是路由映射还是存在？

Got it, shenyu will support it in the future.Thanks for your advice.

**Comment by yu199195** [comment]
> No, What I mean is that when the service is down, the metadata is still there, and the gateway reports an error message that the service provider does not exist.
Can it be changed to delete the metadata when the service goes offline, so that the gateway can directly perceive the error message and no longer need to To call the service.


Dubbo metada is the service interface,  not instance  do  you know?   if dubbo instance down, used by dubbo regsiter center.

the router is mean the user config.

**Comment by zhangjh** [comment]
> > No, What I mean is that when the service is down, the metadata is still there, and the gateway reports an error message that the service provider does not exist.
> > Can it be changed to delete the metadata when the service goes offline, so that the gateway can directly perceive the error message and no longer need to To call the service.
> 
> Dubbo metada is the service interface, not instance do you know? if dubbo instance down, used by dubbo regsiter center.
> 
> the router is mean the user config.
Do not agree very much. Metadata almost automatically registered according to the method marked with annotation `@ShenyuDubboClient`.
It stands to reason that, it should be automatically delete after the rpc service instance does not exist.
For example, after a certain method is abandoned, there will be some useless mapping information in the shenyu-admin console. Of course, the admin console provides a manual delete operation, which will add some additional maintenance work.

不是很认同，元数据是根据标上了注解的方法自动注册上来的，按理说方法实例不存在后理应被自动删除掉。
比方说，某个方法或应用在废弃之后，管理控制台会存在一些无用的映射信息。当然控制台提供了手动删除操作，会增加一些额外的维护工作。

**Comment by yu199195** [comment]
metadata can update,  if service and method changed.   Do you really understand the relationship between metadata and routing?

if dubbo service have 3 instance， Is it necessary to register 3  instance？  If only one is registered, does one of them go down and need to be deleted? 

so  result metadata is have only one,   but instance have more .  And it instance  depends on the dubbo registry。
