### ISSUE TITLE
Is shenyu support Gray released to spring cloud

### ISSUE THREAD

**Issue by joewee** [apache/incubator-shenyu#1509]
## Question

Is shenyu support Gray released to spring cloud？
Thanks！

**Comment by KevinClair** [comment]
Hello, this is our plan for the next version #1233 . If you have good idea, you can send pull request.

**Comment by midnight2104** [comment]
hi, shenyu is support in current, for details ,pls see  https://shenyu.apache.org/docs/next/plugin-center/proxy/spring-cloud-plugin/
