### ISSUE TITLE
ShenYu-admin Support oracle database

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1536]
Hi Community

Now shenyu-admin storage support mysql and h2 , now need to add oracle support, welcome everyone to participate！

#### Additional context

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by magicalxiaochen** [comment]
i want to try this.

**Comment by 0x12FD16B** [comment]
I'd like to participate this task.

**Comment by yu199195** [comment]
@magicalxiaochen hi ,please add me vchat xixy199195,  I invite you to join the developer group

**Comment by renzhuyan** [comment]
can I still participate?
