### ISSUE TITLE
About automatic routing of Shenyu

### ISSUE THREAD

**Issue by rottenmu** [apache/incubator-shenyu#1542]
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Additional context

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by SaberSola** [comment]
can you describe it in detail about automatic routing？

**Comment by midnight2104** [comment]
Are there any questions now? I'll close the issue. if you still have questions, please setup another issue.
