### ISSUE TITLE
Can Shenyu weak admin  in the future.Because I want to use other config center,such as nacos,apollo.

### ISSUE THREAD

**Issue by rottenmu** [apache/incubator-shenyu#1543]
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Additional context

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by KevinClair** [comment]
Now you can do this if you use Nacos as the data synchronization.

**Comment by yu199195** [comment]
@rottenmu  hi， I suggest you use shenyu-admin to configure the routing rules

if you not use shenyu-admin， The data format will be more complex ， also you can used nacos。

you can see this ` org.apache.shenyu.sync.data.nacos.NacosSyncDataService` .

**Comment by midnight2104** [comment]
for details of Nacos sync data, pls see  https://shenyu.apache.org/docs/next/user-guide/use-data-sync#nacos-synchronization-config
