### ISSUE TITLE
Add MetricsReporterTest for UT

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1569]
## Task

this class path is `org.apache.shenyu.metrics.reporter.MetricsReporter`

If you're interested, you can create a test class for it that covers 80 percent of the code.

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by tangtian8** [comment]
please assigned to me,ths

**Comment by joakapp** [comment]
主要就在sou-gateway-admin 上操作选择器时，配置handler(处理器)时添加相关配置信息，可以保存，但是数据没有入库。再次点击查看数据就是空的

**Comment by joakapp** [comment]
只要再次刷新数据就会消失不见，在数据库selector表中也没有数据。（使用的数据库为8.0.23mysql）
