### ISSUE TITLE
Shenyu logback and slf4j replace these with `LogUtils`

### ISSUE THREAD

**Issue by zhaiweij** [apache/incubator-shenyu#1596]
## Task

Replace the logging method of all modules
Task List:

- [ logback and slf4j replace these with `LogUtils`] task1

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by yu199195** [comment]
good lucky to you

**Comment by dengliming** [comment]
@zhaiweij Any progress?

**Comment by zhaiweij** [comment]
> @zhaiweij Any progress?

This time I did some of the task of removing Lombok, and then consider continuing to do it in LogUtils
