### ISSUE TITLE
add sso plugin

### ISSUE THREAD

**Issue by impactCn** [apache/incubator-shenyu#1597]
SSO may be a bit biased towards business needs, so I want to do some general configuration to complete it.

**Comment by yu199195** [comment]
Hi ， We already have the jwt plugin and the auth2 plugin in the works.
Can you send this feature to the mailing list （dev@shenyu.apache.org）?

**Comment by Zhoutzzz** [comment]
CAS is the standard process of SSO, if you just do some general configuration, could you consider to do this on oauth2 plugin, the oauth2 plugin i'm testing features, If you are interested, you can talk to me.
