### ISSUE TITLE
The lastes version is 2.3.0? 

### ISSUE THREAD

**Issue by ypg521** [apache/incubator-shenyu#1619]
## Question

I add dependency to pom :
```
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>soul-spring-boot-starter-gateway</artifactId>
            <version>2.3.0</version>
        </dependency>
``` 
But it can not be downloaded.
I also can not found it  in https://mvnrepository.com use keyword 'soul-spring-boot-starter-gateway'

**Comment by yu199195** [comment]
Hi ,  you can see this : https://search.maven.org/search?q=a:soul , it maybe  2.3.0-RELEASE

**Comment by ypg521** [comment]
> Hi , you can see this : https://search.maven.org/search?q=a:soul , it maybe 2.3.0-RELEASE

It's OK

**Comment by ypg521** [comment]
I want a gateway that support multi-protocol,
for example:
http1 listen at 80 port ,and the same time  http2 listen at 81 port 
Can `shenyu` do ?

**Comment by KevinClair** [comment]
Plugin `Divide` can do this, when the same method deploy with the different port at the same time.
