### ISSUE TITLE
Is it the gateway's job to prevent duplicate client submissions? Do you have this function? If not, will you consider adding it?

### ISSUE THREAD

**Issue by objectboy2016** [apache/incubator-shenyu#1620]
If inscribe!!!

**Comment by KevinClair** [comment]
Do you mean to do idempotent control?

**Comment by objectboy2016** [comment]
> Do you mean to do idempotent control?
Yes, can this be done in the gateway?

**Comment by objectboy2016** [comment]
> Do you mean to do idempotent control?
Yes, can this be done in the gateway?

**Comment by KevinClair** [comment]
Customized development is recommended because it is partial to business attributes.
