### ISSUE TITLE
哪里有 shenyu admin模块的前段 源码

### ISSUE THREAD

**Issue by wangfl-13923768399** [apache/incubator-shenyu#1637]
## Question

// your question here;

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by dengliming** [comment]
Duplicate of [https://github.com/apache/incubator-shenyu/issues/1638](https://github.com/apache/incubator-shenyu/issues/1638)
