### ISSUE TITLE
Add plugin for support  modify response  info 

### ISSUE THREAD

**Issue by SaberSola** [apache/incubator-shenyu#1652]
for example: if you response body is a json like this:{
    "code":0,
    "msg":"sucess",
    "data":{
        "nameInfo":{
            "name":"test"
        },
        "body":{
            "age":"18"
        }
    }
}
you want to replace the  key of  parameters "name" to "realName",you can  modify the json ,then the body json is
{
    "code":0,
    "msg":"sucess",
    "data":{
        "nameInfo":{
            "realName":"test"
        },
        "body":{
            "age":"18"
        }
    }
}

**Comment by xiaoshen11** [comment]
please assgin to me
