### ISSUE TITLE
How to customize a PredicateJudge？

### ISSUE THREAD

**Issue by 624217563** [apache/incubator-shenyu#1661]
## Question

Hello，I wanna customize a PredicateJudge,but I don't konw how to do it.Does there have a reference documents to teach how to do it?Thanks anyway,looking forward to that.

**Comment by Zhoutzzz** [comment]
Can you talk more details, like you wanna customize PredicateJudge in where and what do you wanna impletement feature.

**Comment by 624217563** [comment]
I wanna customize PredicateJudge in Rule condition and I wanna implement a 'in' feature.By it,I can set a configration that match some rule.For example,I set a condition that ip in (1.1.1.1,2.2.2.2,3.3.3) and the request real ip is 1.1.1.1,so the request can be matched.

**Comment by Zhoutzzz** [comment]
You can extends **AbstractMatchStrategy** class, reference **AndMatchStrategy** or **AndMatchStrategy**.I hope this reply can resolve your question, good luck.

**Comment by yu199195** [comment]
can used shenyu spi  to customize  PredicateJudge

**Comment by 624217563** [comment]
> can used shenyu spi to customize PredicateJudge

ok,I'll have a try.Thanks a lot!
