### ISSUE TITLE
About health check for divide plugin

### ISSUE THREAD

**Issue by kevinw66** [apache/incubator-shenyu#1665]
Currently we have two ways to achieve health check when using divide plugin.

1、UpstreamCheckService
* The problem is, this will delete config from database. this will cause plenty of problem, what if users don't know about this feature, and they restart shenyu server after config was deleted, and so on and so on, this will make them confused and wonder if the program has a bug or not.

2、UpstreamCacheManager
* This still like a demo code and should be complete.

**Comment by KevinClair** [comment]
Heart beat check fail, `UpstreamCheckService` will delete the configuration of selector in the divide plugin.The purpose of this is to remind users that your service request has failed or is down, or something is wrong.I don't think it's a problem to delete the configuration.

**Comment by kevinw66** [comment]
> Heart beat check fail, `UpstreamCheckService` will delete the configuration of selector in the divide plugin.The purpose of this is to remind users that your service request has failed or is down, or something is wrong.I don't think it's a problem to delete the configuration.

1、I think the health check logic should not write in admin, but in divide plugin module.
2、The config added by user should deleted by user himself, maybe print a log to remind user is enough?
3、If the machine is currently has bad network, maybe the configuration should not be deleted? If users restart shenyu-admin in the same time, the configuration won't be recovery.

**Comment by KevinClair** [comment]
This view will be discussed later whether configuration needs to be deleted in case of failure of service request;
Actually If the machine is currently has bad network, shenyu will delete the configuration, but in a few seconds, shenyu will add the configuration automatically.

**Comment by kevinw66** [comment]
> Actually If the machine is currently has bad network, shenyu will delete the configuration, but in a few seconds, shenyu will add the configuration automatically.

Yeah, But if user restart shenyu-admin in the same time, the configuration will be deleted forever.

**Comment by ttttangzhen** [comment]
I don't think we should help users delete the configuration. The health check is started by default, which will make users very confused.If the user needs this function, the user can start the health check by himself, or maybe we can modify the state of the selector

**Comment by KevinClair** [comment]
> > Actually If the machine is currently has bad network, shenyu will delete the configuration, but in a few seconds, shenyu will add the configuration automatically.
> 
> Yeah, But if user restart shenyu-admin in the same time, the configuration will be deleted forever.

I know, so we need to discuss whether configuration needs to be deleted.
