### ISSUE TITLE
[Community：Meetings] Apache ShenYu(incubating) Open And Governance Meetings Invitation

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1669]
Hi Community

Welcome to join the community's open governance meetings, if you are interested in.

Details of the meetings are as follows : 

time : 2021/05/13-2021/08/05 21:00-22:30(GMT+08:00) beijing

Mode : online

Language : Chinese or English

Subject :

1. Function Development.
2. Release Apache ShenYu 2.4.0.
3. Apache ShenYu Website(https://shenyu.apache.org) Build and IP clear.
4. Community Governance.

You can join in the following ways:
1. https://meeting.tencent.com/s/JN9K9k0PLP6O  .
2. open tencent meeting app, meeting id is `740836851`  meeting password `123456`.
3. tel to +8675536550000 (Mainland China).
4. tel to +85230018898 (hongkong China).

Notes:
1.Please mute when joining the meeting.
2.Please change your name when you join the meeting. the name rule is `role-githubId`,such as : `Committer-yu199195` , `Contributor-yu199195`, `Community-yu199195`.

Welcome to join us, Thanks!

**Comment by KevinClair** [comment]
Got it, we can discuss #1666  at the meeting tomorrow evening

**Comment by zhaiweij** [comment]
Got it,I will participate in the discussion of Apache ShenYu Website (https://shenyu.apache.org) Build and IP clear.






On 06/23/2021 ***@***.***> wrote：

Hi Community

Welcome to join the community's open governance meetings, if you are interested in.

Details of the meetings are as follows :

time : 2021/05/13-2021/08/05 21:00-22:30(GMT+08:00) beijing

Mode : online

Language : Chinese or English

Subject :

Function Development.
Release Apache ShenYu 2.4.0.
Apache ShenYu Website(https://shenyu.apache.org) Build and IP clear.
Community Governance.

You can join in the following ways:

https://meeting.tencent.com/s/JN9K9k0PLP6O .
open tencent meeting app, meeting id is 740836851 meeting password 123456.
tel to +8675536550000 (Mainland China).
tel to +85230018898 (hongkong China).

Notes:
1.Please mute when joining the meeting.
2.Please change your name when you join the meeting. the name rule is role-githubId,such as : Committer-yu199195 , Contributor-yu199195, Community-yu199195.

Welcome to join us, Thanks!

**Comment by Asxing** [comment]
I hope you will participate in this discussion, and I will chair the meeting :)

**Comment by midnight2104** [comment]
I want join the meeting and  build Apache ShenYu Website .

**Comment by ttttangzhen** [comment]
Thanks for the invitation , I want join this meeting:-)

**Comment by nuo-promise** [comment]
get it

**Comment by lw1243925457** [comment]
join

**Comment by vinceDa** [comment]
Thanks for your invitation , I'll join this meeting!

**Comment by Zhoutzzz** [comment]
Thanks for your invitation , I'll join this meeting!

**Comment by Ting97** [comment]
Thanks for your invitation , I'll join this meeting!

**Comment by lxl910128** [comment]
I'm interested in

**Comment by JooKS-me** [comment]
Thanks for your invitation , I'll join this meeting!

**Comment by yunwu** [comment]
Thanks for your invitation , I'll join this meeting!

**Comment by songyuequan** [comment]
Thanks for your invitation , I'll join this meeting!
