### ISSUE TITLE
请问如何从ServerHttpRequest获取body内容并解析？

### ISSUE THREAD

**Issue by jaychoubaby** [apache/incubator-shenyu#1672]
## 请问如何从ServerHttpRequest获取body内容并解析？

我从ServerWebExchange 获取ServerHttpRequest，然后通过
Flux<DataBuffer> body = request.getBody();
拿到body，可是并没有办法从body中获取请求内容，请问需要怎么做？

**Comment by Zhoutzzz** [comment]
For example, my request body content is json string, I can process like this:
`exchange.getRequest().getBody()
            .map(x -> {
                byte[] b = new byte[x.readableByteCount()];
                x.read(b);
                String string = new String(b, StandardCharsets.UTF_8);
                return string;
            }).subscribe();`

**Comment by jaychoubaby** [comment]
> 比如我的请求正文内容是json字符串，我可以这样处理：
> 
> ```java
> 交换。获取请求（）。获取身体（）
>             .map(x - > {
>                  byte [] b =  new  byte [x . readableByteCount()];
>                 × 。阅读（b）；
>                 String string =  new  String (b, StandardCharsets . UTF_8 );
>                 返回字符串；
>             }) 。订阅（）;
> ```

可是我使用的是form-data提交的，并且上传了文件，这种方法没办法解析出body中的内容
![001](https://user-images.githubusercontent.com/26641387/123566978-ae866480-d7f3-11eb-9103-19871f84c29e.jpg)

**Comment by yu199195** [comment]
pls in english， now we will close it
