### ISSUE TITLE
Parse the response

### ISSUE THREAD

**Issue by yzydhf** [apache/incubator-shenyu#1673]
## Question
Currently we have a situation where we need to process the response, so we need to parse the response body to get the specific data, and then do the following. Here is the process (for example  internationalization handler)：

public static Mono<Void> result(ServerHttpRequest request, ClientResponse clientResponse, ServerHttpResponse response) {
//        DataBufferFactory bufferFactory = response.bufferFactory();
//        ServerHttpResponseDecorator decoratedResponse = new ServerHttpResponseDecorator(response) {
//            @Override
//            public Mono<Void> writeWith(Publisher<? extends DataBuffer> body) {
//                if (body instanceof Flux) {
//                    Flux<? extends DataBuffer> fluxBody = (Flux<? extends DataBuffer>) body;
//                    return super.writeWith(fluxBody.buffer().map(dataBuffers -> {
//
//                        DataBuffer dataBuffer = new DefaultDataBufferFactory().join(dataBuffers);
//                        byte[] content = new byte[dataBuffer.readableByteCount()];
//
//                        dataBuffer.read(content);
//                        DataBufferUtils.release(dataBuffer);
//
//                        String responseStr = new String(content, Charsets.UTF_8);//Garbled
//
//                        String result = "";
//                        try{
//                            ObjectMapper om = new ObjectMapper();
//                            om.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
//                            JsonNode jsonNode = om.readTree(responseStr).get(Constants.RESPONSE_CODE_KEY);//Parse error
//                            if(null == jsonNode){
//                                HttpResult httpResult = JsonUtils.parseObject(responseStr, HttpResult.class);
//                                if (!httpResult.isSuccess()) {
//                                    // internationalization
//                                    I18nHandle.errorMsgI18n(httpResult, request.getHeaders().getFirst("Accept-Language"));
//                                }
//                                result = om.writeValueAsString(httpResult);
//                            }
//                        }catch (Exception e){
//                            e.printStackTrace();
//                        }
//                        this.getDelegate().getHeaders().setContentLength(result.getBytes().length);
//                        return bufferFactory.wrap(result.getBytes());
//                    }));
//                }
//                // if body is not a flux. never got there.
//                return super.writeWith(body);
//            }
//        };
        BodyExtractor<Flux<DataBuffer>, ReactiveHttpInputMessage> bodyExtractor = BodyExtractors.toDataBuffers();
        return response.writeWith(clientResponse.body(bodyExtractor));
    }
The above code ‘String responseStr = new String(content, Charsets.UTF_8); ’  appears garbled。
This causes subsequent JSON parsing errors。

**Comment by SaberSola** [comment]
Maybe your business is garbled,or you can check the HttpMessageConverter
