### ISSUE TITLE
How to parse data from the body?

### ISSUE THREAD

**Issue by jaychoubaby** [apache/incubator-shenyu#1684]
## How to parse data from the body?
Original question #1672

I got the body, but I can't parse it. How can I get the content from it?

![123566978-ae866480-d7f3-11eb-9103-19871f84c29e](https://user-images.githubusercontent.com/26641387/123720763-6b8dc500-d8b7-11eb-8738-e7af79c92c98.jpg)

**Comment by jaychoubaby** [comment]
I can get the data in params, but the data in the body seems unable to be parsed. What should I do?

**Comment by yu199195** [comment]
what version used？

**Comment by jaychoubaby** [comment]
Version 2.0

**Comment by jaychoubaby** [comment]
> what version used？

v2.3.0-release

**Comment by ttttangzhen** [comment]
Hi @jaychoubaby 
The formdata body is defined by Http.I think you'd batter use application/json.
And If you want to read request body , you need to wapper request.you can use ServerHttpRequestDecorator to do this.
for more details, you can see
(https://stackoverflow.com/questions/45240005/how-to-log-request-and-response-bodies-in-spring-webflux)
