### ISSUE TITLE
cleanup the constants

### ISSUE THREAD

**Issue by dengliming** [apache/incubator-shenyu#1692]
- cleanup constants in `org.apache.shenyu.common.constant.Constants`
   Some field in `Constants` is never used. we should remove it. and consider move some common constants to `org.apache.shenyu.common.constant.Constants`. e.g. `"http://"`、`"https://"`

**Comment by param-thakker** [comment]
Hi @dengliming, can I work on this please? Also, which constants are you talking about to move to org.apache.shenyu.common.constant.Constants?

**Comment by dengliming** [comment]
@param-thakker Please feel free to submit a PR.

**Comment by KevinClair** [comment]
By the way, do we need to integrate constant classes?For example, `org.apache.shenyu.common.constant.HttpConstants` and `org.apache.shenyu.common.constant.ResourceTypeConstants`.

**Comment by param-thakker** [comment]
@dengliming, I tried to push my local changes but it is saying that permission is denied for me. Can you please tell me how do I push my changes?

**Comment by dengliming** [comment]
@param-thakker You should `fork` the repo first. see more detail in https://shenyu.apache.org/community/contributor/

**Comment by param-thakker** [comment]
@dengliming I figured out the error! I have submitted a PR. Please review it and let me know if anything else needs to be done.
