### ISSUE TITLE
Update the issue template

### ISSUE THREAD

**Issue by dengliming** [apache/incubator-shenyu#1696]
Fix some broken links in pr/issue template. e.g. 

`https://shenyu.apache.org/projects/shenyu/contributor/` => `https://shenyu.apache.org/community/contributor/`
`Soul version` => `ShenYu version` 

check list:
- https://raw.githubusercontent.com/apache/incubator-shenyu/master/.github/PULL_REQUEST_TEMPLATE.md
- https://github.com/apache/incubator-shenyu/blob/master/.github/ISSUE_TEMPLATE/bug-report.md
- https://github.com/apache/incubator-shenyu/blob/master/.github/ISSUE_TEMPLATE/feature-request.md
- https://github.com/apache/incubator-shenyu/blob/master/.github/ISSUE_TEMPLATE/task.md

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by rbrishabh** [comment]
> I would like to take this one.

Thanks for looking into this @RhnSharma!
