### ISSUE TITLE
Refactor loadBalance some code

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1703]
#### Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is. Ex. I have an issue when [...]

#### Describe the solution you'd like

A clear and concise description of what you want to happen. Add any considered drawbacks.

#### Additional context

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

**Comment by hermeshephaestus** [comment]
Does a related pr already exist? @yu199195
