### ISSUE TITLE
<test> (<shenyu-plugin-modify-response>) : add test case

### ISSUE THREAD

**Issue by xiaoshen11** [apache/incubator-shenyu#1704]
## Task

A clear and concise description of Task

Task List:

- [ ] add tets case for shenyu-plugin-modify-response
- [ ] add tets case for shenyu-spring-boot-starter-plugin-modify-response

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

**Comment by Banana1995** [comment]
I wanna have a try, pls assign it to me

**Comment by xiaoshen11** [comment]
> I wanna have a try, pls assign it to me

@Banana1995 sorry, I have completed this task

**Comment by Banana1995** [comment]
> > I wanna have a try, pls assign it to me
> 
> @Banana1995 sorry, I have completed this task

Alright, that's fine
