### ISSUE TITLE
[Question] h2 support insert ingore into in Mysql model

### ISSUE THREAD

**Issue by plutokaito** [apache/incubator-shenyu#1706]
I find h2 support `INSERT IGNORE INTO <table> (<columns>) SELECT in MySQL Mode` since  version 1.4.198, and now apache shenyu used version 1.4.200. But in issue #1677, "The sql of h2 can't support the keyword of 'ignore'", I don't think so. I wanna modify like 
```
datasource:
  url: jdbc:h2:mem:~/shenyu;MODE=MySQL;DB_CLOSE_DELAY=-1
```

**Comment by dengliming** [comment]
@plutokaito Thanks for reporting this issue. You can submit a PR to fix this.
