### ISSUE TITLE
[Bug] when getInetAddress return null, method isHostConnector in UpstreamCheckUtils always return true;

### ISSUE THREAD

**Issue by plutokaito** [apache/incubator-shenyu#1707]
## Environment

- ShenYu version(s): master

## Steps to reproduce
org.apache.shenyu.common.utils.UpstreamCheckUtilsTest#testNotIp , in this method, I run it, it alway return true.

## Debug logs
![image](https://user-images.githubusercontent.com/7955473/124373328-0de8e680-dcc4-11eb-9827-6b85f067a49a.png)
 thus isHostConnector can't catch any exception, and return true.

**Comment by dengliming** [comment]
Thanks. for reporting this issue. but I don't fully understand what you mean. Can you just give me a simple example to reproduce this case?
