### ISSUE TITLE
How to expose self url and retrieve apis

### ISSUE THREAD

**Issue by ichenhe** [apache/incubator-shenyu#1729]
## Question

Actually, these are two questions:

1. How to expose self url?
2. How to retrieve all the api's information.

My use case is try to aggregate all the api docs of the microservice together. To do that, I have to follow these two steps:

1. Let my gateway application provide swagger-ui pages. I have added the [springdoc](https://springdoc.org/#spring-webflux-support) support, but when I visit the swagger-ui url (`/swagger-ui.html`) , it says `{"code":-102,"message":"Rule not found!","data":null}`. It seems that shenyu treat it as a request that needs to be forwarded, how can I fix that?
2. Config my swagger-ui to show all the api backend. So I need all informations. In spring cloud gateway, [`RouteDefinitionLocator `](https://github.com/springdoc/springdoc-openapi-demos/blob/master/springdoc-openapi-microservices/gateway-service/src/main/java/org/springdoc/demo/services/gateway/GatewayApplication.java#L31) can be used to achiece that. What is the equivalent in shenyu?

**Comment by yu199195** [comment]
you can config redirect plugin to fix
