### ISSUE TITLE
The config shenyu > client > props > port  is duplicate with   spring server.port config

### ISSUE THREAD

**Issue by fixwater** [apache/incubator-shenyu#1731]
#### Is your feature request related to a problem? Please describe

In docs (https://shenyu.apache.org/zh/projects/shenyu/register-center-access/)  when access zookeeper , a springmvc(springboot) client have to config

~~~
shenyu:
  client:
    registerType: zookeeper
    serverLists: localhost:2181
    props:
      contextPath: /http
      appName: http
      port: 8188  
      isFull: false
~~~

The config shenyu > client > props > port  is duplicate with   spring server.port config

#### Describe the solution you'd like

need not config 【shenyu > client > props > port】 config ， just reuse  spring server.port config as port value

**Comment by KevinClair** [comment]
Hello, it is a good idea, can you submit pull request ? we will review it.

**Comment by zhaiweij** [comment]
> Hello, it is a good idea, can you submit pull request ? we will review it.

I go to improve this
