### ISSUE TITLE
shenyu-admin做多个实例， 在 shenyu-admin  页面上做增删改的接口， 只会调用 shenyu-admin后端 多个后端服务实例之一  服务接口， 这导致 shenyu-admin 同步到 shenyu-bootstrap 的时候，网关服务实例的数据不一致

### ISSUE THREAD

**Issue by wangfl-13923768399** [apache/incubator-shenyu#1751]
## Question

// your question here;

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by KevinClair** [comment]
Which way is used for data synchronization?

**Comment by ttttangzhen** [comment]
Hi, 
For the admin module, there is no need to use the cluster to start, or you can use only one web-console. 
If there is a proxy before admin module, and you want to start the cluster also. I have two suggestions

1. you can use Http Long-Polling to synchronize data. It will regularly check the database for changes every 5 minutes.
2. The best way is to use third-party components such as `nacos` to synchronize data

**Comment by yu199195** [comment]
pls in english
