### ISSUE TITLE
develop plugin by self?

### ISSUE THREAD

**Issue by hirCodd** [apache/incubator-shenyu#1753]
## Question

develop plugin must use selector?
e.g. I want to develop a plugin of protocol conversion,I must use selector?

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by KevinClair** [comment]
Please see here [Plugin](https://shenyu.apache.org/zh/projects/shenyu/custom-plugin/).

**Comment by hirCodd** [comment]
thanks!
