### ISSUE TITLE
add realIp plugin

### ISSUE THREAD

**Issue by impactCn** [apache/incubator-shenyu#1756]
When doing trusted authorization services, the real ip of the other party is generally required, 
but after shenyu forwarding, the real ip becomes the ip of shenyu server, 
so I want to add this function.

**Comment by KevinClair** [comment]
Where you want to get the real ip address in your application?

**Comment by impactCn** [comment]
> 你想在你的应用程序中在哪里获得真实的 IP 地址？

yep

**Comment by impactCn** [comment]
> Where you want to get the real ip address in your application?

yep

**Comment by yu199195** [comment]
see https://shenyu.apache.org/projects/shenyu/custom-parsing-ip-and-host/

**Comment by KevinClair** [comment]
Can `HTTP Headers` solve this problem?
