### ISSUE TITLE
shenyu-examples-http

### ISSUE THREAD

**Issue by LionYe** [apache/incubator-shenyu#1757]
## Question
shenyu-examples-http register error
2021-07-13 11:38:30.134 ERROR 13400 --- [or_consumer_-26] o.a.s.r.client.http.utils.RegisterUtils  : http client register error: {"appName":"http","contextPath":"/http","path":"/http/order/save","pathDesc":"Save order","rpcType":"http","ruleName":"/http/order/save","enabled":true,"host":"10.102.22.234","port":8189,"registerMetaData":false} 

![image](https://user-images.githubusercontent.com/20884868/125386681-4331ba80-e3cf-11eb-84bb-70fcb3d55869.png)

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

**Comment by KevinClair** [comment]
Did you start `admin`?

**Comment by LionYe** [comment]
> 你开始了`admin`吗？

yes、I followed the official website document to start the admin and api gateway layer
![image](https://user-images.githubusercontent.com/20884868/125387218-2053d600-e3d0-11eb-8685-2294bad17eb9.png)

**Comment by yu199195** [comment]
please update code

**Comment by LionYe** [comment]
> please update code

Why can't I start according to the operation example？

**Comment by KevinClair** [comment]
Hello, I run it successfully with master branch code,can you try it again?

**Comment by LionYe** [comment]
I think the start of the document starts with the shenyu-admin method. The jar package can be updated. There is a problem with the admin package of this jar. I re-pull the master branch and can run without looking at the document.
![image](https://user-images.githubusercontent.com/20884868/125770914-729725a7-dc21-4b6c-8914-c81752d1b22f.png)

**Comment by yu199195** [comment]
this doc can update。 you can see 2.3.0 doc
