### ISSUE TITLE
i find WebsocketSyncDataService s executor.scheduleAtFixedRate some times can not execute

### ISSUE THREAD

**Issue by kangarooking** [apache/incubator-shenyu#1759]
some times executor.scheduleAtFixedRate can not execute, i need to restart bootstrap. but if it in prod，it is very serious.

**Comment by yu199195** [comment]
why executor.scheduleAtFixedRate can not execute ？ its jdk bug ？ or  your  local environmental issues?

**Comment by midnight2104** [comment]
If there are still questions, please resubmit a issue
