### ISSUE TITLE
restart shenyu-bootstrap,it always show port already used

### ISSUE THREAD

**Issue by kangarooking** [apache/incubator-shenyu#1760]
when i restart bootstrap,it always show port already used,but i use mac command "lsof -i tcp:9195",this port is not in use, i dont know what the problem is

**Comment by kangarooking** [comment]
Change the port, it can start，but  I feel strange and tedious.

**Comment by KevinClair** [comment]
Maybe it's not Shenyu's bug.Can you check again?

**Comment by ChoviWu** [comment]
Kill the computer java process,  retry?
