### ISSUE TITLE
The 3 second timeout is dead in code(HttpClientPluginConfiguration)

### ISSUE THREAD

**Issue by kangarooking** [apache/incubator-shenyu#1762]
I set a 5 second timeout in admin. I want to test the functionality ,but my request always timeout at 3 second. I check code ,find The 3 second timeout is dead in code(HttpClientPluginConfiguration):

 c.addHandlerLast(new WriteTimeoutHandler(properties.getWriteTimeout(), TimeUnit.MILLISECONDS));
                        c.addHandlerLast(new ReadTimeoutHandler(properties.getReadTimeout(), TimeUnit.MILLISECONDS));

**Comment by kangarooking** [comment]
I want to know if I can del this timeout config,Will there be a problem？ because we will use it in prod

**Comment by KevinClair** [comment]
It can work, please don't delete it.Please see the line 93 in `org.apache.shenyu.plugin.divide.DividePlugin`

**Comment by kangarooking** [comment]
I know, but if "exchange.getAttributes().put(Constants.HTTP_TIME_OUT, ruleHandle.getTimeout());" the ruleHandle.getTimeout() > 3000 ,It doesn't work

**Comment by KevinClair** [comment]
Hello @dengliming, did you have any suggestion.

**Comment by SaberSola** [comment]
Hi , I think The 3 second timeout in code(HttpClientPluginConfiguration) is the global Configuration, it‘s means The http readTimeout is 3 second,if you want set timeout > 3000,you should set the global timeout > 3000,then  you can set the  ruleHandle timeOut

**Comment by kangarooking** [comment]
ye I know,I just hope this can dynamic configuration or more obvious in shenyu subsequent versions. I hope shenyu  better and better.
