### ISSUE TITLE
LoggingPlugin couldn't print log info?

### ISSUE THREAD

**Issue by liaomengge** [apache/incubator-shenyu#1772]
## Environment

- ShenYu version(s): [e.g. 2.2.1]

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by dengliming** [comment]
https://shenyu.apache.org/zh/projects/shenyu/logging-plugin/

**Comment by dengliming** [comment]
@liaomengge Can you provide more details?
