### ISSUE TITLE
Question about selector config

### ISSUE THREAD

**Issue by ttttangzhen** [apache/incubator-shenyu#1777]
For the configuration of selector, I have two doubts:
1. I don’t know what the `continued` field means, and I don’t see where it is used in the code.
2. This can be considered a bug, this If we choose FULL_FLOW, the gateway will choose the last `rule`, for some plugin, just like `param-mapping plugin`,this will not meet expectations. 

in org.apache.shenyu.plugin.base.AbstractShenyuPlugin#execute
```
            RuleData rule;
            if (selectorData.getType() == SelectorTypeEnum.FULL_FLOW.getCode()) {
                //get last
                rule = rules.get(rules.size() - 1);
            } else {
                rule = matchRule(exchange, rules);
            }
```

I suggest adjusting the logic here to FULL_FLOW to match specific rules

**Comment by yu199195** [comment]
Hi

1 . continued filed not used
2. if config FULL_FLOW ， its mean all request  match
