### ISSUE TITLE
soul admin注册nacos 异常

### ISSUE THREAD

**Issue by zl530380** [apache/incubator-shenyu#1800]
![image](https://user-images.githubusercontent.com/16401564/126455624-c8bcef80-d3ac-41ad-a8d1-2f1a1828f7a2.png)

**Comment by yu199195** [comment]
can  you modify title to english and update code?

**Comment by lw1243925457** [comment]
please use english, and discribe more detail.

**Comment by tuohai666** [comment]
Hi @zl530380 , Thanks for your report. Could you please change the title to English?
