### ISSUE TITLE
the table selector, uk->unique_name,I suggest update to uk->unique_plugin_id_name

### ISSUE THREAD

**Issue by kangarooking** [apache/incubator-shenyu#1807]
I think different plug-ins can have the same selector name

![shenyu-selector](https://user-images.githubusercontent.com/52196004/126626329-bced14ea-ee58-4de8-a07f-ae04df40469c.jpg)

**Comment by yu199195** [comment]
good idea, can you fix it ?

**Comment by kangarooking** [comment]
yes，i can，But I have to wait until this weekend

**Comment by tuohai666** [comment]
Hi @kangarooking , any progress? Please feel free to discuss here if you have any questions.
