### ISSUE TITLE
When will the version 2.4.0 be available?

### ISSUE THREAD

**Issue by 624217563** [apache/incubator-shenyu#1808]
## Question

we are planing to replace our gateway system by shenyu,and we find some functions which is compatible for our requirement in 2.4.0.I wanna know which branch is stable,so that we can use it.

**Comment by yu199195** [comment]
Hi

We are releasing apache version 2.4.0.  You can use it for the next 2 weeks.

**Comment by 624217563** [comment]
> Hi
> 
> We are releasing apache version 2.4.0. You can use it for the next 2 weeks.
Glad to receive your reply。
And now I wanna know which branch is suitable for us to use for testing,master or 2.4.0-release?

**Comment by 0x12FD16B** [comment]
@624217563 you can checkout to tag v2.4.0 and have a try.

**Comment by tuohai666** [comment]
> @624217563 you can checkout to tag v2.4.0 and have a try.

Agree. This tag is expected to be identical with the new release. But please note that the new release is still not published officially.

**Comment by 624217563** [comment]
> > @624217563 you can checkout to tag v2.4.0 and have a try.
> 
> Agree. This tag is expected to be identical with the new release. But please note that the new release is still not published officially.

I'll try it.Thank you.
