### ISSUE TITLE
shenyu gateway how to use consul acl Usually companies use consul acl ？

### ISSUE THREAD

**Issue by XiBeiWaQiang** [apache/incubator-shenyu#1820]
shenyu gateway how to use consul acl Usually companies use consul acl ？

**Comment by 0x12FD16B** [comment]
ACL is a security standard, do you mean any implement of this standard ?
If you mean, shenyu dose not support it currently.
Welcome you to participant shenyu contributor meeting and share your concrete usage scenario, we would like to discuss more detail.

**Comment by XiBeiWaQiang** [comment]
Because the operation and maintenance consul has set access permissions（acl token），shenyu need read or write consul  but not support set acl token   The same goes for zookpeer You cannot access ， that already have access control. （ user: xxx, pwd:  yyy）

**Comment by 0x12FD16B** [comment]
we will discuss it in recent contributor meeting, welcome you to participate to the discussion(we will send invite mail to dev subscribe). Or if you have any idea now, welcome to create a pull request to resolve it.

**Comment by tuohai666** [comment]
Hi @XiBeiWaQiang , The meeting is planned to hold on Thursday this week, please feel free to join us and share your idea.
In case you miss the meeting, please subscribe the dev mail list via:
https://shenyu.apache.org/community/subscribe-email/
