### ISSUE TITLE
Website copy/paste issue

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-shenyu#1826]
At the copyright part of your website, https://shenyu.apache.org/, you have a copy-paste issue

```
Apache Incubator, Apache, the Apache feather logo, the Apache EventMesh logo and the Apache Incubator project logo are trademarks of The Apache Software Foundation. 
```

I assume you copied this from `EventMesh` project. Please fix this.

**Comment by 0x12FD16B** [comment]
We are sorry for this mistake, we will fix it as soon as possible.

**Comment by yu199195** [comment]
Hi sheng 

Thanks, we have fixed！
