### ISSUE TITLE
Is the package not available in the Dromara warehouse

### ISSUE THREAD

**Issue by hqgordon** [apache/incubator-shenyu#1840]
## What should I do to use it now

Is the package not available in the Dromara warehouse? What should I do to use it now? Is there a successful POM file? Thank you

**Comment by KevinClair** [comment]
We will release the new version as soon as possible.

**Comment by hqgordon** [comment]
> We will release the new version as soon as possible.

So is there no way to do a use now? I am not a Java expert, please let me know if there is any way, thank you very much

**Comment by dengliming** [comment]
Try this https://shenyu.apache.org/projects/shenyu-2.3.0/overview/

**Comment by hqgordon** [comment]
> Try this https://shenyu.apache.org/projects/shenyu-2.3.0/overview/

not work ,thanks for help

**Comment by dengliming** [comment]
I'm not sure I fully understand your question.

1. after 2.3.0 we already donate project to Apache and rename soul to shenyu. We are releasing apache version 2.4.0. You can use it for the next 2 weeks.
2. before 2.3.0 you can use pom like the below:


https://mvnrepository.com/search?q=soul
```
<!-- https://mvnrepository.com/artifact/org.dromara/soul-spring-boot-starter-gateway -->
<dependency>
    <groupId>org.dromara</groupId>
    <artifactId>soul-spring-boot-starter-gateway</artifactId>
    <version>2.3.0-RELEASE</version>
</dependency>
```

**Comment by hqgordon** [comment]
> I'm not sure I fully understand your question.
> 
> 1. after 2.3.0 we already donate project to Apache and rename soul to shenyu. We are releasing apache version 2.4.0. You can use it for the next 2 weeks.
> 2. before 2.3.0 you can use pom like the below:
> 
> https://mvnrepository.com/search?q=soul
> 
> ```
> 
> <dependency>
>     <groupId>org.dromara</groupId>
>     <artifactId>soul-spring-boot-starter-gateway</artifactId>
>     <version>2.3.0-RELEASE</version>
> </dependency>
> ```

finally works! thanks!!!!!!!!!!!
