### ISSUE TITLE
'mvn install' command execution failed

### ISSUE THREAD

**Issue by xuziyang** [apache/incubator-shenyu#1841]
## Describe the bug
'mvn install' command execution failed:

## Debug logs
![image](https://user-images.githubusercontent.com/8465969/127726882-0ade1c08-ab5e-4a2f-b412-406a8cc6356c.png)

**Comment by KevinClair** [comment]
Use command `mvn clean install -Dmaven.javadoc.skip=true` and try again.

**Comment by xuziyang** [comment]
Doesn't solve the problem, let me fix it.

**Comment by xuziyang** [comment]
> Use command `mvn clean install -Dmaven.javadoc.skip=true` and try again.



> Use command `mvn clean install -Dmaven.javadoc.skip=true` and try again.

       
Doesn't solve the problem, Let me fix it.

**Comment by KevinClair** [comment]
I try it successfully with command `mvn clean install -Dmaven.javadoc.skip=true`

**Comment by xuziyang** [comment]
The latest code？

**Comment by xuziyang** [comment]
> I try it successfully with command `mvn clean install -Dmaven.javadoc.skip=true`

The latest code？

**Comment by xuziyang** [comment]
> I try it successfully with command `mvn clean install -Dmaven.javadoc.skip=true`

You execute org.apache.shenyu.admin.service.UpstreamCheckServiceTest this test class, is there a problem?
