### ISSUE TITLE
shenyu-admin a part of classes test code

### ISSUE THREAD

**Issue by 0x12FD16B** [apache/incubator-shenyu#1849]
org.apache.shenyu.admin.listener.AbstractDataChangedListener(3%)
org.apache.shenyu.admin.listener.ConfigDataCache(0%)
org.apache.shenyu.admin.listener.zookeeper.HttpServiceDiscovery(7%)
org.apache.shenyu.admin.listener.websocket.WebsocketListener(10%)
org.apache.shenyu.admin.listener.websocket.WebsocketConfigurator(28%)
org.apache.shenyu.admin.exception.ExceptionHandlers(18%)
org.apache.shenyu.admin.config.LdapConfiguration(0%)
org.apache.shenyu.admin.config.DataSyncConfiguration(0%)
org.apache.shenyu.admin.config.ConsulServerConfiguration(0%)
org.apache.shenyu.admin.config.DataBaseConfiguration(0%)

**Comment by 0x12FD16B** [comment]
- [ ] org.apache.shenyu.admin.listener.AbstractDataChangedListener(3%)
- [ ] org.apache.shenyu.admin.listener.ConfigDataCache(0%)
- [ ] org.apache.shenyu.admin.listener.zookeeper.HttpServiceDiscovery(7%)
- [ ] org.apache.shenyu.admin.listener.websocket.WebsocketListener(10%)
- [ ] org.apache.shenyu.admin.listener.websocket.WebsocketConfigurator(28%)
- [ ] org.apache.shenyu.admin.exception.ExceptionHandlers(18%)
- [ ] org.apache.shenyu.admin.config.LdapConfiguration(0%)
- [ ] org.apache.shenyu.admin.config.DataSyncConfiguration(0%)
- [ ] org.apache.shenyu.admin.config.ConsulServerConfiguration(0%)
- [ ] org.apache.shenyu.admin.config.DataBaseConfiguration(0%)

**Comment by Technoboy-** [comment]
Hi,  I can help to work on it, please assign to me.
