### ISSUE TITLE
sync data etcd bug

### ISSUE THREAD

**Issue by future94** [apache/incubator-shenyu#1859]
## Describe the bug
1. After subscribing to `/shenyu/**` the root path, there is no need in the subscription children.
2. After receive etcd PUT event, when update, subscribt children many times. Performance is very low

## Environment

- ShenYu version(s): [master]

**Comment by dengliming** [comment]
Can you help to optimize it?

**Comment by future94** [comment]
I can try to provide a PR version, it may take some time, because I just read shenyu source code not long.
