### ISSUE TITLE
Cannot compile project in Java16

### ISSUE THREAD

**Issue by aiyanbo** [apache/incubator-shenyu#1872]
## Describe the bug

Lombok 1.8.12 doesn't work in Java16. It need upgrade to 1.8.20 

## Environment

- ShenYu version(s): [master]

## Steps to reproduce
1. clone project 
```sh
git clone https://github.com/apache/incubator-shenyu.git
```
2. run the `compile` command
```sh
./mvnw compile
```

## Expected behavior

compile success

## Debug logs

compile (default-compile) on project shenyu-common: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor
<details>
<summary>Click to expand</summary>

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project shenyu-common: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x46c6ff37) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x46c6ff37 -> [Help 1]
```
</details>

**Comment by tydhot** [comment]
we are removing all Lombok in shenyu now

**Comment by aiyanbo** [comment]
https://github.com/apache/incubator-shenyu/issues/1866
