### ISSUE TITLE
which maven repository could I get your jar file from? I could not find any maven  repository that contains your jar.

### ISSUE THREAD

**Issue by iris-xie** [apache/incubator-shenyu#1878]
## Question
which maven repository could I get your jar file from? I could not find any maven  repository that contains your jar. and I can not find your release 2.4.0 on org.dromara, will you still support it?

**Comment by yu199195** [comment]
Hi ,  2.4.0 is apache first version. 

We're going through the apache release process, and you'll find it in the maven repository in the next few days~

**Comment by dengliming** [comment]
https://search.maven.org/search?q=g:org.apache.shenyu
