### ISSUE TITLE
自定义网关服务。jar包依赖无效

### ISSUE THREAD

**Issue by anlaesx** [apache/incubator-shenyu#1898]
你好，我按照官方文档，进行网管的自定义部署方式进行搭建，引入相应的jar包时，发现在中央仓库中找不到对应的jar包，版本方面是2.3.0。希望能够解决下这个问题？

**Comment by hqgordon** [comment]
Could you please provide your POM file or the official document you refer to

**Comment by anlaesx** [comment]
If the SNAPSHOT is 2.4.0-2.4.0-snapshot, the SNAPSHOT is successfully imported
