### ISSUE TITLE
 JWT Usage Issues 

### ISSUE THREAD

**Issue by zhentaowang** [apache/incubator-shenyu#1906]
## Describe the bug

"Cannot edit {" secretkey ":" "" "," filterpath ":" "}, and examples of usage are missing."
## Environment

- ShenYu version(s): 2.4.0

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by midnight2104** [comment]
Hi, I can't get your point, can you provide more infomation?

**Comment by zhentaowang** [comment]
I mean, the JWT usage description（https://shenyu.apache.org/zh/projects/shenyu/jwt-plugin/） in this document is not detailed enough, Can you give me a demo？

**Comment by impactCn** [comment]
> I mean, the JWT usage description（[https://shenyu.apache.org/zh/projects/shenyu/jwt-plugin/）](https://shenyu.apache.org/zh/projects/shenyu/jwt-plugin/%EF%BC%89) in this document is not detailed enough, Can you give me a demo？

There is currently a lack of initialized SQL statements, you can add them directly to db. Or contact me.

**Comment by zhentaowang** [comment]
> > I mean, the JWT usage description（[https://shenyu.apache.org/zh/projects/shenyu/jwt-plugin/）](https://shenyu.apache.org/zh/projects/shenyu/jwt-plugin/%EF%BC%89) in this document is not detailed enough, Can you give me a demo？
> 
> There is currently a lack of initialized SQL statements, you can add them directly to db. Or contact me.

I know what you said. Now I want to modify these two configuration information on the web. I plan to modify index.40aac744.js to realize this function

**Comment by impactCn** [comment]
First, find this table
![image](https://user-images.githubusercontent.com/35489877/128818853-46cc5318-73db-44cd-b488-d4c216914067.png)
seconde
![image](https://user-images.githubusercontent.com/35489877/128818730-414ba414-1ea1-4594-b619-93d1094d8863.png)
Write the parameters directly and open the plugin to determine whether the token is valid.

**Comment by impactCn** [comment]
> > > I mean, the JWT usage description（[https://shenyu.apache.org/zh/projects/shenyu/jwt-plugin/）](https://shenyu.apache.org/zh/projects/shenyu/jwt-plugin/%EF%BC%89) in this document is not detailed enough, Can you give me a demo？
> > 
> > 
> > There is currently a lack of initialized SQL statements, you can add them directly to db. Or contact me.
> 
> I know what you said. Now I want to modify these two configuration information on the web. I plan to modify index.40aac744.js to realize this function

Modifying the js code may be too troublesome.

**Comment by zhentaowang** [comment]
ok，I've given up
