### ISSUE TITLE
the default group of nacos is lowercase

### ISSUE THREAD

**Issue by lltime** [apache/incubator-shenyu#1910]
## Describe the bug

The problem arises in two places, located in：

- NacosServerRegisterRepository
- NacosClientRegisterRepository

![image](https://user-images.githubusercontent.com/41325511/128735570-f3be03a8-8b84-4310-845a-bd5f394c6b0f.png)

![image](https://user-images.githubusercontent.com/41325511/128735769-74c3fced-9c09-41fb-823b-b48b2ae664a3.png)

nacos's group name is case sensitive.  

![image](https://user-images.githubusercontent.com/41325511/128735189-0b08395f-411b-46ce-9629-e53876e1d1da.png)

the default_group of naocs  is defined in  `shenyu-common/src/main/java/org/apache/shenyu/common/constant/NacosPathConstants.java` ， we can use it 

## Environment

- ShenYu version(s): 2.4.0
- Nacos version(s): 2.0.2

## Steps to reproduce

start shenyu-examples-springcloud

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by lw1243925457** [comment]
why can't sync data when default group is lowcase?

It's different on the NacosPathConstants.java than on the NacosServerRegisterRepository, right?
@lltime

**Comment by lltime** [comment]
I confirmed that it had no effect on the data Synchronize. This is not a BUG. 

I take  a mistake.

but, the default_group can  be consistent with the official value of nacos(DEFAULT_GROUP).

**Comment by lltime** [comment]
Yes，It's different on the NacosPathConstants.java than on the NacosServerRegisterRepository。

I confirmed that it had no effect on the data Synchronize. This is not a BUG. 

I take  a mistake.

but, the default_group can  be consistent with the official value of nacos(DEFAULT_GROUP).

**Comment by lw1243925457** [comment]
Shenyu-common/src/main/java/org/apache/shenyu/common/constant/NacosPathConstants.java maybe use by shenyu-sync-data-nacos.

Shenyu-register-nacos was added later, so cant't use it directly. Because group maybe is diff between sync-data-center and register-data-center.

But default_group as constant is a good idea.
