### ISSUE TITLE
Add  shenyu-agent feature to observability

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1916]
Hi Community：

I have a suggestion for using an agent to provide observability on the shenyu gateway and other!

Maybe you need to create a shenyu-agent project. This could be a very interesting feature.

What is the shenyu-agent used for?

shenyu has a very important position as the entrance of traffic. So its observability becomes important.

1.We use the java agent to provide the gateway with tracing, logging, metrics feature!
2. The current monitoring plugin and logging plugin features are too weak provide complete observability！

Why use java agent? 

1. Provides powerful scalability without intruding into the code！
2. Can provide diversity to metrics, tracing... like as zipkin, prometheus !

To Do List

- [ ] Project initialization and architecture. @yu199195 
- [ ] Add metrics feature (prometheus).
- [ ] Add tracing feature (jager, zipkin).
- [ ] Add unit test
- [ ] Add integration test 

Each of the above tasks is very functional and may require many PRs to complete！

**Comment by fengzhenbing** [comment]
I want to join in  `Add tracing feature (jager, zipkin).`

**Comment by JooKS-me** [comment]
I can help to add tracing feature, too.

**Comment by midnight2104** [comment]
Do you need anyone else? I want to join in.

**Comment by zhentaowang** [comment]
if the feature need more people to completed, i'd like to join in add tracing feature

**Comment by midnight2104** [comment]
The shenyu-agent-tracing has been completed in version 2.4.2, logging and metrics are under development.
