### ISSUE TITLE
soul调用报错

### ISSUE THREAD

**Issue by shiyixunsyx** [apache/incubator-shenyu#1919]
问题描述：我们项目用的是soul网关 自定义了一个插件 前端请求过来 先经过我们的插件 我们的插件调用后台一个服务 调用完成后 再匹配 divide 或者dubbo的插件 继续后面的调用 但现在问题是只要请求经过我们的自定义插件后 再去divide插件 WebClientPlugin发起http请求时就报错
报错信息：（之前以为是超时时间问题，调整到30s也是不行，发起请求直接报如下错误）
Did not observe any item or terminal signal within 30000ms in 'peekTerminal' (and no fallback has been configured)
connection prematurely closed during response

**Comment by SaberSola** [comment]
In English please
if return timeout exception , please check you business or gateway to business’s network
or remove your custom plugin then check the webClientPlugin

**Comment by shiyixunsyx** [comment]
> In English please
> if return timeout exception , please check you business or gateway to business’s network
> or remove your custom plugin then check the webClientPlugin

no problem after remove this custom plugin

**Comment by shiyixunsyx** [comment]
Who can solve it? I'm in a hurry

**Comment by wangdazhong001** [comment]
如何解决这个问题的，没有看到相关说明
