### ISSUE TITLE
Add support for docker

### ISSUE THREAD

**Issue by impactCn** [apache/incubator-shenyu#1924]
When I used docker, I used the ip inside the container to forward the url in the request, which caused the request to fail to be sent and timed out. So I want to do docker support for shenyu.

**Comment by tydhot** [comment]
I remember I have let @HessTina-YuI to deploy shenyu  with docker in our test env in June . And it seemed everything is ok.

**Comment by impactCn** [comment]
Please move here to discuss #1925
