### ISSUE TITLE
contextPath should start with / but / is separator of consul and etcd!

### ISSUE THREAD

**Issue by iris-xie** [apache/incubator-shenyu#1926]
contextPath should start with / but / is separator of consul and etcd!
your kv path looks like this:
shenyu
   ├──regsiter
   ├    ├──metadata
   ├    ├     ├──${rpcType}
   ├    ├     ├      ├────${contextPath}
   ├    ├     ├               ├──${ruleName}

if my contextPath is /test

my consul KV path should be shenyu/register/metadata/http//test/xxx  which is of course not supported by consul.will you base64decode it ?

**Comment by midnight2104** [comment]
Hi, does this question still exist? If there is still a problem, please resubmit the issue.
