### ISSUE TITLE
数据字典中新增或修改记录divide中打开规则列表控制台报错

### ISSUE THREAD

**Issue by qinliang373** [apache/incubator-shenyu#1932]
## Describe the bug
1、在数据字典中新增或修改信息
2、打开divide中rulesList click modify，console print error
![image](https://user-images.githubusercontent.com/39186613/129438215-a85d0c20-752c-440d-998d-bfd9a0f9f87a.png)
浏览器版本
chrome版本 78.0.3904.108（正式版本） （32 位）

## Environment

- ShenYu version(s): [e.g. 2.2.1]
拉取最新版本

## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by KevinClair** [comment]
@fengzhenbing Please check this.

**Comment by fengzhenbing** [comment]
> @fengzhenbing Please check this.

I will check it .

**Comment by fengzhenbing** [comment]
> 1、在数据字典中新增或修改信息
> 2、打开divide中rulesList click modify，console print error
@qinliang373  Thanks, we will fix it right now.
