### ISSUE TITLE
DynamicServerListLoadBalancer serverList is null problem(2.4.0)

### ISSUE THREAD

**Issue by zhentaowang** [apache/incubator-shenyu#1946]
## Describe the bug

If other services are not registered in the same namespace of nacos as the gateway shenyu-bootstrap, an error occurs：

Client: demo-aaa instantiated a LoadBalancer: DynamicServerListLoadBalancer:{NFLoadBalancer:name=demo-aaa,current list of Servers=[],Load balancer stats=Zone stats: {},Server stats: []}ServerList:null
## Environment

- ShenYu version(s):2.4.0

## Expected behavior

DynamicServerListLoadBalancer:{NFLoadBalancer:name=XXX,current list of Servers=[XXX:XXX]
## Debug logs

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by yu199195** [comment]
Can your issue follow the template?

**Comment by zhentaowang** [comment]
@yu199195 how to solve the problem ？

**Comment by midnight2104** [comment]
hi @zhentaowang   please see   https://shenyu.apache.org/community/issue-pr/

**Comment by midnight2104** [comment]
Hi, does this question still exist? If there is still a problem, please resubmit the issue.
