### ISSUE TITLE
 Datasource support Oracle and PostgreSQL.

### ISSUE THREAD

**Issue by midnight2104** [apache/incubator-shenyu#1951]
## Task

MySQL and H2 datasource are currently supported in admin. This task is to implement support for Oracle and PostgreSQL.

Task List:

- [x] Datasource support Oracle. @rom1c77 
- [x] #1967 @ShawnJim 

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

**Comment by ChoviWu** [comment]
i want

**Comment by midnight2104** [comment]
cool, you need to reply in here : https://github.com/apache/incubator-shenyu/issues/1951 . that can assgin to you.



At 2021-08-20 15:32:13, "奕仁" ***@***.***> wrote:

i want

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rom1c77** [comment]
assign to me  [Datasource support Oracle]

**Comment by ShawnJim** [comment]
assign to me [Datasource support PostgreSQL]. thanks
