### ISSUE TITLE
Use another method to replace MD5 in http long polling data synchronization.

### ISSUE THREAD

**Issue by midnight2104** [apache/incubator-shenyu#1952]
## Task

In the Http long polling data synchronization, md5 is used to compare the data on the client and admin. This is not a good method, and other methods are recommended.

```java
    protected <T> void updateCache(final ConfigGroupEnum group, final List<T> data) {
        String json = GsonUtils.getInstance().toJson(data);
        ConfigDataCache newVal = new ConfigDataCache(group.name(), json, Md5Utils.md5(json), System.currentTimeMillis());
        ConfigDataCache oldVal = CACHE.put(newVal.getGroup(), newVal);
        log.info("update config cache[{}], old: {}, updated: {}", group, oldVal, newVal);
    }
```

Task List:

- [ ] Use another method to replace MD5. @rom1c77 

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

**Comment by rom1c77** [comment]
assign to me
