### ISSUE TITLE
shenyu-plugin-httpclient conflicts with spring cloud feign httpclinet

### ISSUE THREAD

**Issue by 17661152** [apache/incubator-shenyu#1954]
When I turn on the spring cloud feign httpclient implementation, the HttpClient in the WebClientConfiguration class is empty, and an error is reported at startup

![image](https://user-images.githubusercontent.com/49092294/130212486-58434c9c-94d0-482f-95bc-bd0dff68680b.png)

![image](https://user-images.githubusercontent.com/49092294/130212596-f78a8f76-5354-4253-8411-96fee314106b.png)

Version is 2.4.0

**Comment by yu199195** [comment]
can you show all configuration or application.yaml?

**Comment by 17661152** [comment]
Please check, thank you！

bootstrap.yml

server:
  port: 80
spring:
  profiles:
    active: dev
  application:
    name: shenyu-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      config:
        server-addr: 192.168.100.98:8848
        namespace: 421a641a-f8b6-46b4-b948-4ae1ac8934fd
        file-extension: yaml
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
        heart-beat-interval: 3000
        heart-beat-timeout: 5000

nacos configuration 

spring:
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh
    time-zone: GMT+8
  redis:
    host: 192.168.100.98
    port: 6379
    database: 2
shenyu:
  sync:
    websocket:
      urls: ws://127.0.0.1:9095/websocket
  httpclient: 
    strategy: webClient
  cross:
    enable: true
  accesslog: 
    enable: true
  result: 
    enable: true
  token: 
    enable: true
    ignoreURI: 
    - /iam/authenticate/showCaptcha
    - /iam/authenticate/login
sa-token:
  token-name: Access-Token
  token-style: random-32
  is-read-cookie: false
hystrix:
  threadpool:
    default:
      coreSize: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 32000
ribbon:
  ReadTimeout: 16000
  ConnectTimeout: 16000
feign:
  hystrix: 
    enabled: false
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 16000
        readTimeout: 16000
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS

**Comment by impactCn** [comment]
> Please check, thank you！
> 
> bootstrap.yml
> 
> server:
> port: 80
> spring:
> profiles:
> active: dev
> application:
> name: shenyu-service
> main:
> allow-bean-definition-overriding: true
> cloud:
> nacos:
> config:
> server-addr: 192.168.100.98:8848
> namespace: 421a641a-f8b6-46b4-b948-4ae1ac8934fd
> file-extension: yaml
> discovery:
> server-addr: ${spring.cloud.nacos.config.server-addr}
> namespace: ${spring.cloud.nacos.config.namespace}
> heart-beat-interval: 3000
> heart-beat-timeout: 5000
> 
> nacos configuration
> 
> spring:
> mvc:
> format:
> date: yyyy-MM-dd
> time: HH:mm:ss
> date-time: yyyy-MM-dd HH:mm:ss
> jackson:
> date-format: yyyy-MM-dd HH:mm:ss
> locale: zh
> time-zone: GMT+8
> redis:
> host: 192.168.100.98
> port: 6379
> database: 2
> shenyu:
> sync:
> websocket:
> urls: ws://127.0.0.1:9095/websocket
> httpclient:
> strategy: webClient
> cross:
> enable: true
> accesslog:
> enable: true
> result:
> enable: true
> token:
> enable: true
> ignoreURI:
> - /iam/authenticate/showCaptcha
> - /iam/authenticate/login
> sa-token:
> token-name: Access-Token
> token-style: random-32
> is-read-cookie: false
> hystrix:
> threadpool:
> default:
> coreSize: 500
> command:
> default:
> execution:
> isolation:
> thread:
> timeoutInMilliseconds: 32000
> ribbon:
> ReadTimeout: 16000
> ConnectTimeout: 16000
> feign:
> hystrix:
> enabled: false
> httpclient:
> enabled: true
> client:
> config:
> default:
> connectTimeout: 16000
> readTimeout: 16000
> management:
> endpoints:
> web:
> exposure:
> include: "*"
> endpoint:
> health:
> show-details: ALWAYS


What version of feign is currently in use.

**Comment by 17661152** [comment]
Hello, the Spring Cloud version currently in use is Hoxton.SR12. Spring Cloud Alibaba is 2.2.6.RELEASE. spring-cloud-starter-openfeign is 2.2.9.RELEASE.

**Comment by impactCn** [comment]
> Hello, the Spring Cloud version currently in use is Hoxton.SR12. Spring Cloud Alibaba is 2.2.6.RELEASE. spring-cloud-starter-openfeign is 2.2.9.RELEASE.

<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <version>2.2.3.RELEASE</version>
        </dependency>

Try this dependency.

**Comment by impactCn** [comment]
> Hello, the Spring Cloud version currently in use is Hoxton.SR12. Spring Cloud Alibaba is 2.2.6.RELEASE. spring-cloud-starter-openfeign is 2.2.9.RELEASE.

```

<dependency>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-starter-openfeign</artifactId>
          <version>2.2.3.RELEASE</version>
 </dependency>
```
Try this dependency.

**Comment by 17661152** [comment]
Hello, I changed httpclient to okhttp and it was no problem
