### ISSUE TITLE
How to record the log information to the database

### ISSUE THREAD

**Issue by janusdo** [apache/incubator-shenyu#1956]
I want to record the api request information into the database, including success and failure records. Is there a good solution?

**Comment by dengliming** [comment]
Try refer to https://github.com/apache/incubator-shenyu/tree/master/shenyu-plugin/shenyu-plugin-logging. and replace log with database.

**Comment by janusdo** [comment]
The Logging plugin cannot record the ShenyuResultWrap error message，Are there any other solutions to this question?
thank you!
