### ISSUE TITLE
Refactor integration test

### ISSUE THREAD

**Issue by JooKS-me** [apache/incubator-shenyu#1979]
Hi, community~

When we are doing integration testing, if we need to configure the relevant information of the gateway, we don't need to use the sql script now. We can just use `HttpHelper` in the Java code to request the relevant interface of the shenyu gateway.

Now, we need to replace the sql script with java code. You can refer to #1975 . The following is about the task of refactoring the integration test.

#### shenyu-integrated-test-http:

- [x] rate-limiter plugin @HelKim
- [x] sign plugin @HelKim
- [x] redirect plugin @yu199195 
- [x] jwt plugin @JooKS-me 
- [x] context-path plugin @JooKS-me 

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

If you would like to participate, Please leave a message under this issue.

**Comment by JooKS-me** [comment]
@HelKim hi,  are you still doing this? Or, do you need my help?

**Comment by yu199195** [comment]
@HelKim  hi,  do you need my help?

**Comment by HelKim** [comment]
@yu199195 @JooKS-me hi, thanks for help. no time to finish it recently, sorry.

**Comment by yu199195** [comment]
@HelKim  It doesn't matter ， @JooKS-me   Can you finish in his place?

**Comment by JooKS-me** [comment]
> @HelKim  It doesn't matter ， @JooKS-me   Can you finish in his place?

Yep, I can try to finish it.
