### ISSUE TITLE
[Integration-Test]  Add plugin test for Http

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1980]
Hi community

Plugin integration testing is very important. But now there is still a part missing, can you do me a small favor.

So I have listed the following tasks：

- [ ] add cryptor plugin  @4zd 
- [ ] add hystrix plugin  @rockpig 
- [ ] add modify-response plugin @lw1243925457 
- [x] add param-mapping plugin
- [x] add request plugin @rom1c77 
- [ ] add resilience4j plugin @rockpig 
- [x] add sentinel plugin @rom1c77 

Don't worry, they are not very difficult, you can refer to：

[waf plugin](https://github.com/apache/incubator-shenyu/blob/master/shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/WafPluginTest.java)

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

If you would like to participate, Please leave a message under this issue.

**Comment by JooKS-me** [comment]
@yu199195 Hi, I have done `param-mapping plugin` test in #1966 .

**Comment by 4zd** [comment]
> @4zd @rockpig Hi, how is the progress? Or do you need my help?

Sorry for missing this message, I did get stuck on something and try to fix it by myself. I find the cryptor plugin integration test has been finished and commited by Kunshuai Zhu on last weekends. Thanks for the favor, and I applogize for the delay from me.

**Comment by JooKS-me** [comment]
> > @4zd @rockpig Hi, how is the progress? Or do you need my help?
> 
> Sorry for missing this message, I did get stuck on something and try to fix it by myself. I find the cryptor plugin integration test has been finished and committed by you on last weekends. Thanks for the favor, and I applogize for the delay from me.

That's alright~
