### ISSUE TITLE
[Integration-Test] Init dubbo integration test

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1981]
Hi community

This task is needed to test support for the dubbo protocol.

you can add project in apache shenyu, The structure is as follows：

-----shenyu-integration-test
-----------shenyu-integration-test-alibaba-dubbo
-----------shenyu-integration-test-apache-dubbo

Don't worry, they are not very difficult, you can refer to：

1. [shenyu-integrated-test-http](https://github.com/apache/incubator-shenyu/tree/master/shenyu-integrated-test/shenyu-integrated-test-http)
2.  also you requires some knowledge of docker

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

If you would like to participate, Please leave a message under this issue.

**Comment by strawberry-crisis** [comment]
OK thx

**Comment by strawberry-crisis** [comment]
I have some trouble doing this task,

1. In "shenyu-integration-test-alibaba-dubbo", I can't override `<dubbo:registry address="zookeeper://localhost:2181"/>` by docker compose file in shenyu-integration-test-alibaba-dubbo with config: 
```
environment:
      - dubbo.registry.address=zookeeper://shenyu-zk:2181
```
2. In "shenyu-integration-test-apache-dubbo", all docker images are up but test failed:
```
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.shenyu.intergratedtest.alibaba.dubbo.ApacheDubboPluginTest
07:45:21.348 [main] INFO org.apache.shenyu.integratedtest.common.helper.HttpHelper - getFromGateway(/dubbo/findById?id=1) resp({"code":-107,"message":"Can not find selector, please check your configuration!","data":null})
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.617 s <<< FAILURE! - in org.apache.shenyu.intergratedtest.alibaba.dubbo.ApacheDubboPluginTest
Error:  org.apache.shenyu.intergratedtest.alibaba.dubbo.ApacheDubboPluginTest.testFindById  Time elapsed: 1.496 s  <<< FAILURE!
java.lang.AssertionError: expected:<hello world shenyu Apache, findById> but was:<null>
	at org.apache.shenyu.intergratedtest.alibaba.dubbo.ApacheDubboPluginTest.testFindById(ApacheDubboPluginTest.java:34)
```
