### ISSUE TITLE
[Integration-Test] Init sofa integration test

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#1982]
Hi community

This task is needed to test support for the sofa-rpc protocol.

you can add project in apache shenyu, The structure is as follows：

-----shenyu-integration-test
-----------shenyu-integration-test-sofa

Don't worry, they are not very difficult, you can refer to：

1. [shenyu-integrated-test-http](https://github.com/apache/incubator-shenyu/tree/master/shenyu-integrated-test/shenyu-integrated-test-http)
2.  also you requires some knowledge of docker

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

If you would like to participate, Please leave a message under this issue.

**Comment by yu199195** [comment]
@ChDoBigThings 
Hi， How's your mission going?

**Comment by JooKS-me** [comment]
@ChDoBigThings Hi, do you still doing this issue? If not, I can help to add soft integration test.

**Comment by ChDoBigThings** [comment]
> @ChDoBigThings Hi, do you still doing this issue? If not, I can help to add soft integration test.

Hi, Please help add soft integration test.

**Comment by JooKS-me** [comment]
> > @ChDoBigThings Hi, do you still doing this issue? If not, I can help to add soft integration test.
> 
> Hi, Please help add soft integration test.

ok, I will try to finish it.

**Comment by midnight2104** [comment]
done
