### ISSUE TITLE
Why are many contents of  SharingSphere AND Dromara like shenyu so much？

### ISSUE THREAD

**Issue by thicv** [apache/incubator-shenyu#2004]
## Question

When I looked at Shen Yu’s document today, I felt that Shen Yu’s coding guidelines are really good. Obviously it is not an excerpt of the document, nor is it a specification already organized by other companies. This seems to be a code carefully organized by a code maker over the years, and I am deeply moved by reading it. However, when I searched, I found that two organizations, Shardingsphere and Dromara, shamelessly copied our Shenyu code specifications, which is outrageous. I hope Shen Yu can manage it well. teach them a lession .

**Comment by yu199195** [comment]
@thicv 
Hi，Thank you for your attention.   

Im is ShardingSphere committer，
ShardingSphere has more useful code specifications， 
So we borrowed some of it, but with a little difference。

**Comment by thicv** [comment]
sugoi !! you are one of the shardingsphere commiter !
そうですね
so , soso,  is that means , the man who create shardingsphere code guideline is the God of coder ? this is my most useful found today , I hope I can talk to that guy . do you have any of his contect method ?
and also hope shenyu works well， be better and better.

BTW, shenyu should declare that used the mojority of shardingsphere code guide line , or other poople will think mistake

**Comment by tuohai666** [comment]
I'll add the reference of the ShardingSphere code conduct for this doc.

**Comment by thicv** [comment]
> @thicv
> Hi，Thank you for your attention.
> 
> Im is ShardingSphere committer，
> ShardingSphere has more useful code specifications，
> So we borrowed some of it, but with a little difference。

hi , comrade do you have that man's contact way ? I want to discuss with him . the god of coder in shardingsphere

**Comment by thicv** [comment]
> I'll add the reference of the ShardingSphere code conduct for this doc.

comrade, you should add the info first and then close this issue, that's the gorgeous opensource way
