### ISSUE TITLE
Modify the return value of the'skip' method interface of'ShenyuPlugin' to boolean

### ISSUE THREAD

**Issue by zhaiweij** [apache/incubator-shenyu#2008]
## Task

Modify the return value of the'skip' method interface of'ShenyuPlugin' to boolean
Task List:

- [ ] Modify the return value of the'skip' method interface of'ShenyuPlugin' to boolean
- [ ] Modify the return value of the reference'skip' method to boolean

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

**Comment by KevinClair** [comment]
What's task No.2?

**Comment by zhaiweij** [comment]
> What's task No.2?

One is to modify the "skip" method, and the other is to modify the reference to the "skip" method
