### ISSUE TITLE
nacos data synchronization will generate large amounts of historical data 

### ISSUE THREAD

**Issue by MarsOu1995** [apache/incubator-shenyu#2029]
#### Is your feature request related to a problem? Please describe

When using nacos as synchronization, it will cause the nacos database "his_config_info" table records to surge.
 Because only one piece of data is synchronized each time,  the nacos will generate a history record.
In my test environment, 83G of historical data was generated in one month. 
#### Describe the solution you'd like

Can sync operations become batches? 

#### Additional context

-rw-r----- 1 mysql mysql 83G Sep  2 17:13 his_config_info.ibd  ，802153

**Comment by yu199195** [comment]
nacos as  data synchronization ， I do not recommend, whether he is full or incremental?

**Comment by MarsOu1995** [comment]
> nacos as data synchronization ， I do not recommend, whether he is full or incremental?

For example: "rule" configuration, the json content has 2M, each time one rule is updated, the all json content will be saved to the history.So it will cause a lot of waste of database space.

**Comment by lw1243925457** [comment]
nacos data synchronization，it should update when rule/select/plugin/metadata/auth update. 
Do you have a better idea for the large batch and historical data?
all nacos synchronization code is here：org.apache.shenyu.sync.data.nacos

**Comment by MarsOu1995** [comment]
> nacos data synchronization，it should update when rule/select/plugin/metadata/auth update.
> Do you have a better idea for the large batch and historical data?
> all nacos synchronization code is here：org.apache.shenyu.sync.data.nacos

Currently, the temporary scheme I use:
Client: Because the data is only synchronized at startup, it uses counters and delays to wait for all data to be prepared and submitted at one time.
Server: Delay processing, but this is not appropriate, it is just a temporary solution.
