### ISSUE TITLE
TimeoutException: Did not observe any item or terminal signal within 3000ms in 'peekTerminal' (and no fallback has been configured)

### ISSUE THREAD

**Issue by wangdazhong001** [apache/incubator-shenyu#2034]
### Question

Version: soul 2.3.0
Frequent requests can cause this problem. Check that the underlying service is complete. This frequently refers to the occurrence of manual clicks.
   Don't know how to solve this problem at the moment?
<img width="1176" alt="090CFE6F-241E-4484-9D4D-7500B0398614" src="https://user-images.githubusercontent.com/49627839/132208547-67cdf859-f800-4422-a5ff-2ccc4ea4d853.png">

**Comment by wangdazhong001** [comment]
#1197

**Comment by yu199195** [comment]
can  you used apache shenyu 2.4.0？

**Comment by wangdazhong001** [comment]
Let me try

**Comment by yu199195** [comment]
@wangdazhong001 

1.  you can modify this : HttpClientPluginConfiguration.java , like master.
2.  and then if  timeout , you can config HttpClientProperties.
```
shenyu:
#  httpclient:
#    strategy: webClient
#    connectTimeout: 45000
#    readTimeout: 3000
#    writeTimeout: 3000
#    wiretap: false
#    pool:
#      type: ELASTIC
#      name: proxy
#      maxConnections: 16
#      acquireTimeout: 45000
  

```

**Comment by wangdazhong001** [comment]
> acquireTimeout



> @wangdazhong001
> 
> 1. you can modify this : HttpClientPluginConfiguration.java , like master.
> 2. and then if  timeout , you can config HttpClientProperties.
> 
> ```
> shenyu:
> #  httpclient:
> #    strategy: webClient
> #    connectTimeout: 45000
> #    readTimeout: 3000
> #    writeTimeout: 3000
> #    wiretap: false
> #    pool:
> #      type: ELASTIC
> #      name: proxy
> #      maxConnections: 16
> #      acquireTimeout: 45000
>   
> ```

**Comment by wangdazhong001** [comment]
> > acquireTimeout
> 
> > @wangdazhong001
> > 
> > 1. you can modify this : HttpClientPluginConfiguration.java , like master.
> > 2. and then if  timeout , you can config HttpClientProperties.
> > 
> > ```
> > shenyu:
> > #  httpclient:
> > #    strategy: webClient
> > #    connectTimeout: 45000
> > #    readTimeout: 3000
> > #    writeTimeout: 3000
> > #    wiretap: false
> > #    pool:
> > #      type: ELASTIC
> > #      name: proxy
> > #      maxConnections: 16
> > #      acquireTimeout: 45000
> >   
> > ```

At present, only shenyu-bootstrap has been upgraded, and it is found to be normal. It is still under continuous observation. If everything goes well, I will inform the result.

**Comment by wangdazhong001** [comment]
> > > acquireTimeout
> > 
> > 
> > > @wangdazhong001
> > > 
> > > 1. you can modify this : HttpClientPluginConfiguration.java , like master.
> > > 2. and then if  timeout , you can config HttpClientProperties.
> > > 
> > > ```
> > > shenyu:
> > > #  httpclient:
> > > #    strategy: webClient
> > > #    connectTimeout: 45000
> > > #    readTimeout: 3000
> > > #    writeTimeout: 3000
> > > #    wiretap: false
> > > #    pool:
> > > #      type: ELASTIC
> > > #      name: proxy
> > > #      maxConnections: 16
> > > #      acquireTimeout: 45000
> > >   
> > > ```
> 
> At present, only shenyu-bootstrap has been upgraded, and it is found to be normal. It is still under continuous observation. If everything goes well, I will inform the result.

After several days of observation, it was basically stable, but there were 2 errors. I don’t know if it has something to do with the server.

**Comment by wangdazhong001** [comment]
It has been stable, but occasionally there will be another time, do not rule out server problems, temporarily shut down
