### ISSUE TITLE
[Question] <add *.http file to support faster experience in examples>

### ISSUE THREAD

**Issue by li-keguo** [apache/incubator-shenyu#2044]
### Question

I want to add the *.http file to the examples project to support faster experience in examples

eg:
in the shengyu-examples-grpc project
Create the file grpc-test-api.http under src/main/http/
add context to file

`
### shengyu getway proxy echo
POST http://localhost:9195/grpc/echo
Accept: application/json
Content-Type: application/json

{
  "data": [
    {
      "message": "hello grpc"
    }
  ]
}
`
if used IDEA IDE, you can click is run

**Comment by yu199195** [comment]
you can fix it

**Comment by li-keguo** [comment]
yes
