### ISSUE TITLE
[Question] <Resilience4JPlugin's conf limitForPeriod invalid>

### ISSUE THREAD

**Issue by rockpig** [apache/incubator-shenyu#2055]
### Question

I test resilience4J plugin, and set limitForPeriod 2 for RuleData, but it was changed 50 in 
 `org.apache.shenyu.common.dto.convert.Resilience4JHandle#checkData() : 393` : 

> resilience4JHandle.setLimitForPeriod(Math.max(resilience4JHandle.getLimitForPeriod(), Constants.LIMIT_FOR_PERIOD));

If I went to limit 2 request per second, it will failed.

I think it should be fix to:

> resilience4JHandle.setLimitForPeriod(Math.min(resilience4JHandle.getLimitForPeriod(), Constants.LIMIT_FOR_PERIOD));

So It is a bug or the way I used has problem?

**Comment by SaberSola** [comment]
Hi, Perhaps this method named 'checkData' is not reasonable,you are right,can you provide a pr fix this bug or remove the 'checkData' method directly

**Comment by rockpig** [comment]
Of course, I will fix it.
