### ISSUE TITLE
[Volunteer]  Init motan integration test

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2060]
### Volunteer help

Hi community

This task is needed to test support for the sofa-rpc protocol.

you can add project in apache shenyu, The structure is as follows：

-----shenyu-integration-test
-----------shenyu-integration-test-motan

Don't worry, they are not very difficult, you can refer to：

shenyu-integrated-test-http
also you requires some knowledge of docker
Please read the Contribution Guideline before submitting the PR

If you would like to participate, Please leave a message under this issue.

**Comment by prospect167** [comment]
pls assign to me
