### ISSUE TITLE
[Question] apache/shenyu-bootstrap docker image not working

### ISSUE THREAD

**Issue by willfenglover** [apache/incubator-shenyu#2073]
### Question

I ran command as follows with my demo env：
```
docker network create shenyu
docker pull apache/shenyu-bootstrap
docker run -d -p 9195:9195 --net shenyu apache/shenyu-bootstrap
```
and I encountered the following error
**_Starting the ShenYu-Bootstrap ...
Please check the log files: /opt/shenyu-bootstrap/logs
tail: can't open '/opt/shenyu-bootstrap/logs/shenyu-bootstrap.out': No such file or directory
tail: no files_**

what should I do，Thanks.

**Comment by yu199195** [comment]
Asynchronous reasons, the file has not been created yet, you can create the file first （'/opt/shenyu-bootstrap/logs/shenyu-bootstrap.out'）, this problem has been fixed~

**Comment by midnight2104** [comment]
Hi, does this question still exist? If there is still a problem, please resubmit the issue.
