### ISSUE TITLE
[Volunteer] Add unit test for ShenyuPluginLoader

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2078]
### Volunteer help

Hi community

Volunteer help to add unit test for `org.apache.shenyu.web.loader.ShenyuPluginLoader`

**Comment by tonytanCoder** [comment]
认领

**Comment by dbaxyx** [comment]
i want

**Comment by yu199195** [comment]
@tonytanCoder What is the current progress and do you need help?

**Comment by midnight2104** [comment]
done
