### ISSUE TITLE
[Volunteer] Add unit test for ShenyuPluginPathBuilder

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2079]
### Volunteer help

Hi community

Volunteer help to add unit test for `org.apache.shenyu.web.loader.ShenyuPluginPathBuilder`

**Comment by hezhaoming** [comment]
I can up

**Comment by hezhaoming** [comment]
Thanks♪(･ω･)ﾉ

**Comment by yu199195** [comment]
@hezhaoming What is the current progress and do you need help?

**Comment by hezhaoming** [comment]
I doing
