### ISSUE TITLE
[Volunteer] Add unit test for PluginController

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2080]
### Volunteer help

Hi community

Volunteer help to add unit test for `org.apache.shenyu.web.controller.PluginController`

**Comment by hezhaoming** [comment]
I want do it

**Comment by dbaxyx** [comment]
i want do it

**Comment by yu199195** [comment]
@dbaxyx  hezhaoming accept, thanks ,Look at the other~

**Comment by yu199195** [comment]
@dbaxyx  What is the current progress and do you need help?

**Comment by hezhaoming** [comment]
3Q, I doing ^_^

**Comment by songyuequan** [comment]
@hezhaoming   dbaxyx What is the current progress and do you need help?

**Comment by yangtianrui95** [comment]
Is there any progress? Let me try it plz @songyuequan @yu199195

**Comment by songyuequan** [comment]
Hi~ I have assigned it to you in #2420 . and you can just try. @yangtianrui95

**Comment by midnight2104** [comment]
done
