### ISSUE TITLE
[Question] best practice 

### ISSUE THREAD

**Issue by danielchenxs** [apache/incubator-shenyu#2095]
### Question

Can you provide best practices documentation, such as JVM (garbage collector G1 or CMS and configuration details), Linux kernel parameters, etc.    
like [rocketmq best practice](https://github.com/apache/rocketmq/blob/master/docs/cn/best_practice.md)

**Comment by yu199195** [comment]
No， Need to be configured according to the application scenario of your own service~

**Comment by midnight2104** [comment]
Hi, does this question still exist? If there is still a problem, please resubmit the issue.
