### ISSUE TITLE
Did not observe any item or terminal signal within 3000ms in 'peekTerminal' (and no fallback has been configured)

### ISSUE THREAD

**Issue by uare987612** [apache/incubator-shenyu#2096]
### Question

Version: soul 2.2.1
If the forwarding interface does not return data for more than 3s the gateway times out.
Modify the HttpClientPluginConfiguration.java as master still does not work.
How can I solve this problem?
![000551](https://user-images.githubusercontent.com/45450332/133824648-d8f1ab2f-bf6c-437e-92a1-0a645ed98102.png)
![003256](https://user-images.githubusercontent.com/45450332/133824666-31327e75-347b-447a-a1dc-2bfdaca8004f.png)
![8003347](https://user-images.githubusercontent.com/45450332/133825105-609c207d-e305-4e7e-a998-f67056ab9d49.png)

**Comment by yu199195** [comment]
you can see this ： https://github.com/apache/incubator-shenyu/issues/2034

**Comment by uare987612** [comment]
I've already done that but it still doesn't work
![33](https://user-images.githubusercontent.com/45450332/133873969-a1da3cfc-5a8d-49f5-a95a-208a9f9c83cf.png)

**Comment by yu199195** [comment]
can you  used 2.4.0？

**Comment by uare987612** [comment]
modify this param
![222](https://user-images.githubusercontent.com/45450332/134354562-88eb8f73-7248-4e0d-b227-8202faa58fbe.PNG)
