### ISSUE TITLE
[BUG] org.apache.shenyu.loadbalancer.cache.UpstreamCheckTaskTest.testRun test fail

### ISSUE THREAD

**Issue by dengliming** [apache/incubator-shenyu#2128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

org.apache.shenyu.loadbalancer.cache.UpstreamCheckTaskTest.testRun test fail sometimes.

see https://github.com/apache/incubator-shenyu/runs/3706238594

### Expected Behavior

No Exception

### Environment

```markdown
ShenYu version(s):
```

**Comment by prospect167** [comment]
pls assign to me
