### ISSUE TITLE
[Volunteer] Add unit test for ConsulClientRegisterRepository

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2136]
### Volunteer help

Hi community

Volunteer help to add unit test for `org.apache.shenyu.register.client.consul.ConsulClientRegisterRepository`

**Comment by dbaxyx** [comment]
I want do it

**Comment by yu199195** [comment]
@dbaxyx  What is the current progress?

**Comment by midnight2104** [comment]
hello  ,  @dbaxyx  , What is the current progress?

**Comment by AhahaGe** [comment]
I will finish this

**Comment by songyuequan** [comment]
> I will finish this, please assign to me

Hi~,I think there is no progress for a long time.
In order to improve the UT Coverage.
I have assign to you in #2420
thank you @AhahaGe

And. you can take some other tasks when you have enough time. @dbaxyx

**Comment by AhahaGe** [comment]
> 

Ok, I am doing this, and reading code to understand the logic, and start write unit test.

**Comment by AhahaGe** [comment]
ConsulClientRegisterRepository is blocking, when I start example using register type consul, it shows below error.
![image](https://user-images.githubusercontent.com/6198217/143396086-cc3484cb-dc10-49d4-8efa-bd38b5b81855.png)
