### ISSUE TITLE
[Volunteer] Add unit test for ConsulServerRegisterRepository

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2137]
### Volunteer help

Hi community

Volunteer help to add unit test for  `org.apache.shenyu.register.server.consul.ConsulServerRegisterRepository`

**Comment by wenjiyang-sh** [comment]
assigned to me

**Comment by wangjianwei123** [comment]
assigned to me

**Comment by midnight2104** [comment]
done
