### ISSUE TITLE
[Volunteer] Add unit test for ShenyuClientRegisterDubboServiceImpl

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2138]
### Volunteer help

Hi community

Volunteer help to add unit test for `org.apache.shenyu.admin.service.register.ShenyuClientRegisterDubboServiceImpl`

you can create `org.apache.shenyu.admin.service.register/ShenyuClientRegisterDubboServiceImplTest` in  `/test/java` package

**Comment by qurenneng** [comment]
Give it to me

**Comment by sunrui849** [comment]
i do
