### ISSUE TITLE
[Volunteer] Add unit test for ShenyuClientRegisterMotanServiceImpl

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2140]
### Volunteer help

Hi community

Volunteer help to add unit test for `org.apache.shenyu.admin.service.register.ShenyuClientRegisterMotanServiceImpl`

you can create `org.apache.shenyu.admin.service.register/ShenyuClientRegisterMotanServiceImplTest` in  `/test/java` package

**Comment by BlankKelly** [comment]
I do.

**Comment by yu199195** [comment]
@BlankKelly What is the current progress?

**Comment by yu199195** [comment]
@cuirui1994  ok

**Comment by cuirui1994** [comment]
#2238 done, just have a check

**Comment by midnight2104** [comment]
done
