### ISSUE TITLE
[Volunteer]  Add unit test for ShenyuClientRegisterSofaServiceImpl

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2141]
### Volunteer help

Hi community

Volunteer help to add unit test for `org.apache.shenyu.admin.service.register.ShenyuClientRegisterSofaServiceImpl`

you can create `org.apache.shenyu.admin.service.register/ShenyuClientRegisterSofaServiceImplTest` in  `/test/java` package

**Comment by BlankKelly** [comment]
I do.
