### ISSUE TITLE
[Volunteer] Add unit test for ShenyuClientRegisterSpringMVCServiceImpl

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2143]
### Volunteer help

Hi community

Volunteer help to add unit test for `org.apache.shenyu.admin.service.register.ShenyuClientRegisterSpringMVCServiceImpl`

you can create `org.apache.shenyu.admin.service.register/ShenyuClientRegisterSpringMVCServiceImplTest` in  `/test/java` package

**Comment by qurenneng** [comment]
Give it to me

**Comment by yu199195** [comment]
@qurenneng  What is the current progress?

**Comment by qurenneng** [comment]
Didn't the code fit in

**Comment by qurenneng** [comment]
It's in
