### ISSUE TITLE
[Volunteer] Add unit test for ShenyuClientRegisterTarsServiceImpl

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2144]
### Volunteer help

Hi community

Volunteer help to add unit test for `org.apache.shenyu.admin.service.register.ShenyuClientRegisterTarsServiceImpl`

you can create `org.apache.shenyu.admin.service.register/ShenyuClientRegisterTarsServiceImplTest` in  `/test/java` package

**Comment by qinxu2015** [comment]
I want do it  ，assigned to me

**Comment by yu199195** [comment]
@qinxu2015 Hi ， What is the current progress?

**Comment by midnight2104** [comment]
Hi, @qinxu2015 , What is the current progress?

**Comment by qinxu2015** [comment]
Hello,Recently, there are many tasks, and it will take a few days to connect them
