### ISSUE TITLE
try resolve two “ / ” on contextPath

### ISSUE THREAD

**Issue by MiniSC** [apache/incubator-shenyu#2145]
### Question

about this question
i found two / will lead to Npe is because of [ZookeeperServerRegisterRepository#subscribeMetaData]   subscribe 
a ChildChanges Listener (named  xxlistner)
then [ZookeeperClientRegisterRepository#registerMetadata]  trigger   zkClient.createPersistent(metaDataPath, true); will registe /v1/v2 node ,but not set data in first zk node create 
then the xxlistner get  new childChanges (v1 )  then watcherMetadata  find childNode  v2, but now v2 has no data , do                 publishMetadata(zkClient.readData(realPath).toString())  ,zkClient.readData(realPath) get null ,then lead to npe

my resolve way  
ZookeeperServerRegisterRepository#subscribeMetaData  
before node create  add zkClient.getEventLock().lock();
and after data set  ,unlock this eventLock

does it work?  want your comment

**Comment by yu199195** [comment]
What are the scenarios where there are multiple /?

**Comment by MiniSC** [comment]
we want use /gw/${applicationName}  as  contextPath , then can do something in filter for different app

**Comment by yu199195** [comment]
donot used  multiple / as context path

**Comment by MiniSC** [comment]
the reason is ? 
/gw is for nginx  let request forwarding to gateway,and use the secondary directory to diff app,  How can I achieve this

**Comment by yu199195** [comment]
> /gw is for nginx let request forwarding to gateway,and use the secondary directory to diff app, How can I achieve this

/gw ,you can config in nginx upstream , not config in shenyu

**Comment by MiniSC** [comment]
ok ,i know it , but  am I discovering the cause of this problem? and will this solution solve the problem?

**Comment by yu199195** [comment]
This is not a solution, for zk `/` is a node, maybe there will be many `/`

**Comment by MiniSC** [comment]
ok, thanks
