### ISSUE TITLE
[BUG] Rule matching does not take rewritten uri into account

### ISSUE THREAD

**Issue by ichenhe** [apache/incubator-shenyu#2162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When matching plugin rules, the original uri is used instead of the rewritten uri.

### Expected Behavior

The rewritten uri should be used. Otherwise, there is no point in rewrite plugin.

### Steps To Reproduce

1. Add a selector to SpringClould plugin: match uri `/**`.
2. Add a rule to SpringClould plugin: match uri `/users/**`
3. Add a selector to Rewrite plugin: match uri `/v1/**`.
4. Add a rule to Rewrite plugin: match uri `/v1/hello`, regex: `.+`, replace: `/users/hello`
5. Get `/v1/hello`  --> Rule not found!

### Environment

```markdown
ShenYu version(s): 2.4.0
```

### Debug logs

```
2021-09-28 15:23:05.722  INFO AbstractShenyuPlugin   : rewrite selector success match , selector name :/v1
2021-09-28 15:23:09.939  INFO AbstractShenyuPlugin   : rewrite rule success match , rule name :/v1/hello
2021-09-28 15:23:10.897  INFO AbstractShenyuPlugin   : springCloud selector success match , selector name :/
2021-09-28 15:39:40.797 ERROR WebFluxResultUtils     : can not match rule data: springCloud
```

### Anything else?

I'm sure the rewrite plugin was the first to execute, and the execution was successful.

The cause seems to be [here](https://github.com/apache/incubator-shenyu/blob/c69d8d84a0c64eb5115249d6da8edfc37837a0c8/shenyu-plugin/shenyu-plugin-base/src/main/java/org/apache/shenyu/plugin/base/condition/data/URIParameterData.java#L31). It gets the path directly, instead of checking the rewrite uri first.

![](https://user-images.githubusercontent.com/10266066/135045059-6e8b7c77-eca4-4d20-bbd1-389482d0d997.png)

**Comment by yu199195** [comment]
> /users/hello 

have some error？

**Comment by ichenhe** [comment]
@yu199195 noop. The backend did not receive the request at all. Shenyu also did not trigger access (I confirmed this through debug.).

There's another evidence:

1. Add a selector to Rewrite plugin: uri == `/users/hello/123`.
2. Add a rule to Rewrite plugin: uri == `/users/hello/123`, regex: `.+`, replace: `/users/hello`
3. Get `/users/hello/123` --> OK

This means that url rewriting is invalid for matching, valid only for [the actual processing of the plugin](https://github.com/apache/incubator-shenyu/blob/c69d8d84a0c64eb5115249d6da8edfc37837a0c8/shenyu-plugin/shenyu-plugin-springcloud/src/main/java/org/apache/shenyu/plugin/springcloud/SpringCloudPlugin.java#L136).

> At the same time, uri rewriting is not transparent to plugins, all plugins need to handle this situation manually. I don't think that's a good idea.

**Comment by yu199195** [comment]
```java
String url = uri.toASCIIString();
final String rewriteURI = (String) exchange.getAttributes().get(Constants.REWRITE_URI);
if (StringUtils.isNotBlank(rewriteURI)) {
        url = url.replace(uri.getPath(), rewriteURI);
}
```

The original request path not been replaced?

**Comment by ichenhe** [comment]
@yu199195 

This function is called in the executor of the plugin -- **after being matched by the rules**.

But this plugin will not be executed, because rule matching uses the original uri.

**Comment by yu199195** [comment]
> this plugin will not be executed, because rule matching uses the original uri.

yes , rule matching uses the original uri.   rewrite plugin  only responsible for replace uri, other plugins are not affected when using uri matcher~

**Comment by ichenhe** [comment]
> other plugins are not affected when using uri matcher.

Then the role of rewriting plugins is very small. Is this a intented behavior? So I have to use Redirect plugin? @yu199195

**Comment by ichenhe** [comment]
Anyway, thanks for the explanation. I have tried Redirect plugin, but encountered another problem. Others have the same report #2028 , but no further information :(
