### ISSUE TITLE
Use spring boot 2.3.1, can not register successfully

### ISSUE THREAD

**Issue by monedory** [apache/incubator-shenyu#2175]
### Question

when i change spring boot 2.2.2, can register successfully

**Comment by yu199195** [comment]
can you provide details info？ and why not this？

**Comment by CoimLuo** [comment]
![image](https://user-images.githubusercontent.com/7017332/136502861-8f2c9e19-6998-450f-82a9-e48f223fdf78.png)
can not get the ServiceBean,but can access the dubbo interface successfully

**Comment by midnight2104** [comment]
Hi, does this question still exist? If there is still a problem, please resubmit the issue.
