### ISSUE TITLE
[BUG] serviceBean.getTimeout() is null

### ISSUE THREAD

**Issue by monedory** [apache/incubator-shenyu#2197]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

I had config the dubbo.provider.timeout,and it allready was effective in dubbo admin. but when ShenyuDubboClient is registered,serviceBean.getTimeout() is null
![image](https://user-images.githubusercontent.com/7017332/136511724-da1735a9-d135-4e5d-9fba-3137bd46c1c9.png)

### Expected Behavior

rpcExt use dubbo.provider.timeout config

### Environment

```markdown
ShenYu version(s):
```

**Comment by yu199195** [comment]
maybe config  timeout in interface， not dubbo.provider~
