### ISSUE TITLE
[Question] <title>  zook config

### ISSUE THREAD

**Issue by xiawanyingtest** [apache/incubator-shenyu#2209]
### Question

zookeeper://localhost:2181,localhost:2182 报错了，多个zook怎么配置

**Comment by midnight2104** [comment]
hi, what is your config and scene? pls provide more info,such as: error message

**Comment by xiawanyingtest** [comment]
> > zookeeper://localhost:2182,localhost:2181
> 
> dubbo config this ? if have multi register?

how to config  zook multi register?

**Comment by yu199195** [comment]
@xiawanyingtest  you can see dubbo doc , how to config register.
