### ISSUE TITLE
[BUG] <title>The plug-in reports a null pointer when calling the interface

### ISSUE THREAD

**Issue by qzpm123** [apache/incubator-shenyu#2211]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我开启了oauth2插件，调用接口的时候报空指针
![DC@QSHPF5(A4IL%VJ4W0PHI](https://user-images.githubusercontent.com/92358153/136906050-b90e6d52-3501-48f6-b5d8-7c3ac8127520.png)

这是配置上面的问题么？？
![WG439{H~3N@M%3MV@4NQT(A](https://user-images.githubusercontent.com/92358153/136906097-0ed882cb-a655-4228-80c0-04eeac9d0abc.png)

### Environment

```markdown
ShenYu version(2.4.0):
```

**Comment by qzpm123** [comment]
> Please provide your oauth2 configuration
选择器和规则都未配置
![image](https://user-images.githubusercontent.com/92358153/136920914-de3a8d3d-5d3d-40a1-93c0-0668a31c41a6.png)
未配置启用
![image](https://user-images.githubusercontent.com/92358153/136920873-393ed042-4d95-4108-b1d8-f7ecd1620aa8.png)
网关引入oauth2 
![image](https://user-images.githubusercontent.com/92358153/136920813-f02f1112-2741-4a2f-979a-aaa25a4fcc89.png)

**Comment by Zhoutzzz** [comment]
> > Please provide your oauth2 configuration
> > 选择器和规则都未配置
> > ![image](https://user-images.githubusercontent.com/92358153/136920914-de3a8d3d-5d3d-40a1-93c0-0668a31c41a6.png)
> > 未配置启用
> > ![image](https://user-images.githubusercontent.com/92358153/136920873-393ed042-4d95-4108-b1d8-f7ecd1620aa8.png)
> > 网关引入oauth2
> > ![image](https://user-images.githubusercontent.com/92358153/136920813-f02f1112-2741-4a2f-979a-aaa25a4fcc89.png)

so，your mean is you open the plugin, the selector and rules don't config, then you find the NPE, what is you oauth2 configuration in .yml file?

**Comment by qzpm123** [comment]
Oauth2 is not configured in the. YML file of the bootstrap project




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-shenyu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月13日(星期三) 上午9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/incubator-shenyu] [BUG] <title&gt;oauth2插件，调用接口的时候报空指针 (#2211)





   
Please provide your oauth2 configuration
 选择器和规则都未配置
 
 未配置启用
 
 网关引入oauth2
 
   
so，your mean is you open the plugin, the selector and rules don't config, then you find the NPE, what is you oauth2 configuration in .yml file?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Zhoutzzz** [comment]
> Oauth2 is not configured in the. YML file of the bootstrap project
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/incubator-shenyu" ***@***.***&gt;; 发送时间:&nbsp;2021年10月13日(星期三) 上午9:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [apache/incubator-shenyu] [BUG] <title&gt;oauth2插件，调用接口的时候报空指针 (#2211) Please provide your oauth2 configuration 选择器和规则都未配置 未配置启用 网关引入oauth2 so，your mean is you open the plugin, the selector and rules don't config, then you find the NPE, what is you oauth2 configuration in .yml file? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Based on the information you provided, I found this problem because using the OAuth2 plug-in requires two conditions.
   1. dependence OAuth2 starter. 
   2 configure Spring Security's clientId and clientSecret in the .yml file of bootstrap. 
The plugin will not take effect if either condition is missing. You did not write the configuration in the .yml file, so the plugin will not take effect. That triggered the NPE. I've fixed it
