### ISSUE TITLE
[BUG]  modify-response-plugin  and cryptor-response-plugin are used in combination, and no information is returned

### ISSUE THREAD

**Issue by likedong** [apache/incubator-shenyu#2225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/32168430/137473092-fa2855be-275e-44dd-8dde-15abe9c2911f.png)
![image](https://user-images.githubusercontent.com/32168430/137473182-2ebf37ac-e05b-476c-9895-27f5314ac1aa.png)

### Expected Behavior

Return information correctly

### Steps To Reproduce
 
1.use modify response plugin , set removeBodyKes  $code
2.use cryptor response plugin , set encrypt data.name

Returned JSON format
{
       "code": 200,
        "msg": "",
        "data": {
                        "id": "",
                       "name": ""
           }
}

### Environment

```markdown
ShenYu version(s): master
```

### Debug logs

Response Code: 200 OK

[Response Headers Start]
transfer-encoding: chunked
Content-Type: application/json
Content-Length: 0
[Response Headers End]

[Response Body Start]

[Response Body End]

**Comment by impactCn** [comment]
There is a problem with the combination? Is it okay to separate each one?
