### ISSUE TITLE
[BUG] Download page is 404

### ISSUE THREAD

**Issue by zouyx** [apache/incubator-shenyu#2235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1413" alt="截屏2021-10-21 上午10 19 44" src="https://user-images.githubusercontent.com/3828072/138200468-64e9608c-5e52-4eac-b78d-222e8b2a3bda.png">

### Expected Behavior

I am not sure..

### Steps To Reproduce

1. open https://shenyu.apache.org/download/
2. click [Apache ShenYu (incubating)]

### Environment

```markdown
ShenYu version(s):
```

### Anything else?

nothing

**Comment by HessTina-YuI** [comment]
Thanks, I will deal with it right away

**Comment by HessTina-YuI** [comment]
OK, it's solved. 
[](https://github.com/apache/incubator-shenyu-website/pull/317)
