### ISSUE TITLE
[Volunteer]  Add unit test for URIPlugin

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2236]
### Volunteer help

Volunteer help to add unit test for `org.apache.shenyu.plugin.uri.URIPlugin`

you can create `org.apache.shenyu.plugin.uri.URIPluginTest` in  `/test/java` package

**Comment by lishijiee** [comment]
get

**Comment by songyuequan** [comment]
Hello~, what is the Progress? @lishijiee

**Comment by haibo-duan** [comment]
Is there any progress on this issue?If not, please assign it to me.

**Comment by songyuequan** [comment]
> Is there any progress on this issue?If not, please assign it to me.
Hi~,I think there is no progress  for a long time. 
In order to improve the UT Coverage.
 I have assign to you in https://github.com/apache/incubator-shenyu/issues/2420 
thank you @haibo-duan   

And. you can  take  some  other  tasks  when you have enough. time. @lishijiee
