### ISSUE TITLE
[Integration-Test] Add integration test for cryptor plugin

### ISSUE THREAD

**Issue by JooKS-me** [apache/incubator-shenyu#2239]
### Task

- [x] add integration test for CryptorRequest plugin.
- [x] add integration test for CryptorResponse plugin.

**Comment by songyuequan** [comment]
Hello, I'll do integration test for CryptorResponse plugin.

**Comment by JooKS-me** [comment]
> Hello, I'll do integration test for CryptorResponse plugin.

Thanks for help~
