### ISSUE TITLE
[BUG] There is an error in the official document describes how to use docker in mysql mode to deploy Shenyun

### ISSUE THREAD

**Issue by vycz** [apache/incubator-shenyu#2250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i tried to use docker in mysql mode to deploy Shenyun,i found it can`t runs as I expected

### Expected Behavior

https://shenyu.apache.org/zh/docs/deployment/deployment-docker

### Steps To Reproduce

docker run -v /${your_work_dir}/ext-lib:/opt/shenyu-admin/ext-lib -e "SPRING_PROFILES_ACTIVE=mysql" -e "spring.datasource.url=jdbc:mysql://${your_ip_port}/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false" -e "spring.datasource.**user**=${your_username}" -e "spring.datasource.password=${your_password}" -d -p 9095:9095 --net shenyu apache/shenyu-admin

Should be modified to

docker run -v /${your_work_dir}/ext-lib:/opt/shenyu-admin/ext-lib -e "SPRING_PROFILES_ACTIVE=mysql" -e "spring.datasource.url=jdbc:mysql://${your_ip_port}/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false" -e "spring.datasource.**username**=${your_username}" -e "spring.datasource.password=${your_password}" -d -p 9095:9095 --net shenyu apache/shenyu-admin

### Environment

```markdown
ShenYu version(s): lasted
```

**Comment by Mayank-KS** [comment]
Can I try working on this issue? And is there some reading material/reference for this issue?
