### ISSUE TITLE
modify the body parameter in param_mapping plugin an error occurred

### ISSUE THREAD

**Issue by chengfei602** [apache/incubator-shenyu#2256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/14965023/138650229-8808a818-11fe-43e6-99ef-524399fba766.png)

### Environment

```markdown
ShenYu version(s):2.4.1
```

### Debug logs

2index.3c0609d9.js:18 Uncaught TypeError: Cannot read properties of undefined (reading 'activeKey')
    at t.r.onChangeConfig (index.3c0609d9.js:18)
    at Object.onChange (index.3c0609d9.js:18)
    at t.n.fireChange (index.3c0609d9.js:18)
    at Object.n.onMenuSelect [as onClick] (index.3c0609d9.js:18)
    at Object.n.onClick (index.3c0609d9.js:18)
    at t.n.onClick (index.3c0609d9.js:18)
    at onClick (index.3c0609d9.js:18)
    at e.onClick (index.3c0609d9.js:18)
    at Object.o (index.3c0609d9.js:18)
    at a (index.3c0609d9.js:18)
r.onChangeConfig @ index.3c0609d9.js:18
onChange @ index.3c0609d9.js:18
n.fireChange @ index.3c0609d9.js:18
n.onMenuSelect @ index.3c0609d9.js:18
n.onClick @ index.3c0609d9.js:18
n.onClick @ index.3c0609d9.js:18
onClick @ index.3c0609d9.js:18
e.onClick @ index.3c0609d9.js:18
o @ index.3c0609d9.js:18
a @ index.3c0609d9.js:18
i @ index.3c0609d9.js:18
c @ index.3c0609d9.js:18
ie @ index.3c0609d9.js:18
ae @ index.3c0609d9.js:18
ce @ index.3c0609d9.js:18
de @ index.3c0609d9.js:18
ia @ index.3c0609d9.js:18
g @ index.3c0609d9.js:18
Te @ index.3c0609d9.js:18
ke @ index.3c0609d9.js:18
WifJ.t.unstable_runWithPriority @ index.3c0609d9.js:18
Wt @ index.3c0609d9.js:18
v @ index.3c0609d9.js:18
Ne @ index.3c0609d9.js:18

**Comment by AhahaGe** [comment]
can you detail you operate step, sorry I can't understand.

**Comment by AhahaGe** [comment]
this is a front bug, and still exist in branch v2.4.1, need front contributor.

**Comment by chenzfp** [comment]
This front bug is caused by the variable declaration problem in line 146 of the "Parampluginrulehandle.js" file, Please fix it.
const state = state; ---> const state = this.state; add "this" @yu199195

**Comment by chenzfp** [comment]
Do the Param functions of plugin "request" and plugin "param_mapping" overlap

**Comment by midnight2104** [comment]
Hi, does this question still exist? If there is still a problem, please resubmit the issue.
