### ISSUE TITLE
[BUG] No link to issue tracker from website

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-shenyu#2258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot find a link to the issue tracker

### Expected Behavior

Should exist

### Environment

```markdown
ShenYu version(s):
```

**Comment by AhahaGe** [comment]
I found it in the bottom of the page, what need we do? if no could we close this issue?

**Comment by sebbASF** [comment]
Users should not have to scroll to the bottom of the page to find such items.

If the bottom of the page is consider a suitable place for the issue tracker, why is GitHub on the top menu as well?
Surely it should only be at the bottom?
Likewise several other items.

**Comment by yu199195** [comment]
we will fix it : https://shenyu.apache.org/download/
