### ISSUE TITLE
[Question] <Whether the role_id field  is used anywhere in the dashboard_user table>

### ISSUE THREAD

**Issue by fengzhenbing** [apache/incubator-shenyu#2264]
### Question

Whether the role_id field  is used anywhere in the dashboard_user table?
* If it is used,we should modify the field name as it is not the role meaning.  We have the role table to implement the role function
*  If it is not used, maybe we should delete it.

**Comment by AhahaGe** [comment]
Do you mean the field name role in table dashboard_user table, as there is no field name role_id in that table.
Role field in dashboard_user table should not be used, as user_role table hold role relation ship. When we create user, we use user_role table to store relationship, and set role(1) for all user.
I agree delete role field in dashboard_user table.

**Comment by yu199195** [comment]
@fengzhenbing @AhahaGe  do not delete it， Permissions will be used

**Comment by midnight2104** [comment]
Hi, does this question still exist? If there is still a problem, please resubmit the issue.
