### ISSUE TITLE
[BUG] <When the client configuration registerType is Nacos and the ifFull attribute is true, the dataId Invalid exception will occur at this time>

### ISSUE THREAD

**Issue by wtlihao** [apache/incubator-shenyu#2275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When registering a nacos node：
shenyu.register.service.http.{content-path}.**

### Expected Behavior

apache shenyu nacos doc:
shenyu.register.service.http.{content-path}

### Steps To Reproduce

1. config:
shenyu:
  client:
    registerType: nacos
    serverLists: localhost:8844
    props:
      contextPath: ${server.servlet.context-path}
      port: ${server.port}
      nacosNameSpace: ShenyuRegisterCenter
      isFull: true
2. 

### Environment

```markdown
ShenYu version(s):2.4.1
```

### Debug logs

![image](https://user-images.githubusercontent.com/30258468/139173844-0873f637-3db8-44bb-bd98-b675033fb30b.png)

**Comment by KevinClair** [comment]
Any progess?
