### ISSUE TITLE
[Question]it's error in the official document describes how to use docker in mysql ,it's not load customer define application.yml

### ISSUE THREAD

**Issue by civism** [apache/incubator-shenyu#2308]
### Question

- [x] Question one：
`docker run -v ${your_work_dir}/conf:/opt/shenyu-admin/conf/ -v /${your_work_dir}/ext-lib:/opt/shenyu-admin/ext-lib -d -p 9095:9095 --net shenyu apache/shenyu-admin`   Should be changed to `docker run -v ${your_work_dir}/conf:/opt/shenyu-admin/conf -v /${your_work_dir}/ext-lib:/opt/shenyu-admin/ext-lib -d -p 9095:9095 --net shenyu apache/shenyu-admin` 

- [x] Question two：
customer define application.yml  be used but it can't load 

- [x] Question three：
shenyu-admin.log and shenyu-admin-error.log shoud be put in logs

**Comment by tuohai666** [comment]
Hi @civism Can you provide your application.yml?

**Comment by tuohai666** [comment]
Hi @civism Would you like to fix **Question one**? You can submit a pr to fix it exactly like you have mentioned.

**Comment by tuohai666** [comment]
- [ ] Please make sure the changes of Question one exist in both English & Chinese docs and in both 2.4.1 and current version

**Comment by civism** [comment]
I have fixed it and submitted a pull on [](https://github.com/apache/incubator-shenyu-website/pull/359)

**Comment by tuohai666** [comment]
Hi @civism I don't think this fix is complete.  (English & Chinese) * (2.4.1 & current) = 4 places to be fixed.
Please correct me if i was wrong.

**Comment by civism** [comment]
@tuohai666  I submitted a new PR to fix the current version  about [link]( https://github.com/apache/incubator-shenyu-website/pull/364)
