### ISSUE TITLE
[Question] Whether `org.apache.shenyu.common.utils.CollectionUtils` should be replaced?

### ISSUE THREAD

**Issue by midnight2104** [apache/incubator-shenyu#2312]
### Question

I found that shenyu uses `org.apache.shenyu.common.utils.CollectionUtils`, but `org.apache.commons.collections4.CollectionUtils` provides the corresponding methods. Do I need to replace `org.apache.shenyu.common.utils.CollectionUtils` with `org.apache.commons.collections4.CollectionUtils`.

- `org.apache.shenyu.common.utils.CollectionUtils`

```java

public class CollectionUtils {

    /**
     * Is empty boolean.
     *
     * @param coll the coll
     * @return the boolean
     */
    public static boolean isEmpty(final Collection<?> coll) {
        return coll == null || coll.isEmpty();
    }

    /**
     * Is not empty boolean.
     *
     * @param coll the coll
     * @return the boolean
     */
    public static boolean isNotEmpty(final Collection<?> coll) {
        return !isEmpty(coll);
    }
}
```

- `org.apache.commons.collections4.CollectionUtils`

```java

    public static boolean isEmpty(Collection<?> coll) {
        return coll == null || coll.isEmpty();
    }

    public static boolean isNotEmpty(Collection<?> coll) {
        return !isEmpty(coll);
    }

```

If a replacement is needed, please assign that task to me, thanks~

**Comment by yu199195** [comment]
yes， you can

**Comment by midnight2104** [comment]
merged pr     https://github.com/apache/incubator-shenyu/pull/2324
