### ISSUE TITLE
[BUG] shenyu-admin: the plugin sort can not support > 100

### ISSUE THREAD

**Issue by qicz** [apache/incubator-shenyu#2316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

can not choose the `pluginList` option
![image](https://user-images.githubusercontent.com/2174082/140882643-fcc89521-2572-44ac-bfdf-27c8bbe6a028.png)

the sort can not support > 100

### Expected Behavior

the sort support > 100

### Environment

```markdown
ShenYu version(s): last
```

**Comment by qicz** [comment]
![image](https://user-images.githubusercontent.com/2174082/140882643-fcc89521-2572-44ac-bfdf-27c8bbe6a028.png)



the sort can not support > 100

**Comment by AhahaGe** [comment]
if not fixed, please add label front bug, so that front guys can pick up quickly, and backend need not check again. @yu199195 @qicz

**Comment by qicz** [comment]
> if not fixed, please add label front bug, so that front guys can pick up quickly, and backend need not check again. @yu199195 @qicz

I can not assign the label 'front bug'. @yu199195

**Comment by yu199195** [comment]
@qicz  you can creator this  lable in shenyu-dashboard

**Comment by qicz** [comment]
> @qicz you can creator this lable in shenyu-dashboard

copy

**Comment by qicz** [comment]
move to shenyu-dashboard https://github.com/apache/incubator-shenyu-dashboard/issues/159.
