### ISSUE TITLE
[Task] Enhance the docker start commands

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shenyu#2337]
### Description

The commands now like:

- docker run -d -p 9095:9095 --net shenyu apache/shenyu-admin

- docker run -v /${your_work_dir}/ext-lib:/opt/shenyu-admin/ext-lib -e "SPRING_PROFILES_ACTIVE=mysql" -e "spring.datasource.url=jdbc:mysql://${your_ip_port}/shenyu?useUnicode=true&characterEncoding=utf-8&useSSL=false" -e "spring.datasource.username=${your_username}" -e "spring.datasource.password=${your_password}" -d -p 9095:9095 --net shenyu apache/shenyu-admin

- docker run -v ${your_work_dir}/conf:/opt/shenyu-admin/conf/ -v /${your_work_dir}/ext-lib:/opt/shenyu-admin/ext-lib -d -p 9095:9095 --net shenyu apache/shenyu-admin

I would suggest we add paramenters to make the commands more available like:

1. --privileged=true 
1. -v /etc/localtime:/etc/localtime:ro 
1. --restart=always

Are these parameters right? Any more parameters should be added?

**Comment by jinze1107** [comment]
i suggest add some env

**Comment by tuohai666** [comment]
> i suggest add some env

Can you provide some details?

**Comment by tuohai666** [comment]
@nuo-promise 
> I think these three configurations are a bit system-specific (Linux).
Considering that the systems using our products may be other systems, it
may be possible to consider not adding them. If you need these features for
your production environment, you can do it yourself.

Agree. Let's provide the minimal parameters which are required, while user can customize parameters which meet their needs.
