### ISSUE TITLE
[BUG] The logs of admin are not located in the logs directory in container

### ISSUE THREAD

**Issue by tuohai666** [apache/incubator-shenyu#2341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The logs of admin are not located in the logs dir, but in the top dir in the container.
While there's no problem of the logs when admin run in a host machine.

### Expected Behavior

The logs of admin are located in the logs directory instead of top dir in a container.

### Environment

```markdown
ShenYu version(s): 2.4.1
```

**Comment by jinze1107** [comment]
log config right?

**Comment by civism** [comment]
I can help with it

**Comment by tuohai666** [comment]
@civism Thank you for reach out. I have assigned this issue to you.

**Comment by tuohai666** [comment]
@civism  I would suggest that you provide the test result of the new script run in both container and host.

**Comment by tuohai666** [comment]
This problem may be root cause of https://github.com/apache/incubator-shenyu/pull/1816

**Comment by tuohai666** [comment]
@civism I have merged your pr, but the test results are still required. Let's keep this issue open until all tests are complete.

**Comment by civism** [comment]
@tuohai666 Hi,The following are my test results：
Use h2 database in shenyu-admin:
![shenyu-admin-h2](https://user-images.githubusercontent.com/21138330/141931975-395744ae-b160-4a4a-b1c1-95c07dc72f83.png)  
Use mysql database in shenyu-admin:
![shenyu-admin-mysql](https://user-images.githubusercontent.com/21138330/141932000-d2057929-5eca-46c8-a4d9-8420eed21381.png)
shenyu-bootstrap test log output:
![shenyu-bootstrap](https://user-images.githubusercontent.com/21138330/141932007-9473ea88-c60a-4e86-afaa-b8fb263ad9cd.png)
The log is output to the logs file in shenyu-admin and shenyu-bootstrap

**Comment by tuohai666** [comment]
@civism Thanks for the test. This issue can be closed.
