### ISSUE TITLE
If there are spaces in the ip, the heartbeat check will fail 

### ISSUE THREAD

**Issue by gaochuang98** [apache/incubator-shenyu#2346]
If there are spaces in the ip, the heartbeat check will fail，Although it may not happen

**Comment by tuohai666** [comment]
@gaochuang98 Please modify the tile and content according to what you want to do.

**Comment by tuohai666** [comment]
@gaochuang98 If you would like to solve this problem, I'll remove the Volunteer label.

**Comment by tuohai666** [comment]
Can you provide some details?

**Comment by gaochuang98** [comment]
![48ccb192dfb08e42c2c6016bae96eb7](https://user-images.githubusercontent.com/49777877/141431508-f5edbd18-0d3e-4fdc-8f92-e88103faf3f9.png)
As shown in the figure，

**Comment by yu199195** [comment]
can you fix it ？
