### ISSUE TITLE
[Volunteer] <Remove warning  code in shenyu-plugin module>

### ISSUE THREAD

**Issue by songyuequan** [apache/incubator-shenyu#2370]
### Volunteer help

- [x] shenyu-plugin-api @songyuequan
- [x] shenyu-plugin-base @songyuequan 
- [x] shenyu-plugin-global @heihei180
- [x] shenyu-plugin-logging @YanHui-Yang
- [x] shenyu-plugin-request @dizent
- [x] shenyu-plugin-resilience4j @haibo-duan 
- [x] shenyu-plugin-response  @haibo-duan 
- [x] shenyu-plugin-rewrite @zendwang 
- [x] shenyu-plugin-sign @zendwang 
- [x] shenyu-plugin-tars @haibo-duan
- [x] shenyu-plugin-uri  @haibo-duan
- [x] shenyu-plugin-context-path @AhahaGe
- [x] shenyu-plugin-redirect  @YanHui-Yang
- [x] shenyu-plugin-motan @YanHui-Yang
- [x] shenyu-plugin-oauth2 @choconana
- [x] shenyu-plugin-ratelimiter @choconana
- [x] shenyu-plugin-sofa @li-keguo 
- [x] shenyu-plugin-cryptor @impactCn 
- [x] shenyu-plugin-monitor @Jossc 
- [x] shenyu-plugin-grpc  @li-keguo 
- [x] shenyu-plugin-sentinel @songyuequan
- [x] shenyu-plugin-dubbo @dizent
-------------------------------------
- [x] shenyu-plugin-waf @zendwang  checked
- [x] shenyu-plugin-websocket @zendwang  checked
- [x] shenyu-plugin-hystrix @isevenluo  checked
- [x] shenyu-plugin-springcloud @choconana checked 
- [x] shenyu-plugin-divide @choconana checked 
- [x] shenyu-plugin-httpclient @dizent checked
- [x] shenyu-plugin-jwt @songyuequan checked
------------------------------------
- [x] shenyu-plugin-modify-response  @songyuequan  
- [x] shenyu-plugin-param-mapping  @songyuequan

**Comment by li-keguo** [comment]
I want to optimize  shenyu-plugin-grpc, I am familiar with this code

**Comment by songyuequan** [comment]
> I want to optimize shenyu-plugin-grpc, I am familiar with this code

thank you  for your help

**Comment by Berrywrq** [comment]
I want to optimize shenyu-plugin-dubbo, shenyu-plugin-sentinel and shenyu-plugin-jwt

**Comment by li-keguo** [comment]
> > I want to optimize shenyu-plugin-grpc, I am familiar with this code
> 
> thank you for your help

it shenyu-plugin-sofa, I wrote it wrongly, shenyu-plugin-grpc can also try, learn a wave

**Comment by songyuequan** [comment]
> > > I want to optimize shenyu-plugin-grpc, I am familiar with this code
> > 
> > 
> > thank you for your help
> 
> it shenyu-plugin-sofa, I wrote it wrongly, shenyu-plugin-grpc can also try, learn a wave

Just  try

**Comment by zendwang** [comment]
I want to optimize  shenyu-plugin-waf、shenyu-plugin-websocket.

**Comment by heihei180** [comment]
i want to optomize `shenyu-plugin-cryptor`

**Comment by haibo-duan** [comment]
i want to optomize shenyu-plugin-tars and shenyu-plugin-uri.
please assign it to me.

**Comment by Jossc** [comment]
I want to optimize Shenyu-plugin-monitor,  please assign it to me.

**Comment by songyuequan** [comment]
Hei~, II have assign  these tasks to you. .  @Jossc    @haibo-duan  @heihei180  @zendwang

**Comment by YanHui-Yang** [comment]
I want to optimize shenyu-plugin-logging

**Comment by heihei180** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    shenyu-plugin-global
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    On 11/17/2021 ***@***.***> wrote： 



Hei~, II have assign  these tasks to you. .  @Jossc    @haibo-duan  @heihei180  @zendwang

**Comment by heihei180** [comment]
let me try ` shenyu-plugin-global`

**Comment by heihei180** [comment]
ok, u can do it.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Wed, Nov 17, 2021 19:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/incubator-shenyu] [Volunteer] <Remove warning  code inshenyu-plugin module&gt; (Issue #2370)




 
I want to optimize shenyu-plugin-hystrix
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YanHui-Yang** [comment]
I also want to optimize shenyu-plugin-motan. Thanks!

**Comment by haibo-duan** [comment]
i want to optimize  shenyu-plugin-resilience4j and shenyu-plugin-response.
please assign it to me.

**Comment by zendwang** [comment]
> Hei~, II have assign these tasks to you. . @Jossc @haibo-duan @heihei180 @zendwang

I can't find warning code.

**Comment by songyuequan** [comment]
> I also want to optimize shenyu-plugin-motan and shenyu-plugin-redirect and shenyu-plugin-response. Thanks!

Ok , thank you

**Comment by songyuequan** [comment]
Hei ~. I just assign shenyu-plugin-response to  @YanHui-Yang
you can do shenyu-plugin-resilience4j . @haibo-duan 

> i want to optimize shenyu-plugin-resilience4j and shenyu-plugin-response.
> please assign it to me.

**Comment by songyuequan** [comment]
> I also want to optimize shenyu-plugin-motan and shenyu-plugin-redirect and shenyu-plugin-response. Thanks!

Hei~I just assign shenyu-plugin-motan and shenyu-plugin-redirect  to you @@YanHui-Yang

**Comment by isevenluo** [comment]
> I want to optimize shenyu-plugin-hystrix

I didn't find the warning for shenyu-plugin-hystrix. What else can I optimize

**Comment by songyuequan** [comment]
> > I want to optimize shenyu-plugin-hystrix
> 
> I didn't find the warning for shenyu-plugin-hystrix. What else can I optimize

 shenyu-plugin-modify-response
 shenyu-plugin-param-mapping  

I  will assign  these   to  you  @isevenluo

**Comment by AhahaGe** [comment]
please assign some task to me?

**Comment by songyuequan** [comment]
> please assign some task to me?

I have assigned shenyu-plugin-context-path  to you.  you can have a try

**Comment by heihei180** [comment]
> > please assign some task to me?
> 
> I have assigned shenyu-plugin-context-path to you. you can have a try @AhahaGe

pls assign to me `shenyu-plugin-resilience4j`

**Comment by songyuequan** [comment]
> > > please assign some task to me?
> > 
> > 
> > I have assigned shenyu-plugin-context-path to you. you can have a try @AhahaGe
> 
> pls assign to me `shenyu-plugin-resilience4j`

Sorry , I have assign   `shenyu-plugin-resilience4j` to @haibo-duan  Do you have finished  `shenyu-plugin-cryptor` ? @heihei180

**Comment by heihei180** [comment]
> > > > please assign some task to me?
> > > 
> > > 
> > > I have assigned shenyu-plugin-context-path to you. you can have a try @AhahaGe
> > 
> > 
> > pls assign to me `shenyu-plugin-resilience4j`
> 
> Sorry , I have assign `shenyu-plugin-resilience4j` to @haibo-duan Do you have finished `shenyu-plugin-cryptor` ? @heihei180

`cryptor` has discuss in  wechat groupchat, and @sinsy will do it.

**Comment by heihei180** [comment]
> > > > > please assign some task to me?
> > > > 
> > > > 
> > > > I have assigned shenyu-plugin-context-path to you. you can have a try @AhahaGe
> > > 
> > > 
> > > pls assign to me `shenyu-plugin-resilience4j`
> > 
> > 
> > Sorry , I have assign `shenyu-plugin-resilience4j` to @haibo-duan Do you have finished `shenyu-plugin-cryptor` ? @heihei180
> 
> `cryptor` has discuss in wechat groupchat, and @sinsy will do it.

@impactCn rather than @sinsy

**Comment by songyuequan** [comment]
> @impactCn

Ok, thank you

**Comment by isevenluo** [comment]
> > > I want to optimize shenyu-plugin-hystrix
> > 
> > 
> > I didn't find the warning for shenyu-plugin-hystrix. What else can I optimize
> 
> shenyu-plugin-modify-response shenyu-plugin-param-mapping
> 
> I will assign these to you @isevenluo

Ok, thank you. I will try to finish these two projects

**Comment by songyuequan** [comment]
Hi~ what is the progress?  @choconana  @Berrywrq @Jossc

**Comment by choconana** [comment]
Sorry, I’m busy recently, but I have reviewed some module before, so the task will be completed within these two days.
| |
zdhe9535
|
|
***@***.***
|
签名由网易邮箱大师定制


On 11/25/2021 ***@***.***> wrote：

Hi~ what is the progress? @***@***.***@Jossc

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by songyuequan** [comment]
> Sorry, I’m busy recently, but I have reviewed some module before, so the task will be completed within these two days. | | zdhe9535 | | ***@***.*** | 签名由网易邮箱大师定制 On 11/25/2021 ***@***.***> wrote： Hi~ what is the progress? @***@***.***@Jossc — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

OK，thank you very much.

**Comment by choconana** [comment]
there are not warning codes in module shenyu-plugin-springcloud and shenyu-plugin-divide

**Comment by songyuequan** [comment]
> there are not warning codes in module shenyu-plugin-springcloud and shenyu-plugin-divide

Ok, thank you .

**Comment by songyuequan** [comment]
Done
