### ISSUE TITLE
[BUG] <scripts. start.sh  in different JDK version ,parameter in JAVA_OPTS  is invalid >in macos jdk version is 11，start.sh do not work 

### ISSUE THREAD

**Issue by IceFoxs** [apache/incubator-shenyu#2390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/26451038/142213238-fa9c5394-7762-4196-9e00-ce2fce1b7a9d.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/26451038/142213703-8a4042d0-5f4c-4f57-a219-bd72ba2f8c0d.png)
remove -XX:+UseFastAccessorMethods
./start.sh  do work .

### Environment

```markdown
ShenYu version(s):2.4.1
```

**Comment by yu199195** [comment]
can you fix it？

**Comment by impactCn** [comment]
![image](https://user-images.githubusercontent.com/35489877/142342615-d626bbf0-fe5a-4332-b826-d5a5d6874eb8.png)

Edit start.sh, find the'UseFastAccessorMethods' parameter and remove it. It should be ready to start.

**Comment by IceFoxs** [comment]
In the script, judge the JDK version and select the GC optimization parameters of the corresponding version.
it will be  better.

**Comment by yu199195** [comment]
@IceFoxs  you can fix it

**Comment by IceFoxs** [comment]
> @IceFoxs you can fix it
I try fix it

**Comment by IceFoxs** [comment]
> @IceFoxs you can fix it
I already submit the pr ,you can check it.

**Comment by midnight2104** [comment]
done
