### ISSUE TITLE
[Question]File upload error413Request Entity Too Large

### ISSUE THREAD

**Issue by yinj51** [apache/incubator-shenyu#2432]
### Question
vertion: shenyu 2.4.1-SNAPSHOT
Error code: 413
Error message: Request Entity Too Large。
describe:Using alicloud OSS, the gateway directly intercepts and reports errors
![_20211122164305](https://user-images.githubusercontent.com/66461549/142829991-9a932a25-9d15-47dc-ac29-7243cc78b9d9.png)

**Comment by yu199195** [comment]
pls use english， and follow the issue template。

**Comment by yinj51** [comment]
> pls use english， and follow the issue template。

Please look at the picture

**Comment by yinj51** [comment]
> ### Question
> vertion: shenyu 2.4.1-SNAPSHOT Error code: 413 Error message: Request Entity Too Large。 describe:Using alicloud OSS, the gateway directly intercepts and reports errors ![_20211122164305](https://user-images.githubusercontent.com/66461549/142829991-9a932a25-9d15-47dc-ac29-7243cc78b9d9.png)

**Comment by yinj51** [comment]
After testing, it exceeds 100kb and will report 413

**Comment by yu199195** [comment]
This is a tip for your own real service， pls check your server

**Comment by midnight2104** [comment]
done
