### ISSUE TITLE
[BUG] <title>Some Handler Not registered to SpringIOC

### ISSUE THREAD

**Issue by OnlyQuiet** [apache/incubator-shenyu#2438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cryptor plugin invalid
![图片](https://user-images.githubusercontent.com/41868553/143018109-f177e413-1ff5-4b53-b9d7-1a70060013b6.jpg)

### Expected Behavior

Cryptor plugin effect

### Steps To Reproduce

1、jdk 1.8，ShenYu 2.4.1
 2、Run the official example include ShenYu-admin and ShenYu-bootstrap
3、ShenYu-bootstrap pom add dependency
 ```
<!-- apache shenyu Cryptor Request plugin start-->
<dependency>
   <groupId>org.apache.shenyu</groupId>
   <artifactId>shenyu-spring-boot-starter-plugin-cryptor</artifactId>
   <version>${project.version}</version>
 </dependency>
 <!-- apache shenyu Cryptor Request plugin end-->
 ```
 4、deploy selector and rule
 5、request url
 6、error
`ERROR org.apache.shenyu.plugin.cryptor.request.CryptorRequestPlugin - Cryptor request rule configuration is null :1463105512063905792`

### Environment

```markdown
ShenYu version(s):2.4.1
```

### Anything else?

Cryptor plugin Handler Not registered to SpringIOC
![image](https://user-images.githubusercontent.com/41868553/143018394-018606e9-68be-421b-9fa3-ef0acb48f58c.png)

`org.apache.shenyu.springboot.starter.plugin.cryptor.CryptorPluginConfiguration`

add method

```
    @Bean
    public PluginDataHandler cryptorRequestPluginDataHandler() {
        return new CryptorRequestPluginDataHandler();
    }

    @Bean
    public PluginDataHandler cryptorResponsePluginDataHandler() {
        return new CryptorResponsePluginDataHandler();
    }
```

Cryptor plugin effect.

Handler registered to SpringIOC List：

0 = {DividePluginDataHandler@6198} 
1 = {ContextPathPluginDataHandler@6199} 
2 = {RateLimiterPluginDataHandler@6200} 
3 = {HystrixPluginDataHandler@6201} 
4 = {WafPluginDataHandler@6202} 
5 = {MonitorPluginDataHandler@6203} 
6 = {Resilience4JHandler@6204} 
7 = {SentinelRuleHandle@6205} 
8 = {RedirectPluginDataHandler@6206} 
9 = {RewritePluginDataHandler@6207} 
10 = {TarsPluginDataHandler@6208} 
11 = {GrpcPluginDataHandler@6209} 
12 = {JwtPluginDataHandler@6210} 
13 = {SofaPluginDataHandler@6211} 
14 = {AlibabaDubboPluginDataHandler@6212} 
15 = {WebSocketPluginDataHandler@6213} 
16 = {ModifyResponsePluginDataHandler@6214} 
17 = {ParamMappingPluginDataHandler@6215} 

Other plugins have this bug

**Comment by impactCn** [comment]
I will keep track of this issue.

**Comment by impactCn** [comment]
hi, the current problem has been fixed in the master version.

**Comment by impactCn** [comment]
> hi, the current problem has been fixed in the master version.

https://github.com/apache/incubator-shenyu/pull/2244.

**Comment by OnlyQuiet** [comment]
thanks
