### ISSUE TITLE
I have a problem with the springcloud proxy plug-in

### ISSUE THREAD

**Issue by ldinger** [apache/incubator-shenyu#2477]
### Question

?

**Comment by yu199195** [comment]
used english and follow the issue template

**Comment by ldinger** [comment]
look this 
the hosts of my computer:
------
127.0.01 shenyu.test.com
-------
shenyu's version   is  2.4.1 
and  I have used the springcloud plug-in  
for example , the proxy address is  : shenyu.test.com/service-app1/test
postman and browser test this address  returns empty 
but  “curl” command line test returns normally 
curl shenyu.test.com/service-app1/test   returns is OK
browser returns :  net::ERR_EMPTY_RESPONSE
postman returns:  error: socket hang up


However, both 127.0.01 and localhost  can be returned normally

**Comment by yu199195** [comment]
shenyu.test.com Is it passable in your local area? What request method are you using? post and get?

**Comment by ldinger** [comment]
both ping  and  telnet can pass 
used GET request method  
os is  mac
“shenyu.test.com”  in  my hosts configuration file 
 I don't understand why "curl" is ok but browser and postman not passable

**Comment by yu199195** [comment]
can you  replace shenyu.test.comto ip:port ?
