### ISSUE TITLE
2.4.1 版本启动shenyu-admin 报table不存在.

### ISSUE THREAD

**Issue by bootstrap2025** [apache/incubator-shenyu#2500]
### Question

```2.4.1``` 版本，代码下载下来，启动shenyu-admin 报table不存在. 请问在哪里可以生成sql?

**Comment by WanShengWu** [comment]
shenyu-admin resource 目录下 sql-script目录

> ### 题
> `2.4.1`版本，代码下载下来，启动shenyu-admin 报表不存在。还有可以在哪里生成sql？

**Comment by bootstrap2025** [comment]
感谢，
