### ISSUE TITLE
500 Server Error for HTTP POST "/http/order/save"

### ISSUE THREAD

**Issue by bootstrap2025** [apache/incubator-shenyu#2505]
### Question

![image](https://user-images.githubusercontent.com/9637974/144250487-6a613507-ec35-4ea5-8bcd-7d96d8a155c7.png)
元数据注册成功了，但是访问测试例子时如下图
![image](https://user-images.githubusercontent.com/9637974/144249834-8e42eb39-341f-43d3-baa2-7e7169d97688.png)
参考文档中的例子测试，测试shenyu-examples http://localhost:9195/http/order/save 接口时返回500错误，可以帮忙看下是什么原因吗？ 感谢

**Comment by KevinClair** [comment]
Run `shenyu-bootstrap` and try it again.

**Comment by yu199195** [comment]
whats the version？

**Comment by bootstrap2025** [comment]
最新版本2.4.1

**Comment by bootstrap2025** [comment]
我发现我的问题了，bootstrap里pom里没有引入插件，加上接口就代理成功了，但是这里
![image](https://user-images.githubusercontent.com/9637974/144371087-b708ec48-2aa7-4c33-b1d8-490d509dcd79.png)
matchType 为啥是0 是和http 接口有关吗？

**Comment by midnight2104** [comment]
Is there still a problem?
