### ISSUE TITLE
客户端服务注册是根据rpcType拼接的，那所有服务都是一个servicename

### ISSUE THREAD

**Issue by xiangHannibal** [apache/incubator-shenyu#2509]
### Question

 private synchronized void registerService(final String rpcType, final String contextPath, final String host,
                                              final int port, final URIRegisterDTO registerDTO) {
        if (registerService) {
            return;
        }
        registerService = true;
        Instance instance = new Instance();
        instance.setEphemeral(true);
        instance.setIp(host);
        instance.setPort(port);
        Map<String, String> metadataMap = new HashMap<>();
        metadataMap.put(Constants.CONTEXT_PATH, contextPath);
        metadataMap.put("uriMetadata", GsonUtils.getInstance().toJson(registerDTO));
        instance.setMetadata(metadataMap);
        String serviceName = RegisterPathConstants.buildServiceInstancePath(rpcType);
        try {
            namingService.registerInstance(serviceName, instance);
        } catch (NacosException e) {
            throw new ShenyuException(e);
        }
        LOGGER.info("register service uri success: {}", serviceName);
    }

public static String buildServiceInstancePath(final String rpcType) {
        return String.join(SEPARATOR, ROOT_PATH, "service", rpcType)
                .replace("/", ".").substring(1);
    }

2.4.1这样拼接服务名，nacos注册上去的微服务名字都是一个样

![image](https://user-images.githubusercontent.com/6896623/144373777-5030d50a-7294-43fa-b075-0797fe448db2.png)

**Comment by yu199195** [comment]
pls used english， and  whats the version？

**Comment by lw1243925457** [comment]
can look: https://shenyu.apache.org/zh/docs/design/register-center-design#nacos%E6%B3%A8%E5%86%8C%E5%8E%9F%E7%90%86

nacos register explain.

**Comment by xiangHannibal** [comment]
> pls used english， and whats the version？

中文看不懂？2.4.1 。写的那么清楚看不见？是在解答问题还是在装逼？

**Comment by xiangHannibal** [comment]
> 



> can look: https://shenyu.apache.org/zh/docs/design/register-center-design#nacos%E6%B3%A8%E5%86%8C%E5%8E%9F%E7%90%86
> 
> nacos register explain.

这个方式有问题。如果有一个服务多个实例怎么区分？

**Comment by xiangHannibal** [comment]
> can look: https://shenyu.apache.org/zh/docs/design/register-center-design#nacos%E6%B3%A8%E5%86%8C%E5%8E%9F%E7%90%86
> 
> nacos register explain.

不是。你们是觉得这种方式没问题吗？就问怎么区分微服务。如果做不到就干脆不要支持，放个半成品拉低开源产品质量。

**Comment by lw1243925457** [comment]
![40d72146866c06c71ac84341e21dfc6](https://user-images.githubusercontent.com/11513436/146637769-ef07cc9e-137b-4afd-bc17-cb18f1ded623.png)
![198f17dc3feceb7462bdaa410f1a4e8](https://user-images.githubusercontent.com/11513436/146637779-ffd8e008-be8a-4c36-b54b-d8d0b8716289.png)
![b517e5f4b0a4717ff9f5e8b8e5bf052](https://user-images.githubusercontent.com/11513436/146637782-6560bef5-96c3-4a8b-afb5-c7d880ab2e6b.png)

you can read nacos:https://nacos.io/zh-cn/docs/sdk.html, then run example.

**Comment by xiangHannibal** [comment]
> ![40d72146866c06c71ac84341e21dfc6](https://user-images.githubusercontent.com/11513436/146637769-ef07cc9e-137b-4afd-bc17-cb18f1ded623.png) ![198f17dc3feceb7462bdaa410f1a4e8](https://user-images.githubusercontent.com/11513436/146637779-ffd8e008-be8a-4c36-b54b-d8d0b8716289.png) ![b517e5f4b0a4717ff9f5e8b8e5bf052](https://user-images.githubusercontent.com/11513436/146637782-6560bef5-96c3-4a8b-afb5-c7d880ab2e6b.png)
> 
> you can read nacos:https://nacos.io/zh-cn/docs/sdk.html, then run example.

这样的方式是只能在nacos注册一个微服务，其他所有的实例都在这一个微服务下。实际上，微服务不止一个，这里说的不是实例，假设，订单中心，售后中心等等不同的微服务，怎么区分。说的是这个问题。

**Comment by xiangHannibal** [comment]
> > ![40d72146866c06c71ac84341e21dfc6](https://user-images.githubusercontent.com/11513436/146637769-ef07cc9e-137b-4afd-bc17-cb18f1ded623.png) ![198f17dc3feceb7462bdaa410f1a4e8](https://user-images.githubusercontent.com/11513436/146637779-ffd8e008-be8a-4c36-b54b-d8d0b8716289.png) ![b517e5f4b0a4717ff9f5e8b8e5bf052](https://user-images.githubusercontent.com/11513436/146637782-6560bef5-96c3-4a8b-afb5-c7d880ab2e6b.png)
> > you can read nacos:https://nacos.io/zh-cn/docs/sdk.html, then run example.
> 
> 这样的方式是只能在nacos注册一个微服务，其他所有的实例都在这一个微服务下。实际上，微服务不止一个，这里说的不是实例，假设，订单中心，售后中心等等不同的微服务，怎么区分。说的是这个问题。

![image](https://user-images.githubusercontent.com/6896623/147619262-0838db62-30c8-40c6-8618-a1491500ad17.png)

nacos是要注册这样的显示多个微服务，然后每个微服务下面有多个实例。
