### ISSUE TITLE
springmvc startup error

### ISSUE THREAD

**Issue by bootstrap2025** [apache/incubator-shenyu#2512]
### Question

![image](https://user-images.githubusercontent.com/9637974/144469190-f95ad6d1-b911-46ff-ad22-7b66a5be23f4.png)
When starting the service in springmvc mode, my xml file shows that the constructor is missing one parameter，
and The following error is reported when the service starts：
![image](https://user-images.githubusercontent.com/9637974/144469606-fb6ad1a2-4d1a-4f55-8bca-fa71e503bfe9.png)
Is this the document problem?

**Comment by AhahaGe** [comment]
Please provide more information, which version, what's your steps, thanks.

**Comment by bootstrap2025** [comment]
![image](https://user-images.githubusercontent.com/9637974/144537029-bf5909ce-e169-4591-ac4c-cb29ca11a0e9.png)
When building an http proxy according to your documentation, the springmvc project will report this error at startup
The version number is ```2.4.1```

**Comment by yu199195** [comment]
maybe doc have error， pls see example config

**Comment by bootstrap2025** [comment]
There is no springMVC example, only springboot

**Comment by yu199195** [comment]
can you convert springboot yaml configuration to spring xml

**Comment by AhahaGe** [comment]
![image](https://user-images.githubusercontent.com/6198217/144560294-ec914bd3-2133-436f-a3c5-0f16807f4936.png)
doc don't contain the config of ShenyuClientRegisterRepository, maybe this is the reason lead to your error, as in springboot most of the bean are auto created by configuration. 
![image](https://user-images.githubusercontent.com/6198217/144560517-47f2dc05-9d50-407e-848a-820e925baf40.png)
So, I suggest u may need to config ShenyuClientRegisterRepository according to source code manully and retry.

**Comment by yu199195** [comment]
@AhahaGe  you can modify spring mvc doc，

**Comment by AhahaGe** [comment]
provide no-springboot-springmvc example code, or provide another no-springboot-springmvc-client?

**Comment by bootstrap2025** [comment]
Where should I manually configure this bean @AhahaGe

**Comment by AhahaGe** [comment]
This problem need four pr:
1. add constructor for clientRepository finished
2. edit 2.4.1 document
3. add springmvc demo
4. current document add mvc document
