### ISSUE TITLE
[Question] Maybe these Class should be deleted

### ISSUE THREAD

**Issue by li-keguo** [apache/incubator-shenyu#2513]
### Question

I find Class never used， These classes should probably be deleted

- shenyu-common
  - [ ] org.apache.shenyu.common.utils.ThreadShare : only UT used
  - [ ] org.apache.shenyu.common.utils.ThreadShareUtils : no used
  - [ ] org.apache.shenyu.common.utils.SpiLoadFactory : only UT used
- shenyu-examples
  - [ ] org.apache.shenyu.examples.http.result.PaymentTypeService :  no used
- Shenyu-web
  - [ ] org.apache.shenyu.web.filter.AbstractWebFilter:  no used

**Comment by yu199195** [comment]
only PaymentTypeService can remove
