### ISSUE TITLE
[Task:feature]  < improve and extend ShenyuException> add some concrete exceptions

### ISSUE THREAD

**Issue by damonxue** [apache/incubator-shenyu#2523]
### Description

There are only the ShenyuException and the ShenyuGrpcException, In order to understand the real and specific abnormal conditions, we need to improve and extend ShenyuException System with adding concrete exceptions.

### Task List

- [ x ] read the Contribution Guideline

**Comment by YanHui-Yang** [comment]
please asign to me.

**Comment by damonxue** [comment]
> please asign to me.

@yu199195 pls asign to us.
