### ISSUE TITLE
[Question]  if client http server is down , how does shenyu find and remove UPSTREAM_MAP_TEMP

### ISSUE THREAD

**Issue by MiniSC** [apache/incubator-shenyu#2538]
### Question

What mechanisms can check client server is down and remove ip from UPSTREAM_MAP_TEMP
i only find  [shenyu.upstream.check] can start a Schedule task to find ip not work and remove it

**Comment by yu199195** [comment]
if used http register，just like you say.   you can used other register type such as zookeeper , etcd ...
