### ISSUE TITLE
[Question] Duplicate metaData，version-2.4.0，Is this a bug or it has been fixed

### ISSUE THREAD

**Issue by 3813g00c** [apache/incubator-shenyu#2541]
### Question

![image](https://user-images.githubusercontent.com/33142631/144955463-2066e95d-9770-4f82-8232-b3858669ee39.png)

in database，the two same metaData createTime and updateTime is same

![image](https://user-images.githubusercontent.com/33142631/144960167-6cbf4fbf-8b29-4058-b19b-d9a877435f18.png)

**Comment by yu199195** [comment]
pls in english

**Comment by yu199195** [comment]
2.0.4 is soul ？  if spring cloud have two， pls remove it

**Comment by 3813g00c** [comment]
version is 2.0.4，Spring cloud plugin is only one

**Comment by yu199195** [comment]
in multiple environments?  used same db ?

**Comment by 3813g00c** [comment]
no，We have 6 environments，They are independent，but every env has same problem

**Comment by xxxQi** [comment]
已收到，谢谢。

**Comment by 3813g00c** [comment]
![image](https://user-images.githubusercontent.com/33142631/144999682-db32ca2c-628e-4745-9d9b-ac099a548145.png)
synchronized and @Transactional(rollbackFor = Exception.class)

**Comment by yu199195** [comment]
this is  2.4.1 ， you can try

**Comment by midnight2104** [comment]
Hi, does this question still exist? If there is still a problem, please resubmit the issue.
