### ISSUE TITLE
[BUG] resource data path is duplicate

### ISSUE THREAD

**Issue by sinlang** [apache/incubator-shenyu#2544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/4089994/145128676-e43b92dc-2ee4-4e97-aa20-6400267e3504.png)

### Expected Behavior

only on record /http/order/findById

### Environment

```markdown
ShenYu version(s):2.4.1
```

### Debug logs

dd

### Anything else?

d

**Comment by yu199195** [comment]
`/http/order/findById` in shenyu-admin have two？

**Comment by Zhoutzzz** [comment]
In latest version,I can't repetition this question,is your config have two same path?

**Comment by hutaishi** [comment]
![图片](https://user-images.githubusercontent.com/12478263/151145237-2edff63e-638c-4286-835d-81f654e05b77.png)
Is it possible that two servers have been started？

**Comment by midnight2104** [comment]
Hi, does this question still exist? If there is still a problem, please resubmit the issue.
