### ISSUE TITLE
[BUG] WebFluxResultUtils shenyuResult the last request result was not cleared

### ISSUE THREAD

**Issue by janusdo** [apache/incubator-shenyu#2578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the second request error, the data value is the last response data, WebFluxResultUtils shenyuResult the last request result was not cleared.

First request result
{
	"code": 200,
	"data": {
		"id": "4c73bc08-bdf3-46d8-ba6c-1b5175ec57d1"
	},
	"requestId": "b488575b-9315-4266-91be-d2d69d171af0",
	"message": "Success!"
}

Second request result
{
	"code": 400,
	"data": {
		"id": "4c73bc08-bdf3-46d8-ba6c-1b5175ec57d1"
	},
	"requestId": "e86ecfde-34c6-44fb-8b34-c4261688025e",
	"message": "Sign is not pass!"
}

How to customize sorting by code, message, requestid and data？

Thanks!

### Expected Behavior

Second request result
{
	"code": 400,
	"message": "Sign is not pass!",
	"requestId": "e86ecfde-34c6-44fb-8b34-c4261688025e"
}

### Environment

```markdown
ShenYu version(s): 2.4.1
```

**Comment by yu199195** [comment]
this is result by shenyu? 

```
{
"code": 400,
"data": {
"id": "4c73bc08-bdf3-46d8-ba6c-1b5175ec57d1"
},
"requestId": "e86ecfde-34c6-44fb-8b34-c4261688025e",
"message": "Sign is not pass!"
}
```

**Comment by qicz** [comment]
maybe this data is not from shenyu, shenyu response contains not the request id. @janusdo

**Comment by janusdo** [comment]
requestId is my custom attribute. A unique ID is generated for each request. 

When calling WebFluxResultUtils.result, If result is error, shenyResult.clear() Is not called.

**Comment by qicz** [comment]
> requestId is my custom attribute. A unique ID is generated for each request.
> 
> When calling WebFluxResultUtils.result, If result is error, shenyResult.clear() Is not called.

2.4.1 or last version from master ?

**Comment by janusdo** [comment]
last version from master

**Comment by qicz** [comment]
> last version from master

Do you use the `put` function to add data?

**Comment by janusdo** [comment]
yes, use put function to add data. When the result is JSON，the map is not reset.

**Comment by qicz** [comment]
I have been already fixed this bug. You can wait for the merge and try again.

**Comment by qicz** [comment]
@janusdo After discussion, we decided to transform this feature and open up the format of the data for users to customize according to the situation.
