### ISSUE TITLE
[BUG] abnormal return of file request. serious

### ISSUE THREAD

**Issue by MarsOu1995** [apache/incubator-shenyu#2611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Service A provides a file / picture download.
shenyu-gateway return is an abnormal file character stream.

### Expected Behavior

shenyu-gateway will return file stream.

### Environment

```markdown
ShenYu version(s):2.4.2
```

### Debug logs

I don't think the file return should be converted to string.
![2bd8426e997b362e5150ed966bb71d7](https://user-images.githubusercontent.com/20200721/146521142-a0846b4c-7f82-4385-be16-78764798293b.png)
![60f718a0ec7ac6a7d8107b955e78dd1](https://user-images.githubusercontent.com/20200721/146521339-5209764c-ed2f-4c25-b271-728ed1964271.png)

**Comment by impactCn** [comment]
I can fix this problem.

**Comment by impactCn** [comment]
Can you provide responseHeader?
