### ISSUE TITLE
feature shenyu-plugin-response : support raw HttpStatus forwarding

### ISSUE THREAD

**Issue by xuetao0** [apache/incubator-shenyu#2614]
### Question

Raw HttpStatus forwarding is not supported in shenyu-plugin-response.
I want to support this feature. Just like Spring Cloud Gateway.

**Comment by qicz** [comment]
master was support. you can see this https://shenyu.apache.org/docs/next/developer/custom-result/

**Comment by xuetao0** [comment]
not custom response.
is source server return's status

**Comment by qicz** [comment]
> not custom response. is source server return's status

the exchange can get the `client response`.

**Comment by qicz** [comment]
I’ll close this issue first, and if you have any questions, please contact me again
@xuetao0
