### ISSUE TITLE
[BUG] <Type definitions of ‘SentinelHandle.degradeRuleCount’ and 'Sentinel DegradeRule.count ' are inconsistent.>

### ISSUE THREAD

**Issue by pmgcat** [apache/incubator-shenyu#2618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the DegradeRule grade is ‘EXCEPTION_RATIO’, its value cannot be set to the corresponding ratio value.When the DegradeRule grade is ‘EXCEPTION_RATIO’, its value cannot be set to the corresponding ratio value.

### Environment

```markdown
ShenYu version(s): 2.4.1
```

**Comment by yu199195** [comment]
can you fix it，

**Comment by pmgcat** [comment]
OK, I'll try.
