### ISSUE TITLE
can dividePlugin support to retry  another upstream but not retry only on one upstream  ,when is fail .

### ISSUE THREAD

**Issue by yuzhijia88** [apache/incubator-shenyu#2627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
ShenYu version(s): 2.4.1
```

**Comment by yu199195** [comment]
yes， support all upstream

**Comment by dragon-zhang** [comment]
For example, there are 3 upstreams like `http://localhost:1111`、`http://localhost:1112` and `http://localhost:1113`, when call `http://localhost:1111` fails, I think he means to call `http://localhost:1112` or `http://localhost:1113` for retry, not just call `http://localhost:1111` for retry, don't you ? @yuzhijia88

**Comment by yuzhijia88** [comment]
> For example, there are 3 upstreams like `http://localhost:1111`、`http://localhost:1112` and `http://localhost:1113`, when call `http://localhost:1111` fails, I think he means to call `http://localhost:1112` or `http://localhost:1113` for retry, not just call `http://localhost:1111` for retry, don't you ? @yuzhijia88

yes

**Comment by dragon-zhang** [comment]
> > For example, there are 3 upstreams like `http://localhost:1111`、`http://localhost:1112` and `http://localhost:1113`, when call `http://localhost:1111` fails, I think he means to call `http://localhost:1112` or `http://localhost:1113` for retry, not just call `http://localhost:1111` for retry, don't you ? @yuzhijia88
> 
> yes

It can be done and if it done, you need to add some config for `DividePlugin`(in order to be compatible with the old version of `DividePlugin`), can you accept it ?

**Comment by yuzhijia88** [comment]
> > > For example, there are 3 upstreams like `http://localhost:1111`、`http://localhost:1112` and `http://localhost:1113`, when call `http://localhost:1111` fails, I think he means to call `http://localhost:1112` or `http://localhost:1113` for retry, not just call `http://localhost:1111` for retry, don't you ? @yuzhijia88
> > 
> > 
> > yes
> 
> It can be done and if it done, you need to add some config for `DividePlugin`(in order to be compatible with the old version of `DividePlugin`), can you accept it ?

yes

**Comment by dragon-zhang** [comment]
> > > > For example, there are 3 upstreams like `http://localhost:1111`、`http://localhost:1112` and `http://localhost:1113`, when call `http://localhost:1111` fails, I think he means to call `http://localhost:1112` or `http://localhost:1113` for retry, not just call `http://localhost:1111` for retry, don't you ? @yuzhijia88
> > > 
> > > 
> > > yes
> > 
> > 
> > It can be done and if it done, you need to add some config for `DividePlugin`(in order to be compatible with the old version of `DividePlugin`), can you accept it ?
> 
> yes

Ok, I'll take care of it.

**Comment by dragon-zhang** [comment]
And I think it's not a `bug` but a `new feature`.

**Comment by dragon-zhang** [comment]
All job done, you can try it in `master` branch now, @yuzhijia88 

you can test by these steps:
1. run `ShenyuAdminBootstrap`;
2. run `ShenyuTestHttpApplication`;
3. visit `http://localhost:9095` and change retry strategy to `failover`;
4. run `ShenyuBootstrapApplication`;
5. send post request
```http
POST http://localhost:9195/http/shenyu/client/timeout
Accept: application/json
Content-Type: application/json
```
then you can see the correct result.

**Comment by dragon-zhang** [comment]
@yuzhijia88 please close this issue.

**Comment by yuzhijia88** [comment]
perfect
