### ISSUE TITLE
[Question] <Is it possible to add strategy attributes in HttpClientProperties.java?>

### ISSUE THREAD

**Issue by OnlyQuiet** [apache/incubator-shenyu#2673]
### Question

Browse the configuration file more clearly.
before
![image](https://user-images.githubusercontent.com/41868553/147619856-cd96a026-90b3-4ef7-b98a-045b0c7ecd13.png)
after
![image](https://user-images.githubusercontent.com/41868553/147620131-8087a4c3-f058-4b1c-92df-701d06ba399a.png)

**Comment by yu199195** [comment]
you can see this ： https://shenyu.apache.org/zh/docs/next/user-guide/property-config/gateway-property-config/
