### ISSUE TITLE
[Task] <Check doc of apache dubbo xml whether valid for v2.4.1 and v2.4.0>

### ISSUE THREAD

**Issue by AhahaGe** [apache/incubator-shenyu#2685]
### Description

Check doc of apache dubbo xml whether valid for v2.4.1 and v2.4.0.
And if v2.4.1 and v2.4.0 should use previous version's doc. 

### Task List

- [x] 1. v2.4.1
- [x] 2. v2.4.0

**Comment by AhahaGe** [comment]
please assign to me

**Comment by yu199195** [comment]
good job

**Comment by AhahaGe** [comment]
Both are not valid, this is a related issue. #1262

**Comment by AhahaGe** [comment]
Finished check.
