### ISSUE TITLE
拉取最新代码模块调整pom中模块没有去掉

### ISSUE THREAD

**Issue by qinliang373** [apache/incubator-shenyu#2692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

拉取最新代码模块调整pom中模块没有去掉

### Expected Behavior

![图片](https://user-images.githubusercontent.com/39186613/147852542-bbdf5f7e-da35-4312-938e-802dd5d142d2.png)

### Environment

```markdown
ShenYu version(s):
```

**Comment by yu199195** [comment]
why remove？ pls in english

**Comment by qinliang373** [comment]
There is no corresponding module under the parent POM。this is lastest master branch
![图片](https://user-images.githubusercontent.com/39186613/147867285-35e3b15d-730f-4334-acc7-3b63fd0ccf32.png)

**Comment by yu199195** [comment]
can you modify this issue title?

more plugin，you can not clone success,  you can see this : https://shenyu.apache.org/community/faq
