### ISSUE TITLE
[Question] <How to set sentinel fallbackUri?>

### ISSUE THREAD

**Issue by OnlyQuiet** [apache/incubator-shenyu#2700]
### Question

version：master

The configuration is as follows, fallbackUri = 'http://localhost:9195/http/test/payment'
![image](https://user-images.githubusercontent.com/41868553/148016535-1eb73fdc-c457-4530-a192-493ec27e76cf.png)

Response
![image](https://user-images.githubusercontent.com/41868553/148016725-01c898e5-adad-4874-84fc-8c91c702a4bc.png)

**Comment by yu199195** [comment]
>'http://localhost:9195/http/test/payment'

have this controller  in 9195?

**Comment by OnlyQuiet** [comment]
omg, i get it. Thanks
