### ISSUE TITLE
[Question] <apache shenyu blog Modify the style>

### ISSUE THREAD

**Issue by gaochuang98** [apache/incubator-shenyu#2726]
### Question

![0882e8ffd0d626eede61f772adf8cb2](https://user-images.githubusercontent.com/49777877/148481911-b1ec0a91-5c58-4b2a-9f36-2b4383f39caa.png)
Can anyone remove these shadows ？
It is not friendly to the eyes to use

**Comment by gaochuang98** [comment]
https://shenyu.apache.org/blog

**Comment by yu199195** [comment]
@gaochuang98  can you help this ？

**Comment by gaochuang98** [comment]
sure,what should I do

**Comment by yu199195** [comment]
you can see this ： https://github.com/apache/incubator-shenyu-website

> sure,what should I do ,but this is in https://shenyu.apache.org/zh/blog/ I do not know where it is
