### ISSUE TITLE
[Task] Add integrated test for zipkin plugin

### ISSUE THREAD

**Issue by JooKS-me** [apache/incubator-shenyu#2739]
### Description

Hi community,
The [tracing-zipkin-plugin](https://shenyu.apache.org/docs/next/user-guide/observability/tracing/#agent-plugin-tracing-zipkin) in `shenyu-agent` has been completed.

And then, we need add integrated test for zipkin plugin.

If you want to take this task, you can comment in this issue.

It might be a little difficult, but you can refer to this [the it of otel plugin](https://github.com/apache/incubator-shenyu/pull/2718)

### Task List

- [ ] Add integrated test for zipkin plugin

Ref #2699 .

**Comment by LeeGuoPing** [comment]
May I have a try?

**Comment by yu199195** [comment]
@LeeGuoPing Of course you can,  you can see this : https://shenyu.apache.org/community/

**Comment by LeeGuoPing** [comment]
I met some trouble, how to write docker-compose.yml. Can you give me some advice @JooKS-me 
![image](https://user-images.githubusercontent.com/35389145/149295135-ea49e6db-347b-4a4a-a19b-b153e6d1a13c.png)
<img width="1395" alt="微信截图_20220113163949" src="https://user-images.githubusercontent.com/35389145/149295417-31fd9c71-d8b7-4b23-8b6d-0043905927b5.png">

**Comment by JooKS-me** [comment]
@LeeGuoPing Hi, before we start integrated image such as `apache/shenyu-integrated-test-agent-tracing-opentelemetry:latest`, we should build the image first. And the is a `Dockerfile` in the same directory of docker-compose.yml, we should build it first.

By the way, you can refer to [Run Integration Test Locally](https://shenyu.apache.org/community/integration-test)

**Comment by LeeGuoPing** [comment]
> @LeeGuoPing Hi, before we start integrated image such as `apache/shenyu-integrated-test-agent-tracing-opentelemetry:latest`, we should build the image first. And the is a `Dockerfile` in the same directory of docker-compose.yml, we should build it first.
> 
> By the way, you can refer to [Run Integration Test Locally](https://shenyu.apache.org/community/integration-test)

oh, thank you for your reply. why the image named jaegertracing/all-in-one:lastest. I saw your issue #2718, the issue is about opentelemetry. And I don't find other code `jaegertracing/all-in-one:lastes` in the project @JooKS-me

**Comment by JooKS-me** [comment]
> oh, thank you for your reply. why the image named jaegertracing/all-in-one:lastest. I saw your issue #2718, the issue is about opentelemetry. And I don't find other code `jaegertracing/all-in-one:lastes` in the project @JooKS-me

[Opentelemetry](https://opentelemetry.io/docs/) can export traces data to both jaeger and zipkin, but it does not store or display data itself.

**Comment by LeeGuoPing** [comment]
> > oh, thank you for your reply. why the image named jaegertracing/all-in-one:lastest. I saw your issue #2718, the issue is about opentelemetry. And I don't find other code `jaegertracing/all-in-one:lastes` in the project @JooKS-me
> 
> [Opentelemetry](https://opentelemetry.io/docs/) can export traces data to both jaeger and zipkin, but it does not store or display data itself.
> 
> And to use, you can see [our document](https://shenyu.apache.org/docs/next/user-guide/observability/tracing)

ok,I will try again.

**Comment by lxl910128** [comment]
I fixed it
