### ISSUE TITLE
[BUG] <Sentinel Plugin-exception number is not effective>

### ISSUE THREAD

**Issue by yunlongn** [apache/incubator-shenyu#2743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My Configuration:
![image](https://user-images.githubusercontent.com/38271111/148741148-7b4486c7-cc2b-4a30-8626-b679ff6369d1.png)

request http://localhost:9195/order/findById?id=3 
![image](https://user-images.githubusercontent.com/38271111/148741301-1bbc86d9-a8a1-4901-9c20-c5746b7a06c9.png)

request  http://localhost:9195/order/findById 
![image](https://user-images.githubusercontent.com/38271111/148741350-0665117d-34ff-4226-9501-2675575ce8fa.png)

http://localhost:9195/order/findById status code is abnormal, sentinel should trigger the number of times to downgrade.  
But the result is not so

### Expected Behavior

http://localhost:9195/order/findById 
reslut {"code":-103,"message":"Service invocation exception, or no result is returned!","data":null}

### Steps To Reproduce

start the service
![image](https://user-images.githubusercontent.com/38271111/148741904-d69d92cf-bb2b-4c41-a0ff-1c2c7beb9b9c.png)
configure divide
![image](https://user-images.githubusercontent.com/38271111/148742140-250d342c-39e9-478c-b875-7095e837606a.png)
![image](https://user-images.githubusercontent.com/38271111/148742164-bcb40966-231d-49f8-80de-089e9033c0d9.png)
open sentinel
![image](https://user-images.githubusercontent.com/38271111/148742211-932cc76b-0114-4f10-8700-867551a0b18f.png)
configure sentinel
![image](https://user-images.githubusercontent.com/38271111/148742268-12bf0696-9197-4e64-8085-e8e00b065ce9.png)

request http://localhost:9195/order/findById

### Environment

```markdown
ShenYu version(s): 2.4.0
```

### Anything else?

find a workable way  

modify WebClientPlugin

![image](https://user-images.githubusercontent.com/38271111/148742520-aeb3764c-51cb-4e9d-9e3a-c33c9d0dd851.png)

modify SentinelFallbackHandler
![image](https://user-images.githubusercontent.com/38271111/148742763-6a5683a3-244d-4d15-8907-d4ffdba583cc.png)

try requesting again http://localhost:9195/order/findById 
Trigger downgrade when abnormal number of times is reached

**Comment by yu199195** [comment]
> Trigger downgrade when abnormal number of times is reached
 
I'm a little confused as to what you mean, does the plugin meet your expectations, and if not, can you fix it
Because the official website shows that you need to have the English document first, and then the Chinese document, so you also need to make up the English document, inside your pr this time

**Comment by yunlongn** [comment]
![image](https://user-images.githubusercontent.com/38271111/148744116-f46b4c73-de1e-49b2-bbe8-0fbad7f4a1f6.png)

The return status of the application that forwards the call is 500. The number of exceptions is not currently recorded.

**Comment by yunlongn** [comment]
![image](https://user-images.githubusercontent.com/38271111/148744684-8ee26c37-6f7b-4108-8284-5718936dbb19.png)
Status code 500 returned by the app service. Shouldn't it be an exception? Due to the above code, the downgrade policy is not triggered. It looks like the processing of the status code is ignored here

**Comment by SaberSola** [comment]
Hi,brother,thanks for you issue,Sentinel triggering fuse must rely on the exception mechanism,I will fix this problem in the next two days。

**Comment by yunlongn** [comment]
Thanks, looking forward to your solution
