### ISSUE TITLE
[BUG] <If you use nacos data synchronization, the registration fails and the registration is still successful>

### ISSUE THREAD

**Issue by gaochuang98** [apache/incubator-shenyu#2783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you use nacos data synchronization, the registration fails and the registration is still successful

### Expected Behavior

I want to modify other registry logs
Make it as elegant to use as
`HttpClientRegisterRepository`

### Steps To Reproduce

look #issue 2710

### Environment

```markdown
ShenYu version(s):master
```

**Comment by gaochuang98** [comment]
please assign it to me

**Comment by KevinClair** [comment]
Duplicate of #2710
