### ISSUE TITLE
[Question] <title> what effects dose divide Plugin Configuration  item multiSelectorHandle and multiRuleHandle make

### ISSUE THREAD

**Issue by qingchunchencheng** [apache/incubator-shenyu#2800]
### Question

what does divide Plugin Configuration  item multiSelectorHandle and multiRuleHandle value mean?
please give Example For this
![1](https://user-images.githubusercontent.com/52264692/150295994-684e52e3-ceaa-4449-949a-36885fdd21e5.png)

**Comment by KevinClair** [comment]
It will affect the style of selector and rule.

**Comment by qingchunchencheng** [comment]
> It will affect the style of selector and rule.
 a little more specific? some example or where the code take effect
@KevinClair

**Comment by KevinClair** [comment]
see divide plugin, then choose single or multiple and reload page, you will find the difference.

**Comment by qingchunchencheng** [comment]
> 
I try to change the value and reload page  repeatly, but do not find  any difference 
@KevinClair

**Comment by qingchunchencheng** [comment]
> see divide plugin, then choose single or multiple and reload page, you will find the difference.

I try to change the value and reload page repeatly, but do not find any difference
please give more tips

**Comment by qingchunchencheng** [comment]
> see divide plugin, then choose single or multiple and reload page, you will find the difference.

I try to change the value and reload page repeatly, but do not find any difference
please give more tips
@KevinClair

**Comment by ClippersAnthony** [comment]
if you choose single handle(multiSelectorHandle),you'll find you can't add more than one handler when you modify the selector.

**Comment by qingchunchencheng** [comment]
> if you choose single handle(multiSelectorHandle),you'll find you can't add more than one handler when you modify the selector.

Thanks
@ClippersAnthony
