### ISSUE TITLE
[refactor shenyu-disruptor] <DisruptorProvider#onData(final Consumer<DataEvent<T>> function) has a bug> 

### ISSUE THREAD

**Issue by hutaishi** [apache/incubator-shenyu#2803]
### Description

DisruptorProvider#onData(final Consumer<DataEvent<T>> function) has a bug.
![图片](https://user-images.githubusercontent.com/12478263/150738256-0b08417d-09a1-4221-9ff4-1ccfc40c4a3b.png)

tmpObj.getData() will get a null. And this method is @Deprecated and not called in anywhere.
I think should remove this method.

### Task List

1. delete method of  DisruptorProvider#onData(final Consumer<DataEvent<T>> function)

**Comment by yu199195** [comment]
onData(), Are you sure you don't have any place to use it?

**Comment by hutaishi** [comment]
yes, I sure.    we used is onData(final T data), but not use public void onData(final Consumer<DataEvent<T>> function) .
I search globally and compiled.
