### ISSUE TITLE
[BUG] shenyu-bootstrap-dist missing agent parameter  in start.bat script

### ISSUE THREAD

**Issue by IceFoxs** [apache/incubator-shenyu#2814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/26451038/151137638-afdf5f4b-17e6-4b0d-9328-4187d5ba653d.png)

![image](https://user-images.githubusercontent.com/26451038/151138279-a36be8f3-3f41-4b30-b627-89aeb33a65e1.png)

### Expected Behavior

./start.bat agent   do work well

### Environment

```markdown
ShenYu version(s):2.4.2
```

**Comment by JooKS-me** [comment]
@IceFoxs Hi, can you help to submit a pr to support this?

**Comment by IceFoxs** [comment]
> @IceFoxs Hi, can you help to submit a pr to support this?

I fix it ，pls check it
