### ISSUE TITLE
[Question] Compatibility needs to be improved

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#2818]
### Question

cn
最近我想推动公司人员升级网关，因为我们公司使用的是旧版本的网关(还叫`soul`的版本)，升级到新版本的`shenyu`需要很大的工作量。我们能像Dubbo一样兼容吗？例如，`Dubbo`的软件包名在捐赠给`apache`之前是`alibaba`，在捐赠给`apache`后，包名改为`apache`，但它仍然与`alibaba`包名的注解和方法兼容。
en
Recently, I want to push the company's people to upgrade the gateway. Because our company uses an older version of the gateway (also known as the `soul` version), upgrading to the new version of `shenyu `has a lot of workload. Can we be as compatible as `Dubbo`? For example, the package name of `Dubbo` was `alibaba` before it was donated to `apache.` After it was donated to `apache`, the package name was changed to `apache`, but it is still compatible with the annotation and method of `alibaba` package name.

**Comment by dragon-zhang** [comment]
cn
另外，为了方便以后的升级，我们能否像`istio`一样，弄一个`sidecar`？
en
In addition, in order to facilitate future upgrades, can we get a `sidecar` like `istio`?

**Comment by yu199195** [comment]
To upgrade, you just need to redeploy, admin may involve data migration

**Comment by dragon-zhang** [comment]
The workload of `data migration` is not large, but it is laborious to promote the upgrade of 'client-sdks'

**Comment by yu199195** [comment]
> shenyu-client ?

It is not required, BTW, your company is register in

**Comment by dragon-zhang** [comment]
These `client-sdks` still send `post` request to `/soul-client/springmvc-register`、`/soul-client/springcloud-register`、`/soul-client/dubbo-register`

**Comment by dragon-zhang** [comment]
> > shenyu-client ?
> 
> It is not required, BTW, your company is register in #68

Already registered

**Comment by dragon-zhang** [comment]
cn
对了，之前是不是已经出过兼容版本了？
en
By the way, has there been a compatible version before?

**Comment by dragon-zhang** [comment]
see https://github.com/apache/incubator-shenyu/pull/2844
