### ISSUE TITLE
[BUG] <Double the amount of logs output>

### ISSUE THREAD

**Issue by impactCn** [apache/incubator-shenyu#2831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We currently have around 500,000 DAU and around 2 million MAU.
The output out file is not packed and compressed for logs, which can easily cause the server storage memory to be full.

![image](https://user-images.githubusercontent.com/35489877/152911665-127aeeb5-4703-4105-a21b-73c4284f2e45.png)

so.
![image](https://user-images.githubusercontent.com/35489877/152911759-96773117-742b-42df-b0e6-08d28a35fcb2.png)

I think it's best not to output logs here.

### Environment

```markdown
ShenYu version(s):
```

**Comment by yu199195** [comment]
can refactor to

**Comment by tuohai666** [comment]
This problem was introduced by this issue https://github.com/apache/incubator-shenyu/issues/2341 to solve a problem in container. Please go through that issue then make a fix.
Any suggestion? @impactCn @civism

**Comment by impactCn** [comment]
I think that when using the nohup command, the redirected logs can be controlled without output and can be controlled by logback. What I'm currently using inside the container is valid.

This is my pr. #2839

**Comment by tuohai666** [comment]
Hi @impactCn ,
What do does it mean when using inside the container? Are the logs in the right place?

**Comment by impactCn** [comment]
> Hi @impactCn , What do does it mean when using inside the container? Are the logs in the right place?

![image](https://user-images.githubusercontent.com/35489877/153155502-2506dfac-6c8a-4ba3-9b94-4f0b5d0fda65.png)
I pull the latest image of shenyu bootstrap. It is found that there are duplicate logs. Then I modified the start.sh script directly in the container to test. It is found that modifying to `/dev/null` can only output it once.

and logs is right place.

**Comment by tuohai666** [comment]
@impactCn I'd suggest that remove the logs dir before run the modified script. If you have already read the https://github.com/apache/incubator-shenyu/issues/2341 and https://github.com/apache/incubator-shenyu/pull/2345/files , you will find when there's no log file the tail action will fail.
