### ISSUE TITLE
[BUG] <start.sh>  shell error

### ISSUE THREAD

**Issue by lzqdename** [apache/incubator-shenyu#2836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

on the same comuter
if you start bootstarp ,and then start admin
admin will report error " 
ERROR: The ShenYu-Admin already started!
PID: 1347029
1347041
"
---
there is a error about shell script in start.sh
PIDS=`ps -ef | grep "$DEPLOY_DIR" | grep -v grep | pgrep -f java`

if u start any java procedure already, this script will get all java pids
I think the right script should be 
PIDS=`ps -ef | grep "$DEPLOY_DIR" | grep -v grep | awk '{print $2}'`

if the bug is true,u can check the shell command in both bootstrap and admin

### Expected Behavior

the admin should be started normally

### Environment

```markdown
ShenYu version(s):2.4.2
```

**Comment by tuohai666** [comment]
I have reproduced this problem. It was introduced by this issue https://github.com/apache/incubator-shenyu/issues/2338 to solve a problem in container.
Change the `pgrep -f java` to` awk '{print $2}'` will make the script work in host machine but fail in container.
Any suggestion? @lzqdename @lahmXu

**Comment by lahmXu** [comment]
> I have reproduced this problem. It was introduced by this issue #2338 to solve a problem in container. Change the `pgrep -f java` to` awk '{print $2}'` will make the script work in host machine but fail in container. Any suggestion? @lzqdename @lahmXu

I tried to modify the `start.sh` and `stop.sh` under the directory of `apache-shenyu-incubating-2.4.2-bootstrap-bin/bin/` and `apache-shenyu-incubating-2.4.2-admin-bin/bin/`, a total of 4 files need to be modified. as shown below
```shell
change 
PIDS=`ps -ef | grep "$DEPLOY_DIR" | grep -v grep | pgrep -f java`
to 
PIDS=`ps -eo pid,cmd |grep -v tail|grep -v grep|grep "$DEPLOY_DIR"|awk '{print $1}'`
```
specify the order of PID and it worked.

## Test Result
### Linux Server
![image-20220209135945113](https://user-images.githubusercontent.com/31627887/153133379-60c9430f-31a9-44f7-9f3e-83ba007fa716.png)


### Docker Container
#### Shenyu Admin
![image-20220209140925147](https://user-images.githubusercontent.com/31627887/153133280-bc3aad9f-713e-4c33-bed7-f4dc0203b609.png)

#### Shenyu Bootstrap
![image-20220209140624992](https://user-images.githubusercontent.com/31627887/153133222-2e02ddf6-996e-49cc-8422-c3747d5450ef.png)

**Comment by tuohai666** [comment]
Hi @lahmXu , I prefer your solution. Some details need to consider:

1. Remove the judgement in start.sh. If there's port conflicts, the process will failure automatically, we don't have to judge.
2. The change should be made in the stop.sh
3. Make sure Admin process will failure when the port conflicts.

**Comment by lahmXu** [comment]
> Hi @lahmXu , I prefer your solution. Some details need to consider:
> 
> 1. Remove the judgement in start.sh. If there's port conflicts, the process will failure automatically, we don't have to judge.
> 2. The change should be made in the stop.sh
> 3. Make sure Admin process will failure when the port conflicts.

ok, I will fix the problem as you say.
