### ISSUE TITLE
[Question] <Context_path plugin have practical significance for websocket? Not sure if it's a bug>

### ISSUE THREAD

**Issue by lianjunwei** [apache/incubator-shenyu#2840]
### Question

Background: I need to use the gateway proxy websocket in the project. I'm going to implement the automatic registration of websocket. During demo verification, it is found that the Context_path plugin has no practical effect on websocket. Not sure if it's a bug.

Detailed description: Context_path plugin is meaningful to the HTTP request of the divide proxy. Before the gateway really requests the downstream service, it will process the buildrealurl and remove the contextpath in the URL upstream of the gateway. The buildwsrealpath () method of Websocket plugin (websocketplugin. Java) does not modify the path in the upstream URL, and does not use the realurl in shenyucontext.

As shown below：
![websocket](https://user-images.githubusercontent.com/13819823/152955469-1ba79182-e054-4659-bc2e-818b73b85f1d.png)

The current request URL is: ws://172.22.193.11:8080/websocket-demo/n/webSocket/TOM .
The expected URL is: ws://172.22.193.11:8080/n/webSocket/TOM .

Is my expected result correct? Thank the kind-hearted person for answering?

**Comment by KevinClair** [comment]
Thanks for your reporting, i will check it later.

**Comment by lianjunwei** [comment]
> After the wechat community group asked xiaoyu, the problem is clear. Context_ path plugin doesn't handle websocket. I'll just add it. I'll mention PR later.

**Comment by lianjunwei** [comment]
1. If the contextpath plug-in is opened and the URL does not contain contextpath,  will throw NPE. If url contains contextpath, cannot access it.   
2.  so，is a bug。

**Comment by lianjunwei** [comment]
fixed and close .
