### ISSUE TITLE
[BUG] <when the size of response exceeds 256 * 1024,error happens>

### ISSUE THREAD

**Issue by lzqdename** [apache/incubator-shenyu#2846]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

when the size of response exceeds 256 * 1024,error happens

### Expected Behavior

the response is normal

### Environment

```markdown
ShenYu version(s):2.4.2
```

**Comment by lzqdename** [comment]
to fix it, we can add one config item as follows:
spring:
  codec:
      max-in-memory-size: 2MB

then user knows that this config can be adjusted

**Comment by yu199195** [comment]
can add in yaml， if you want to fix it

**Comment by lzqdename** [comment]
> can add in yaml， if you want to fix it

Okay, let me add it in yaml

**Comment by lzqdename** [comment]
the code has been merged into master branch, so I will close this issue!
