### ISSUE TITLE
[BUG] <admin can not be started if db type set to be mysql>

### ISSUE THREAD

**Issue by lzqdename** [apache/incubator-shenyu#2850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if db set to be mysql
admin project fails to start due to lackness of mysql driver
so ,I think u had better to add mysql / pg driver jars into the lib 
then users will start admin project without any trouble to increase user experience

### Environment

```markdown
ShenYu version(s):2.4.2
```

**Comment by yu199195** [comment]
hi， mysql lib， is not apache license， copy mysql-connector.jar to /$(your_work_dir)/ext-lib

**Comment by lzqdename** [comment]
> hi， mysql lib， is not apache license， copy mysql-connector.jar to /$(your_work_dir)/ext-lib

ok,so i will close this issue : )
