### ISSUE TITLE
[Volunteer]  Add log plugin for shenyu-agent

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2870]
### Volunteer help

Hi Community：

In the observability of shenyu, the log is very important. 

Now we should support log plugin in shenyu-agent.

Task List:

- [ ] add shenyu-agent-plugin-logging as parent pom.
- [ ] add add shenyu-agent-plugin-logging-rocketmq ，sending logs to rocketmq.

If you are interested, you can reply to the issue.

thanks~

**Comment by hutaishi** [comment]
I'm doing these two tasks. I will finish it no later than February 15.

Other interested partners are welcome to contribute other log plugins.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-shenyu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月13日(星期天) 中午1:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/incubator-shenyu] [Volunteer]  Add log plugin for shenyu-agent (Issue #2870)





 
I can try add plugin for send log to es.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hutaishi** [comment]
I submitted a pull request. Please help me review it. think

**Comment by midnight2104** [comment]
done
