### ISSUE TITLE
[BUG] SelectorServiceImpl Parameter Error

### ISSUE THREAD

**Issue by nf-nanfeng** [apache/incubator-shenyu#2878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the last of the method: org.apache.shenyu.admin.service.impl.SelectorServiceImpl#updateDivideUpstream
called this method: org.apache.shenyu.admin.service.impl.UpstreamCheckService#replace

What the interface(org.apache.shenyu.admin.service.impl.UpstreamCheckService#replace) need is selectorId, but actually gets selectorName, and this will prevent the invalid upstream which is added in web being removed.

### Expected Behavior

The invalid upstream added in web can be automatically removed

### Steps To Reproduce

1. start shenyu-admin.jar
2. create a DivideSelector and set a new upstream in web, for example: 192.168.1.125:8080
3. close 192.168.1.125:8080
4. the 192.168.1.125:8080 now is invalid and console has printed error, but this upstream is not removed

### Environment

```markdown
ShenYu version(s): 2.4.2
```

### Debug logs

![image](https://user-images.githubusercontent.com/54448899/153986848-63514571-5006-4b08-9b10-36a88bd8d2d3.png)
![image](https://user-images.githubusercontent.com/54448899/153986870-5c64dd06-358c-400e-8e49-70c31119dc5a.png)
![image](https://user-images.githubusercontent.com/54448899/153986979-8b770263-b031-4218-84bf-8cc93976d621.png)

**Comment by yu199195** [comment]
@nf-nanfeng 

hi，pls in english for issue， Thank you for your contribution. BTW，you can fix it？

**Comment by nf-nanfeng** [comment]
> 

sure, I will commit a PR later

**Comment by nf-nanfeng** [comment]
@yu199195 sure, I will commit a PR later

**Comment by yu199195** [comment]
it be fix ，i will close it， thanks
