### ISSUE TITLE
[Question] nacos data synchronization will lose config when restart shenyu-bootstrap

### ISSUE THREAD

**Issue by zengxp0605** [apache/incubator-shenyu#2879]
### Question

Using `nacos` data synchronization , when I change config on `shenyu-admin` web-console and click the button "Synchronous divide".  The nacos configurations data(dataId=`shenyu.selector.json`) just has one key `divide`.  The old keys like `context_path`,`sign` and `dubbo` are missing. 

In this case, I restarted `shenyu-bootstrap`, (maybe it crashed or scaled in k8s cluster), the new `shenyu-bootstrap` application can not get the full `selector` config from nacos.

The reason why I use `nacos` data synchronization is that I need to keep 2 pods in k8s of the application `shenyu-admin`. 
So I can't use `WebSocket Synchronization`.

ps: shenyu version is v2.4.1.

**Comment by yu199195** [comment]
it more big data，mybe~    BTW，you can try it！

**Comment by zengxp0605** [comment]
> 
 I think maybe it is a bug.


First I start `shenyu-admin`, Nacos data(dataId=shenyu.selector.json) is `{}`.

Then I start `shenyu-bootstrap`, and then `shenyu-examples-http`, 
at this time, Nacos data(dataId=shenyu.selector.json) content is `before.json`.

before.json(2 keys `context_path` and `divide`)
```before.json
{"context_path":[{"id":"1493839719350710272","pluginId":"14","pluginName":"context_path","name":"/http","matchMode":0,"type":1,"sort":1,"enabled":true,"logged":true,"continued":true,"conditionList":[{"paramType":"uri","operator":"match","paramName":"/","paramValue":"/http/**"}]}],"divide":[{"id":"1493839717828177920","pluginId":"5","pluginName":"divide","name":"/http","matchMode":0,"type":1,"sort":1,"enabled":true,"logged":true,"continued":true,"handle":"[{\"weight\":50,\"warmup\":10,\"protocol\":\"http://\",\"upstreamHost\":\"localhost\",\"upstreamUrl\":\"192.168.192.72:8189\",\"status\":true,\"timestamp\":1644994271878}]","conditionList":[{"paramType":"uri","operator":"match","paramName":"/","paramValue":"/http/**"}]}]}```
```

Now, I visit the url `"http://localhost:9195/http/test/findByUserId?userId=1234`, it works ok.

Then I add `context_path` config on `shenyu-admin` web-console, and click button `Synchronous context_path`, Nacos data(dataId=shenyu.selector.json) content becomes `after.json`.

after.json(just one key `context_path`)
```after.json
{"context_path":[{"id":"1493839719350710272","pluginId":"14","pluginName":"context_path","name":"/http","matchMode":0,"type":1,"sort":1,"enabled":true,"logged":true,"continued":true,"conditionList":[{"paramType":"uri","operator":"match","paramName":"/","paramValue":"/http/**"}]},{"id":"1493841747456077824","pluginId":"14","pluginName":"context_path","name":"/add/path","matchMode":0,"type":1,"sort":1,"enabled":true,"logged":true,"continued":true,"conditionList":[{"paramType":"uri","operator":"match","paramName":"/","paramValue":"/add/path"}]}]}
```

In this case, the `shenyu-bootstrap` application still works right, but when I restarted it, it can not work with the url `http://localhost:9195/http/test/findByUserId?userId=1234`. 
The reason is that Nacos config of `divide` is missing.

**Comment by zengxp0605** [comment]
The document on <https://shenyu.apache.org/docs/2.4.1/design/data-sync/#nacos-synchronization> says "When the sequential data send changes, it will update the configuration node in Nacos in full amount. "

But in fact, when I click button "Synchronous context_path" to synchronize data, the Nacos config is not full.

**Comment by KevinClair** [comment]
Hi @zengxp0605 , don't click button `Synchronous context_path` when you add config, then try it again.

**Comment by KevinClair** [comment]
I check the code, maybe it's a problem here.
![image](https://user-images.githubusercontent.com/37257651/154229550-dca66f6f-280a-4a06-a913-f9ba0068d9f7.png)

**Comment by zengxp0605** [comment]
> Hi @zengxp0605 , don't click button `Synchronous context_path` when you add config, then try it again.

I know I can add config and it can work. This problem was appeared after click the button `Synchronous context_path`. No one reminded me the button can not be used with `nacos` data synchronization.

**Comment by KevinClair** [comment]
> > Hi @zengxp0605 , don't click button `Synchronous context_path` when you add config, then try it again.
> 
> I know I can add config and it can work. This problem was appeared after click the button `Synchronous context_path`. No one reminded me the button can not be used with `nacos` data synchronization.

so, will you fix it?
