### ISSUE TITLE
[Question] How about adding an `IsolatePlugin` ?

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#2886]
### Question

With the increasing application of accessing `ShenYu`, hot applications and non hot applications will `interact` with each other, resulting in the problem of application avalanche.

To solve this problem, `IsolatePlugin` is introduced to isolate `shenyu-bootstrap` resources(such as memory, threads, etc).

Only `thread pool resource` is supported for the first version.

**Comment by yu199195** [comment]
@dragon-zhang  whats mean  to protection shenyu？

**Comment by dragon-zhang** [comment]
> 

When facing great pressure, it can make `shenyu-bootstrap` run more stably.

**Comment by yu199195** [comment]
>When facing great pressure, it can make shenyu-bootstrap run more stably.

Is there any difference between the hystrix plugin and resilience4j plugin~

**Comment by dragon-zhang** [comment]
These two plugins do not distinguish traffic, the traffic of hot applications can be affected by the traffic of non hot applications.



发自我的iPhone


------------------ Original ------------------
From: xiaoyu ***@***.***&gt;
Date: Wed,Feb 16,2022 6:14 PM
To: apache/incubator-shenyu ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/incubator-shenyu] [Question] How about adding an `IsolatePlugin` ? (Issue #2886)





  
When facing great pressure, it can make shenyu-bootstrap run more stably.
  
Is there any difference between the hystrix plugin and resilience4j plugin~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yu199195** [comment]
@dragon-zhang 

you can send eamil to dev@shenyu.apache.org, And Explain the principle and the solution，

Looking forward to your contribution~

**Comment by dragon-zhang** [comment]
> @dragon-zhang
> 
> you can send eamil to [dev@shenyu.apache.org](mailto:dev@shenyu.apache.org), And Explain the principle and the solution，
> 
> Looking forward to your contribution~

Sure, I will do it as soon as possible.

**Comment by dragon-zhang** [comment]
After reading `Concurrent Thread count` in https://sentinelguard.io/en-us/docs/flow-control.html carefully, I realize that `SentinelPlugin` has provided good support for this, and there is no need to add `IsolatePlugin`, so I will close this issue.
