### ISSUE TITLE
[BUG] The trouble of big data in Websocket.

### ISSUE THREAD

**Issue by HessTina-YuI** [apache/incubator-shenyu#2891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
ShenYu version(s): 2.4.2
```

**Comment by hutaishi** [comment]
Who is doing this? If not, please assign it to me.

**Comment by hutaishi** [comment]
the maximum value of inputMaxFrameSize is Integer.MAX_VALUE.
![图片](https://user-images.githubusercontent.com/12478263/154831138-77c802cd-866e-4e6a-8a07-1771e806a13f.png)
The maximum value of inputmaxframesize is 2147483647 bytes Under what circumstances will bigdata appear?

**Comment by yu199195** [comment]
@hutaishi  Looking forward to your pr~

**Comment by hutaishi** [comment]
> @hutaishi Looking forward to your pr~

I'm happy to do such an interesting thing

**Comment by hutaishi** [comment]
> @hutaishi Looking forward to your pr~

Hi, I have submitted a pr. if you are free, please check it for me. Thank you very much
