### ISSUE TITLE
[Volunteer] Add integration test for Hystrix plugin

### ISSUE THREAD

**Issue by JooKS-me** [apache/incubator-shenyu#2909]
### Volunteer help

- [ ] Add integration test for Hystrix plugin

We should test as many parameter configurations as possible.

**Comment by erdengk** [comment]
Hi，@JooKS-me
I want to try to solve this problem.
I don't know much about integration tests. I noticed a lot of related issues and PRs in the community. Maybe I can learn these issues and pr to solve this problem?

**Comment by JooKS-me** [comment]
You can refer to [the integration test of RateLimiterPluginTest](https://github.com/apache/incubator-shenyu/blob/master/shenyu-integrated-test/shenyu-integrated-test-http/src/test/java/org/apache/shenyu/integrated/test/http/combination/RateLimiterPluginTest.java), I think they are somewhat similar.

**Comment by erdengk** [comment]
@JooKS-me 
ok，thank you. I will try my best to fix it.

**Comment by erdengk** [comment]
@kaveeshadinamidu 
I'm still writing the test, I'll ask for help if there's a problem, thanks～
