### ISSUE TITLE
[Volunteer] Add integrated test for Resilience4j plugin

### ISSUE THREAD

**Issue by JooKS-me** [apache/incubator-shenyu#2910]
### Volunteer help

- [ ] Add integrated test for Resilience4j plugin

We should test as many parameter configurations as possible.

**Comment by hgaol** [comment]
I can have a try.

**Comment by JooKS-me** [comment]
> I can have a try.

good luck!

**Comment by RobWin** [comment]
I cross my fingers :)

**Comment by JooKS-me** [comment]
> I cross my fingers :)

Haha, we think Resilience4j is an excellent fault-tolerant library that can integrate well with Apache ShenYu~

**Comment by kaveeshadinamidu** [comment]
Do the tests are implemented? If not I can have a try.
