### ISSUE TITLE
[Question] How about change ribbon `ServerListRefreshInterval` from 30s to 10s ?

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#2916]
### Question

If the data of the registry (such as zookeeper) has been updated, `SpringCloudPlugin` will still select `unavailable` instances when using `Ribbon` for load balancing, change `ServerListRefreshInterval` from `30s` to `10s` can't completely solve this problem, but it can be avoided to a great extent.

**Comment by dragon-zhang** [comment]
Oh, maybe it's better to refactor like DividePlugin ?



发自我的iPhone


------------------ Original ------------------
From: dragon-zhang ***@***.***&gt;
Date: Mon,Feb 21,2022 5:45 PM
To: apache/incubator-shenyu ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Your activity ***@***.***&gt;
Subject: Re: [apache/incubator-shenyu] [Question] How about change ribbon `ServerListRefreshInterval` from 30s to 10s ? (Issue #2916)





 
Question
 
If the data of the registry (such as zookeeper) has been updated, SpringCloudPlugin will still select unavailable instances when using Ribbon for load balancing, change ServerListRefreshInterval from 30s to 10s can't completely solve this problem, but it can be avoided to a great extent.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yu199195** [comment]
this props，maybe can dynamic config~

**Comment by dragon-zhang** [comment]
In `ShenyuClientRegisterSpringCloudServiceImpl#buildHandle`, I found that `URLs` has been set in the `handle` field of the `selector`, which means that we can do this directly in 'SpringCloudPlugin#doExecute':
```java
    private List<Upstream> convertUpstreamList(final List<DivideUpstream> upstreamList) {
        return upstreamList.stream().map(u -> Upstream.builder()
                .protocol(u.getProtocol())
                .url(u.getUpstreamUrl())
                .weight(u.getWeight())
                .status(u.isStatus())
                .timestamp(u.getTimestamp())
                .warmup(u.getWarmup())
                .build()).collect(Collectors.toList());
    }

    @Override
    protected Mono<Void> doExecute(final ServerWebExchange exchange, final ShenyuPluginChain chain, final SelectorData selector,
                                   final RuleData rule) {
        if (Objects.isNull(rule)) {
            return Mono.empty();
        }
        final ShenyuContext shenyuContext = exchange.getAttribute(Constants.CONTEXT);
        assert shenyuContext != null;
        final SpringCloudSelectorHandle springCloudSelectorHandle = SpringCloudPluginDataHandler.SELECTOR_CACHED.get().obtainHandle(selector.getId());
        final SpringCloudRuleHandle ruleHandle = SpringCloudPluginDataHandler.RULE_CACHED.get().obtainHandle(CacheKeyUtils.INST.getKey(rule));

        //Below is a partial implementation of the code I plan to refactor
        final List<DivideUpstream> divideUpstreamList = springCloudSelectorHandle.getDivideUpstreams();
        if (CollectionUtils.isEmpty(divideUpstreamList)) {
            Object error = ShenyuResultWrap.error(exchange, ShenyuResultEnum.CANNOT_FIND_HEALTHY_UPSTREAM_URL, null);
            return WebFluxResultUtils.result(exchange, error);
        }
        String ip = Objects.requireNonNull(exchange.getRequest().getRemoteAddress()).getAddress().getHostAddress();
        Upstream upstream = LoadBalancerFactory.selector(convertUpstreamList(divideUpstreamList), ruleHandle.getLoadBalance(), ip);
        if (Objects.isNull(upstream)) {
            Object error = ShenyuResultWrap.error(exchange, ShenyuResultEnum.CANNOT_FIND_HEALTHY_UPSTREAM_URL, null);
            return WebFluxResultUtils.result(exchange, error);
        }
        //......
    }
```

**Comment by dragon-zhang** [comment]
In this way, another benefit is that we don't have to depend on `Ribbon`.

**Comment by dragon-zhang** [comment]
> In `ShenyuClientRegisterSpringCloudServiceImpl#buildHandle`, I found that `divideUpstreams` has been set in the `handle` field of the `selector`, which means that we can do this directly in `SpringCloudPlugin#doExecute`:
> 
> ```java
>     @Override
>     protected Mono<Void> doExecute(final ServerWebExchange exchange, final ShenyuPluginChain chain, final SelectorData selector,
>                                    final RuleData rule) {
>         if (Objects.isNull(rule)) {
>             return Mono.empty();
>         }
>         final ShenyuContext shenyuContext = exchange.getAttribute(Constants.CONTEXT);
>         assert shenyuContext != null;
>         final SpringCloudSelectorHandle springCloudSelectorHandle = SpringCloudPluginDataHandler.SELECTOR_CACHED.get().obtainHandle(selector.getId());
>         final SpringCloudRuleHandle ruleHandle = SpringCloudPluginDataHandler.RULE_CACHED.get().obtainHandle(CacheKeyUtils.INST.getKey(rule));
> 
>         //Below is a partial implementation of the code I plan to refactor
>         List<Upstream> upstreamList = UpstreamCacheManager.getInstance().findUpstreamListBySelectorId(selector.getId());
>         //......
>     }
> ```

Haha, as I supposed :)
<img width="993" alt="111111_3c411993-a2c3-419a-96f3-1077dc28d722" src="https://user-images.githubusercontent.com/38336731/154971081-4f9b961d-6cdf-447e-8745-7bd682a7a0db.png">

**Comment by dragon-zhang** [comment]
> this props，maybe can dynamic config~

I think `List<Upstream> upstreamList = UpstreamCacheManager.getInstance().findUpstreamListBySelectorId(selector.getId());` could be better, what do you think ?

**Comment by yu199195** [comment]
good pr， i will close this issue~
