### ISSUE TITLE
[Task] Change `Duration.ofSeconds` and `Duration.ofNanos` to `Duration.ofMiles` to avoid calculate manually in Resilience4J Plugin

### ISSUE THREAD

**Issue by hgaol** [apache/incubator-shenyu#2924]
### Description

Change `Duration.ofSeconds` and `Duration.ofNanos` to `Duration.ofMiles` to avoid calculate manually. And divide by 1000 will also influence the accuracy.

### Task List

 - [ ] change to Duration.ofMiles to avoid manual canculation.

**Comment by hgaol** [comment]
I can quick fix it.

**Comment by yu199195** [comment]
it good pull reuqest， it be fix， i will close this issue~
