### ISSUE TITLE
[BUG] <registerType is zookeeper，contextPath contains multiple '/', like '/my/context',   but '/' Is a zookeeper special character>

### ISSUE THREAD

**Issue by hutaishi** [apache/incubator-shenyu#2926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

contextPath contains multiple '/'.
setup admin:
![图片](https://user-images.githubusercontent.com/12478263/155261151-cde300f8-d574-4035-ac07-33965a222db8.png)

### Environment

```markdown
ShenYu version(s):
```

### Anything else?

If the user contextPath does not set multiple '/', this problem will not occur.
so Do we need to solve this case?

**Comment by yu199195** [comment]
contextPath only used by one '/'

**Comment by hutaishi** [comment]
> 

I don't think it's necessary to set multiple '/'. So can close this issue.
