### ISSUE TITLE
[Question] For Resilience4J plugin, why using max value between user configuration and preset, instead of making the preset value as default?

### ISSUE THREAD

**Issue by hgaol** [apache/incubator-shenyu#2927]
### Question

You can see below codes in `Resilience4JHandle#checkData`. The question is as mentioned in title. Is it by design?

<img width="1641" alt="image" src="https://user-images.githubusercontent.com/11908658/155288768-adefbeb9-907d-47c2-b872-27911f91c7e6.png">

BTW, if it's purpose is to use preset value as default, I can help to fix it.

Similar question, #2055 .

**Comment by hgaol** [comment]
Sorry, seems all the configurations except `fallbackUri` are required in `admin` portal. I guess the goal for `checkData` is to avoid invalid number, like `-10`?

**Comment by yu199195** [comment]
it set value, i think the logic should be to set defaults if you don't have them and configure them if you do~

**Comment by hgaol** [comment]
> it set value, i think the logic should be to set defaults if you don't have them and configure them if you do~

If like you mentioned, I think it needs to be updated. BTW, many fields like `limitForPeriod` are `int` or `long`, which means it will always has a number. Considering 0 is also an valid config in `resilience4j` for some scenarios, could I just verify the number and replace with default when it's less than 0. Like,
```java
resilience4JHandle.setLimitForPeriod(resilience4JHandle.getLimitForPeriod() < 0 ? Constants.LIMIT_FOR_PERIOD : resilience4JHandle.getLimitForPeriod());
```

**Comment by yu199195** [comment]
> could I just verify the number and replace with default when it's less than 0. Like

yes , you can~
