### ISSUE TITLE
hystrix plugin rule configuration, must restart the gateway to take effect

### ISSUE THREAD

**Issue by zouchangfu** [apache/incubator-shenyu#2931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
ShenYu version(s):v2.4.1
```

**Comment by hutaishi** [comment]
Who is doing this? If not, can you assign it to me and let me exercise

**Comment by lxl910128** [comment]
hello , you can use this feature synchronous config.

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/8736745/155937633-925d96da-00db-4213-bf27-902580ad4213.png">

**Comment by erdengk** [comment]
@lxl910128  
I tried sync but it still doesn't work.
I think this is also a bug. I created a new issue #2992
