### ISSUE TITLE
[Question] <title>SpringCloud proxy set isFull true but Rules Conditions is wrong

### ISSUE THREAD

**Issue by shawnlamjj** [apache/incubator-shenyu#2969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Conditions show uri is "=" /ContextPath

### Expected Behavior

Conditions show uri is "match" /ContextPath/**

### Steps To Reproduce

1.set application.yml

### Environment

```markdown
ShenYu version(s):2.4.2
```

### Anything else?

There was no problem in the previous 2.4.0 version, why did this happen after the update of 2.4.2?

**Comment by shawnlamjj** [comment]
shenyu:
  register:
    registerType: consul
    serverLists: x.x.x.x:8500
    props:
      name: ${spring.application.name}
      instanceId: ${spring.application.name}:${server.port}
  client:
    springCloud:
      props:
        contextPath: /${spring.application.name}
        port: ${server.port}
        isFull: true

**Comment by hgaol** [comment]
Seems it's a bug, I'll try to fix it.
