### ISSUE TITLE
[Question] shenyu-admin

### ISSUE THREAD

**Issue by chariles** [apache/incubator-shenyu#2972]
### Question

When I restart admin, the original configuration will be lost，why is this？

**Comment by AhahaGe** [comment]
could you please detail your question, with version, snapshot, procedure and so on, many thanks.

**Comment by KevinClair** [comment]
Set `spring.profiles.active=mysql`, then try it again.

**Comment by chariles** [comment]
> could you please detail your question, with version, snapshot, procedure and so on, many thanks.



> could you please detail your question, with version, snapshot, procedure and so on, many thanks.



> Set `spring.profiles.active=mysql`, then try it again.

ok, get it,many thinks

**Comment by midnight2104** [comment]
done
