### ISSUE TITLE
[Volunteer] Add unit test for [shenyu-agent] module .

### ISSUE THREAD

**Issue by haibo-duan** [apache/incubator-shenyu#2982]
### Volunteer help

Add unit test for [shenyu-agent] module .
please use junit5.

**Comment by kaveeshadinamidu** [comment]
I would like to work on this. Can you assign it to me? @haibo-duan

**Comment by haibo-duan** [comment]
@[kaveeshadinamidu](https://github.com/kaveeshadinamidu) Ok, thank you for your help .

**Comment by erdengk** [comment]
@kaveeshadinamidu 
Sheyu-agent has many modules, can I contribute together? Please share with me. thanks ：）

**Comment by kaveeshadinamidu** [comment]
@erdengk Yeah sure lets work together 👍

**Comment by erdengk** [comment]
@kaveeshadinamidu 
thanks, my friend.
What about that part of the test I do? Please assign it.

**Comment by kaveeshadinamidu** [comment]
@erdengk You can choose the models that you want. And give me other ones. That's fine with me 👍

**Comment by haibo-duan** [comment]
@[erdengk](https://github.com/erdengk) @[kaveeshadinamidu](https://github.com/kaveeshadinamidu)
Hi brother,What's the progress of this task？

**Comment by kaveeshadinamidu** [comment]
@haibo-duan Actually we are seeking some help to write the unit tests for the agent module. Can you give us some guidance? Because the methods in the shenyu-agent are somewhat different.

**Comment by erdengk** [comment]
@haibo-duan 
 Sorry for some busyness recently. I am trying to solve both of these problems.
#3028  #2985 
With the help of the community, I solved them.
Regarding this issue, I tried writing unit tests, but didn't make much progress. 
Can you guide me to get started?

**Comment by lxl910128** [comment]
We will adjust the agent design. So Unit tests don't need to be done now. thanks for you attention. @erdengk @kaveeshadinamidu
