### ISSUE TITLE
[BUG] <The judgment of the contains condition of all plug-ins does not work, which is a serious bug. >

### ISSUE THREAD

**Issue by lianjunwei** [apache/incubator-shenyu#2983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a URL: /gateway-demo/n/findById, which contains 'n'  to execute a plug-in. It is found that the plug-in is not executed.

![12451646473251_ pic](https://user-images.githubusercontent.com/13819823/156879282-215a59fc-a809-4f0e-b545-9d7443a633f3.jpg)

### Expected Behavior
java class: the matching result of containspredicatejudge after execution. It is expected to return true. But now it returns false. 

_No response_

### Steps To Reproduce
![12371646472526_ pic](https://user-images.githubusercontent.com/13819823/156879253-0f71e1c6-a448-4698-b8e9-be95e22138f6.jpg)
![12391646472641_ pic](https://user-images.githubusercontent.com/13819823/156879266-d4b79bfa-724f-4b2e-99e7-75b03bd4da14.jpg)

_No response_

### Environment

```markdown
ShenYu version(s): 2.4.2 and master.
```

### Anything else?

I'll submit a PR to fix it .

**Comment by impactCn** [comment]
https://github.com/apache/incubator-shenyu/pull/2608

This pr is a bug that was introduced by fixing various configurations. Can you try to fix the problem that the current string contains?

**Comment by lianjunwei** [comment]
> 



> #2608
> 
> This pr is a bug that was introduced by fixing various configurations. Can you try to fix the problem that the current string contains?
#2608 this fix is actually a wrong usage. "Contains" cannot be used as a "In". As shown below:
![image](https://user-images.githubusercontent.com/13819823/156907665-2fe5bf1d-fe1d-4aea-81cb-7740eaefbe0a.png)
