### ISSUE TITLE
[BUG] <no main manifest attribute, in shenyu-bootstrap.jar、shenyu-admin.jar>

### ISSUE THREAD

**Issue by lishuo5263** [apache/incubator-shenyu#3016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

mvn clean install -Dmaven.test.skip=true

### Steps To Reproduce

1.mvn clean package install all jar in local repository
![image](https://user-images.githubusercontent.com/19170961/157621540-2c1d3c38-e8d2-4d9a-a6c6-b079ead58337.png)

2.run java -jar shenyu-bootstrap.jar 

3.no main manifest attribute, in shenyu-bootstrap.jar
![image](https://user-images.githubusercontent.com/19170961/157623731-ebdbd476-f37c-453d-85c4-8d8beed00c72.png)

### Environment

```markdown
ShenYu version(s):2.4.3-SNAPSHOT
```

### Debug logs

![image](https://user-images.githubusercontent.com/19170961/157623824-d9396fd3-fdc6-470b-915a-92485c4a8b51.png)

**Comment by lishuo5263** [comment]
1.The company user should be deploy shenyu-admin(shenyu-dashboard)、shenyu-bootstrap(gateway) those project
2.I want use above project to run local env in idea, that fine ,but when I want deploy those project in ubuntu the jar is remind no main clss
3.The maven repository jar is same as ,entire jar file is 21kb when I run java -jar  the console output is no main class
![image](https://user-images.githubusercontent.com/19170961/157789188-dd4ba5ec-8036-477d-80df-a5957b07a238.png)

**Comment by chigend** [comment]
how you solve this problem , i meet the same issue
