### ISSUE TITLE
[BUG] When the service shutdown, it is not removed from the selector (Divide)

### ISSUE THREAD

**Issue by jerbo99** [apache/incubator-shenyu#3017]
### Is there an existing issue for this?

- [ ] #3018

### Current Behavior

With DevidePlugin, there are still requests for those client service after you close them one or more.

### Expected Behavior

After a service is down, the client service is no longer requested until it is restarted.

### Steps To Reproduce

1. Start client services.
2. Stop one or more of them.
3. Send multiple requests to the ShenYu.

### Environment

```markdown
ShenYu version(s): 2.4.2
```

### Debug logs

No error logs.

in AbstractShenyuClientRegisterServiceImpl.doRegisterURI:
if (CollectionUtils.isEmpty(uriList)) return "";

in ShenyuClientRegisterDivideServiceImpl.buildHandle
List<DivideUpstream> diffList = addList.stream().filter(divideUpstream -> !existList.contains(divideUpstream)).collect(Collectors.toList());  //returns diffList size of 0, because addList is the remaining list available, all exist in existList.

**Comment by jerbo99** [comment]
When the last client service down, RegisterServerConsumerExecutor is not processed because the primary attribute in the URIRegisterDTO is null.

**Comment by yu199195** [comment]
this fixed by 2.4.3

**Comment by jerbo99** [comment]
I have fixed it.
