### ISSUE TITLE
[Question] How about RPC and HTTP using shared thread pool ?

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3026]
### Question

When a request comes, it can be called either to `webClient` or RPC (Dubbo, sofa, grpc, etc.). Using shared thread pool can greatly improve resource utilization.

**Comment by yu199195** [comment]
@dragon-zhang  can you provide this new featrue？

**Comment by dragon-zhang** [comment]
> 

sure, I can do it.

**Comment by dragon-zhang** [comment]
> @dragon-zhang can you provide this new featrue？

sure, I can do it.

**Comment by yu199195** [comment]
@dragon-zhang Looking forward to your contributor，thanks
