### ISSUE TITLE
[BUG] <The Rewrite Plugin should support {PathVariable} request>

### ISSUE THREAD

**Issue by lishuo5263** [apache/incubator-shenyu#3037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1.Actived ShenYu Rewrute plugin , and add pom relateion jar 
2.Add rewrite rule ,the rule include {PathVariable}  param 
![image](https://user-images.githubusercontent.com/19170961/158093014-e6c02e1a-8677-41ec-b3f4-90285af254de.png)

### Steps To Reproduce

1.Refactor of  rewrite plugin  rewrite logic .
2.Add relate juint .

### Environment

```markdown
ShenYu version(s):2.4.3-SNAPSHOT
```

### Debug logs

2022-03-14 10:13:12 [boundedElastic-1]
INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - rewrite selector success match , selector name :gaia-internal-api-demo
2022-03-14 10:13:12 [boundedElastic-1] 
INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - rewrite rule success match , rule name :/gaia-internal-api/demo/order
2022-03-14 10:13:12 [boundedElastic-1] 
ERROR org.apache.shenyu.web.handler.GlobalErrorHandler - [99f5d1e9] Resolved [PatternSyntaxException: Illegal repetition near index 33
gaia-internal-api/demo/order/path/{id}/{name}
                                 ^] for HTTP GET /gaia-internal-api/demo/order/path/1/godfje@

**Comment by yu199195** [comment]
it merged，i will close it， thanks
