### ISSUE TITLE
The Shenyu-Bootstrap already started

### ISSUE THREAD

**Issue by yu65044** [apache/incubator-shenyu#3041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you use the ./start.sh command to start the admin successfully, and then use the ./start.sh command to start bootstrap, it will prompt: The ShenYu-Bootstarp already started! PID: xxxx
![微信图片_20220315150253](https://user-images.githubusercontent.com/54879138/158324397-e77b8f93-ad8d-4a66-b49b-f45ca19c062a.png)

### Expected Behavior

Need to successfully start ShenYu-Bootstrap
![1647328129](https://user-images.githubusercontent.com/54879138/158324981-33a094f3-c68b-4059-910a-f66e31a05792.png)

### Steps To Reproduce

1.cd apache-shenyu-incubating-2.4.2-bootstrap-bin/bin
2.Modify the start.sh file
3.Change PIDS=`ps -ef | grep "$DEPLOY_DIR" | grep -v grep | pgrep -f java` to PIDS=`ps -ef | grep "$DEPLOY_DIR" | grep -v grep`
4.Successfully saved after modification
5.Reuse the ./start.sh command to start bootstarp
![微信图片_20220315151547](https://user-images.githubusercontent.com/54879138/158325883-e8cb7972-a258-47f2-855e-f3548c8518e7.png)

### Environment

```markdown
ShenYu version(s):2.4.2-tar
```

### Debug logs

bootstrap started successfully
![1647328129](https://user-images.githubusercontent.com/54879138/158326476-83f33e58-193e-400f-8200-1a3cbe2f59cb.png)

### Anything else?

If you are referring to Chinese documentation, you need to pay attention to:
When the admin starts, it will prompt: java.sql.SQLException: No suitable driver found for jdbc:mysql...
You need to copy your local mysql-connector.jar to the ext-lib directory or the lib directory

hope this helps! Of course, ignore that exaggerated title. have a good day.

**Comment by impactCn** [comment]
https://github.com/apache/incubator-shenyu/pull/2859
