### ISSUE TITLE
[BUG] plugin edit bug

### ISSUE THREAD

**Issue by qicz** [apache/incubator-shenyu#3042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Request error! invalid argument [name: The plugin name already exists and can't be added repeatedly!]
![e11d441734ec6d9353112581529bc77](https://user-images.githubusercontent.com/2174082/158364103-9fb35d97-50f2-4a6a-bffb-65870e95cc2e.png)

### Environment

```markdown
ShenYu version(s): last
```

**Comment by li-keguo** [comment]
I fix it
