### ISSUE TITLE
[Question] How to package from 2.4.2 source code?

### ISSUE THREAD

**Issue by Franz362100** [apache/incubator-shenyu#3049]
### Question

In 2.4.1 packaging generated two compressed files, but I could not find the.tar.gz package after 2.4.2 packaging

The package command is:  
mvn clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -DskipITs -DskipTests

**Comment by yu199195** [comment]
pls see this ： https://shenyu.apache.org/zh/download
