### ISSUE TITLE
[BUG] Too much memory is occupied and has not been released

### ISSUE THREAD

**Issue by qicz** [apache/incubator-shenyu#3063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Maybe the client `runOn` is used incorrectly?

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/2174082/159102684-cce4debe-b5ec-4451-9586-25b211cfcc88.png">

![image](https://user-images.githubusercontent.com/2174082/159102663-3c5c87f5-be01-4998-a273-58a759b72e45.png)

### Environment

```markdown
ShenYu version(s): last
```

**Comment by qicz** [comment]
@dragon-zhang pls watch this.

**Comment by dragon-zhang** [comment]
I will watch it.



发自我的iPhone


------------------ Original ------------------
From: Qicz ***@***.***&gt;
Date: Sat,Mar 19,2022 10:10 AM
To: apache/incubator-shenyu ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/incubator-shenyu] [BUG] Too much memory is occupied and has not been released (Issue #3063)





 
@dragon-zhang pls watch this.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dragon-zhang** [comment]
> @dragon-zhang pls watch this.

I think this bug should be related to `org.apache.shenyu.plugin.httpclient.config.HttpClientProperties.ThreadPool#preferNative`, can you please add `Steps To Reproduce` ?

**Comment by dragon-zhang** [comment]
see https://github.com/apache/incubator-shenyu/pull/3068
