### ISSUE TITLE
[Task] <refactor shenyu agent logging>

### ISSUE THREAD

**Issue by hutaishi** [apache/incubator-shenyu#3064]
### Description

Reconstruct Shenyu agent logging in the form of Shenyu plugins.

### Task List

- [ ] Reconstruct Shenyu agent logging in the form of Shenyu plugins.
- [ ] remove  shenyu agent logging module

**Comment by WillemJiang** [comment]
Please add the background story of this issue.
I can only see what you want to do in this issue, but I cannot get the point why you want to do it.

**Comment by hutaishi** [comment]
> Please add the background story of this issue. I can only see what you want to do in this issue, but I cannot get the point why you want to do it.

Use plugin to replace agent and implement the same function.

**Comment by hutaishi** [comment]
> Please add the background story of this issue. I can only see what you want to do in this issue, but I cannot get the point why you want to do it.


 * Based on the guidance of the IPMC member and our mentors, and the
understanding of PPMC members, we should remove or redesign the
shenyu-agent module.
  * Agree on removing the shenyu-agent module.
  * Encourage developers to provide plugins to upstream like
Skywalking, ZipKin and Opentelemetry to implement the tracing
features.

Shenyu agent module will no longer be maintained and will be deleted.

**Comment by hutaishi** [comment]
We discuss the remove the agent module in the meeting
：https://lists.apache.org/thread/ow8o0hkym6p72gsoxxk0pyk895yk4wzv
