### ISSUE TITLE
[Question] Fail to use docker with mysql to deploy the Apache ShenYu gateway

### ISSUE THREAD

**Issue by zhanggyang** [apache/incubator-shenyu#3087]
### Question

Refer to the deployment documentation https://shenyu.apache.org/docs/deployment/deployment-docker.
I successfully deployed Apache ShenYu admin using h2 to store data.
When I change the storage to mysql,it failed
Here is the wrong message: Web server failed to start. Port 9095 was already in use.
I'm sure no one is using this port.I have tested ports  and none of them work.

By the way,I think Binary Packages Deployment also has something wrong. 
the file start.sh doesn't work on Linux server.This line of code seems to have a problem.
"PIDS=`ps -ef | grep "$DEPLOY_DIR" | grep -v grep | pgrep -f java`"
It seems to find out all the processes java started, causing the gateway to fail to start.

**Comment by yu199195** [comment]
@zhanggyang  hi whats the version？

**Comment by zhanggyang** [comment]
2.4.2

**Comment by yu199195** [comment]
> 2.4.2

you can used by master , it will be fix

**Comment by zhanggyang** [comment]
Thanks for your reply. I'll try it first

**Comment by impactCn** [comment]
https://github.com/apache/incubator-shenyu/issues/3041

**Comment by zhanggyang** [comment]
> > 2.4.2
> 
> you can used by master , it will be fix

**Comment by zhanggyang** [comment]
>  Hi , I tried it with the master image, and the problem was still there.
-  Steps To Reproduce
    - `docker pull apache/shenyu-admin:latest`
    - `docker network create shenyu`
    -  `netstat -tunlp | grep 9095`   Port 9095 is not occupied
    - `docker run -v /home/shenyu/conf:/opt/shenyu-admin/conf/ -v /home/shenyu/ext-lib:/opt/shenyu-admin/ext-lib -d -p 9095:9095 --net shenyu apache/shenyu-admin:latest`  my work dir is `/home/shenyu` and the relevant configuration files are ready
![image](https://user-images.githubusercontent.com/19372980/159643190-88d4144e-ca38-4e72-a293-7a0e9ea0f93c.png)
    -  The error massage is  “Web server failed to start. Port 9095 was already in use.” 
    -  `docker exec -it nostalgic_payne /bin/sh ` I exec into the container  to checkout `netstat -tunlp | grep 9095`  
![image](https://user-images.githubusercontent.com/19372980/159643313-083d6447-1c79-4be9-97e1-63d1f8fbbbdd.png)
    -  `sh -x start.sh `
![image](https://user-images.githubusercontent.com/19372980/159643658-9d9fafb1-58fd-413f-84fc-cc535e586ed7.png)
It seems there is still a problem with the start command

**Comment by impactCn** [comment]
You need to go into the container and modify the start.sh script. For details, please see https://github.com/apache/incubator-shenyu/issues/3041.

**Comment by zhanggyang** [comment]
> You need to go into the container and modify the start.sh script. For details, please see #3041.

I have change PIDS=ps -ef | grep "$DEPLOY_DIR" | grep -v grep | pgrep -f java to PIDS=ps -ef | grep "$DEPLOY_DIR" | grep -v grep. But it is not work for me.

![lQLPDhtDaTwIov_NAejNBHCwI3SNRYnvGR0CPx6X1sBsAA_1136_488](https://user-images.githubusercontent.com/19372980/159663262-fd1c1456-8241-4736-b6f8-186bb844a931.png)

![image](https://user-images.githubusercontent.com/19372980/159663182-dc8be56d-8e30-4032-9778-d28dafd822ae.png)

**Comment by impactCn** [comment]
![image](https://user-images.githubusercontent.com/35489877/159665197-1133486f-9878-441b-859d-7b51c6faff7b.png)

Delete all screenshots.

**Comment by zhanggyang** [comment]
> ![image](https://user-images.githubusercontent.com/35489877/159665197-1133486f-9878-441b-859d-7b51c6faff7b.png)
> 
> Delete all screenshots.
Hi，Do you mean converting all screenshots into text or simply deleting them？

 The h2 storage command `docker run -d --name sy-admin -p 9095:9095 --net shenyu apache/shenyu-admin:latest`  can start normally

But `
docker run -v /home/shenyu/bin/start.sh:/opt/shenyu-admin/bin/start.sh -v /home/shenyu/conf:/opt/shenyu-admin/conf/ -v /home/shenyu/ext-lib:/opt/shenyu-admin/ext-lib -d --name sy_admin  -p 9095:9095  --net shenyu apache/shenyu-admin:latest` can not.  think there is no problem with the master branch startup command itself, this feels like a mysql-related issue

**Comment by zhanggyang** [comment]
> ![image](https://user-images.githubusercontent.com/35489877/159665197-1133486f-9878-441b-859d-7b51c6faff7b.png)
> 
> Delete all screenshots.
Hi，Do you mean converting all screenshots into text or simply deleting them？

 The h2 storage command `docker run -d --name sy-admin -p 9095:9095 --net shenyu apache/shenyu-admin:latest`  can start normally

But `
docker run -v /home/shenyu/bin/start.sh:/opt/shenyu-admin/bin/start.sh -v /home/shenyu/conf:/opt/shenyu-admin/conf/ -v /home/shenyu/ext-lib:/opt/shenyu-admin/ext-lib -d --name sy_admin  -p 9095:9095  --net shenyu apache/shenyu-admin:latest` can not.  think there is no problem with the master branch startup command itself, this feels like a mysql-related issue
