### ISSUE TITLE
how can i get the ServerWebExchange anywhere ?

### ISSUE THREAD

**Issue by yelingjun** [apache/incubator-shenyu#3095]
### Question

i want to get the ServerWebExchange anywhere, and get some parameters from ServerWebExchange, how can i get it, thank you

**Comment by hutaishi** [comment]
You can refer to the responsive context. [link](https://projectreactor.io/docs/core/release/reference/#context):https://projectreactor.io/docs/core/release/reference/#context

You can put serverwebexchange into the responsive context in the interceptor, and then you can get it in the subsequent business code

**Comment by yelingjun** [comment]
thank you @hutaishi
