### ISSUE TITLE
[BUG] shell command errors

### ISSUE THREAD

**Issue by wklong** [apache/incubator-shenyu#3101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hi The  section (After the code is merged) of contributor guide(https://shenyu.apache.org/community/contributor-guide/) ,
**git pull upsteam master**
The shell command errors exist

**Comment by wklong** [comment]
I want to submit  PR fix for it

**Comment by yu199195** [comment]
@wklong  you can fix it， Looking forward to your pr

**Comment by erdengk** [comment]
@wklong
hi，the documentation is [here](https://github.com/apache/incubator-shenyu-website/blob/main/i18n/en/docusaurus-plugin-content-docs-community/current/3-contributor.md)

Thank you for your contribution

**Comment by wklong** [comment]
> @wklong hi，the documentation is [here](https://github.com/apache/incubator-shenyu-website/blob/main/i18n/en/docusaurus-plugin-content-docs-community/current/3-contributor.md)
> 
> Thank you for your contribution

thks for your reply

**Comment by wklong** [comment]
[https://github.com/apache/incubator-shenyu-website/issues/509](#509)

**Comment by wklong** [comment]
new issues:[#509](https://github.com/apache/incubator-shenyu-website/issues/509)
