### ISSUE TITLE
请问admin下得前端资源可以开源吗

### ISSUE THREAD

**Issue by justlemontree** [apache/incubator-shenyu#3103]
### Question

请问admin下得前端资源可以开源吗

**Comment by erdengk** [comment]
@justlemontree 
Hey, please communicate in English.
The front end of shenyu is in this [repository](https://github.com/apache/incubator-shenyu-dashboard).

**Comment by justlemontree** [comment]
ths~~

**Comment by erdengk** [comment]
@justlemontree 
please close this issue，thanks
