### ISSUE TITLE
[Volunteer] <title>Nullified logic needs to be improved

### ISSUE THREAD

**Issue by 1103283969** [apache/incubator-shenyu#3110]
### Volunteer help

Description

Hi Community:
This PR is to format the current null-detection logic. Improvements should be made for project maintenance needs and to enhance the robustness of the procedures.

For example,This is the original program:
          `if (log == null || logCollectClient == null) {
            return;
        }`

This does not guarantee that all fields in the log class are not empty. If important fields are empty, this can cause problems for subsequent processing logic. In addition, there is no printed error return log, which is not convenient for operation and error screening.

Here are the improvements,

```
  /* if (log == null || logCollectClient == null) { return; `}*/
        org.springframework.util.Assert.notNull(log,"ShenyuRequestLog `log入参");
       org.springframework.util.Assert.notNull(log.getClientIp(),"ShenyuRequestLog ClientIp入参");  
       org.springframework.util.Assert.notNull(log.getHost(),"ShenyuRequestLog Host入参");    
        org.springframework.util.Assert.notNull(log.getRequestUri(),"ShenyuRequestLog RequestUri入参");
        
    }
```

**Comment by 1103283969** [comment]
> 
This is all I've got right now. The above solution I think is only temporary. Eventually I would like to combine the ES logging system to finally implement null logic and null log storage.

**Comment by 1103283969** [comment]
> the scope is all project?

At present, I have only found this one, but I found that the system does not have the habit of storing logs to determine whether important fields are empty or not. I think it is possible to determine whether important fields are empty and store them in ES later.

**Comment by yu199195** [comment]
pls uesd Objects.nonNull adn Objects.isNull replace

**Comment by 1103283969** [comment]
> pls uesd Objects.nonNull xxxx != null or Objects.isNull replace xxxx == null

okey

**Comment by midnight2104** [comment]
pls see   https://shenyu.apache.org/zh/community/code-suggestions/
