### ISSUE TITLE
[Task] Optimize  plugin configuration  

### ISSUE THREAD

**Issue by qicz** [apache/incubator-shenyu#3121]
### Description

Optimize admin plugin configuration and sync plugin state to ShenYu

### Task List

1. sync admin plugin configuration state to Shenyu bootstrap
2. remove the disabled plugin from webhandler's `plugins`

**Comment by impactCn** [comment]
I am try it.

**Comment by moremind** [comment]
I want to do it

**Comment by yu199195** [comment]
@moremind  you can do it
