### ISSUE TITLE
[Question] <title>

### ISSUE THREAD

**Issue by zhangxin766884** [apache/incubator-shenyu#3126]
### Question

If it is a parameter like the following, an unsupported operationexception will be thrown if the JSON contains an array. Is there a solution for this?

{
	"name": "测试规则",
	"rule_data": {
		"rule_content": "1 > 0",
		"output_variables": [{
			"value": "SFDS",
			"name": "原因码",
			"variable_category": "RC_CAUSE_CODE"
		}, {
			"value": null,
			"name": "标签码1",
			"variable_category": "RC_TAG_CODE"
		}, {
			"value": null,
			"name": "标签码2",
			"variable_category": "tag_code_out"
		}, {
			"value": null,
			"name": "风险代码",
			"variable_category": "RC_RISK_CODE"
		}, {
			"value": "0",
			"name": "决策结果",
			"variable_category": "approval_result"
		}]
	},
	"control_group": {},
	"operator": null
}

**Comment by yu199195** [comment]
Please follow the template to ask questions, you can change the title to make it look more friendly~

**Comment by midnight2104** [comment]
invalid title name
