### ISSUE TITLE
[Question] <title>

### ISSUE THREAD

**Issue by Zc-yaochun** [apache/incubator-shenyu#3139]
### Question

shenyu网关部署完成 测试bootstrap代理时报错
![微信图片_20220328195037](https://user-images.githubusercontent.com/39295310/160392047-bf5e5bae-af75-4640-ab3e-b8972b8a5a59.png)
配置基本没有改动  存储方式变成mysql了 
本地测试代码(走非mvc方式)  localhost:19000/test/test（已测试能通）
shenyu-bootstrap的端口是19195
当请求localhost:19195/test/test
![微信图片_20220328195735](https://user-images.githubusercontent.com/39295310/160393102-942a3c31-bf01-4539-b7f0-6b43986d5a23.png)
如果路径错误 则会报普通的json错误
![微信图片_20220328195848](https://user-images.githubusercontent.com/39295310/160393254-e776f349-3ddb-485d-8cf0-523c184db95b.png)

**Comment by AhahaGe** [comment]
Please follow https://shenyu.apache.org/zh/docs/plugin-center/http-process/contextpath-plugin, and https://github.com/apache/incubator-shenyu/tree/master/shenyu-examples/shenyu-examples-http guide and try again, may this help u.

And please submit your plugin configuration and more details.

Thanks for your issue, and please use english to submit issue.

**Comment by Zc-yaochun** [comment]
Changed a server
The test was successful once
This is a screenshot
![微信图片_20220329103402](https://user-images.githubusercontent.com/39295310/160521294-2635f1a9-c7d4-4117-9c06-5a844cf1c743.png)
I changed the port of bootstrap to 19195
![微信图片_20220329103413](https://user-images.githubusercontent.com/39295310/160521407-dda23c78-853f-4561-9ec7-59d57ffd49fc.png)
This is the port and path of my test case
![微信图片_20220329103427](https://user-images.githubusercontent.com/39295310/160521491-6ced2fa1-5665-4ea1-a2aa-d3f647cf1222.png)
This is my selector configuration
![微信图片_20220329103430](https://user-images.githubusercontent.com/39295310/160521540-c9b79a33-a319-4da1-a052-81d9cfc6f862.png)
This is my rule configuration
![微信图片_20220329103937](https://user-images.githubusercontent.com/39295310/160521920-abfd5e98-620a-4259-a882-ad0ae6fc2a91.png)
This is the plug-in I used in the bootstrap project

But when I visit again later
It's wrong！！！
This is the wrong log
[error (3).txt](https://github.com/apache/incubator-shenyu/files/8367631/error.3.txt)

**Comment by AhahaGe** [comment]
You are following this document https://shenyu.apache.org/zh/docs/quick-start/quick-start-http/, right? 
Sorry I could not understand why you place your jars in ext-lib file and it may need some other dependency jars , and I can't see it in your jar dir, and you used 2.4.2 bootstrap, it's better use 2.4.2 divide and httpclient jar, maybe this caused the classClassException.

**Comment by midnight2104** [comment]
invalid title name
