### ISSUE TITLE
[Question] How to generate the same *.tar.gz package as before

### ISSUE THREAD

**Issue by Franz362100** [apache/incubator-shenyu#3142]
### Question

![image](https://user-images.githubusercontent.com/65158204/160518401-6695279f-b3e9-421b-8bf5-87374c92abfc.png)
![image](https://user-images.githubusercontent.com/65158204/160518427-433853d6-783a-418a-829f-89703f643cbf.png)

mvn clean install -Dmaven.javadoc.skip=true -B -Drat.skip=true -Djacoco.skip=true -DskipITs -DskipTests

**Comment by impactCn** [comment]
First, check release in the maven profile, and then execute mvn install in the parent pom to find the compressed jar under the dist directory.

**Comment by AhahaGe** [comment]
1. go to shenyu root directory
2. execute ```./mvnw -B clean install -Prelease -Dmaven.javadoc.skip=true -Dmaven.test.skip=true```
![image](https://user-images.githubusercontent.com/6198217/160530393-b7c17456-8705-46a0-873c-b1cf74c945d1.png)
