### ISSUE TITLE
[BUG] Front-end exception.

### ISSUE THREAD

**Issue by MarsOu1995** [apache/incubator-shenyu#3167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I add and modify the handler.
![image](https://user-images.githubusercontent.com/20200721/161224674-d00399ef-404f-4e32-bcd4-e61d9cc14d73.png)

refresh failed. Because of parameter passing exception.

http://localhost:9095/plugin-handle?pluginId=1509803933171535872&currentPage%5BcurrentPage%5D=1&pageSize=12

### Environment

```markdown
ShenYu version(s): 2.4.3
```

**Comment by li-keguo** [comment]
hi! it fixed, Please wait for the release of the next version


https://github.com/apache/incubator-shenyu-dashboard/pull/188
https://github.com/apache/incubator-shenyu-dashboard/issues/190

**Comment by midnight2104** [comment]
done
