### ISSUE TITLE
[BUG] The postgreSql database initialization script has an error.

### ISSUE THREAD

**Issue by ShawnJim** [apache/incubator-shenyu#3180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `date_created`、`date_updated` field in the table 'plugin' is not null.
![image](https://user-images.githubusercontent.com/32192263/161377307-476ded27-39b6-4254-9d78-1968ec8c7af0.png)

 But `date_created`、`date_updated` field is assigned null in the insert sql.
![image](https://user-images.githubusercontent.com/32192263/161377424-6f24f3c5-b877-494e-b4e7-0f2deaee219f.png)

### Environment

```markdown
ShenYu version(s): master
```

### Debug logs

Script Execution log:

![70f383476d3bf8a1ed790d9be8e293c](https://user-images.githubusercontent.com/32192263/161377089-ae00ed11-3657-4b04-a0c2-5f868bb7a385.png)

**Comment by nuo-promise** [comment]
You can remove the default datetime of h2 mysql pg.

**Comment by ShawnJim** [comment]
> You can remove the default datetime of h2 mysql pg.

Ok, I will commit the changes later.

**Comment by midnight2104** [comment]
doen
