### ISSUE TITLE
How to customize log information？

### ISSUE THREAD

**Issue by LinQilong** [apache/incubator-shenyu#3200]
### Question

Hello, I'd like to ask. If I want to customize the log information (API call success and failure information, IP, parsing location information, saving specific information, etc.), how should I configure it?

**Comment by yu199195** [comment]
hi， you can see logging plugin，and logging-rockeqMQ plugin.

If it does not meet your needs, you can custom develop  shenyu plugin.

**Comment by hutaishi** [comment]
If you have good suggestions or find problems or unmet needs, you can communicate with the community, and the community is willing to improve

**Comment by midnight2104** [comment]
If there are still questions, please reopen issue
