### ISSUE TITLE
[Question] How about reuse `HttpClient` in `HttpClientPluginConfiguration` for `WebSocketPluginConfiguration`

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3224]
### Question

current `WebSocketPluginConfiguration`:
```java
    @Bean
    public ReactorNettyWebSocketClient reactorNettyWebSocketClient(final ShenyuConfig shenyuConfig) {
        final ReactorNettyWebSocketClient webSocketClient = new ReactorNettyWebSocketClient();
        webSocketClient.setMaxFramePayloadLength(shenyuConfig.getWebsocket().getMaxFramePayloadSize() * 1024 * 1024);
        return webSocketClient;
    }
```
after reuse `HttpClient` in `HttpClientPluginConfiguration`:
```java
    @Bean
    public ReactorNettyWebSocketClient reactorNettyWebSocketClient(final ShenyuConfig shenyuConfig,
                                                                   final ObjectProvider<HttpClient> httpClient) {
        final ReactorNettyWebSocketClient webSocketClient = new ReactorNettyWebSocketClient(httpClient.getIfAvailable(HttpClient::create));
        webSocketClient.setMaxFramePayloadLength(shenyuConfig.getWebsocket().getMaxFramePayloadSize() * 1024 * 1024);
        return webSocketClient;
    }
```
I think reuse could be better, how do you guys feel ?

**Comment by yu199195** [comment]
if used `HttpClient` , it be used by divide and spring cloud plugin,

and then used by websocket plugin, Is not as good as the original
isolation？ （I can't confirm）

**Comment by dragon-zhang** [comment]
We didn't use any `blocking` operator when using `HttpClient`, therefore reuse should not have adverse effects.

**Comment by yu199195** [comment]
> Sorry for the late response. We didn't use any blocking operator when using HttpClient, therefore reuse should not have adverse effects.

pls reply for dev mail

**Comment by dragon-zhang** [comment]
copy that.






------------------ Original ------------------
From: xiaoyu ***@***.***&gt;
Date: Tue,Apr 12,2022 11:02 PM
To: apache/incubator-shenyu ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/incubator-shenyu] [Question] How about reuse `HttpClient` in `HttpClientPluginConfiguration` for `WebSocketPluginConfiguration` (Issue #3224)





  
Sorry for the late response. We didn't use any blocking operator when using HttpClient, therefore reuse should not have adverse effects.
  
pls reply for dev mail
