### ISSUE TITLE
[Task] <Shenyu-admin add new module: API document aggregation display & sandbox test>

### ISSUE THREAD

**Issue by lianjunwei** [apache/incubator-shenyu#3239]
### Description

The document information provided by each micro service is summarized and displayed uniformly.

### Task List

Several core APIs are listed below:
1、 Menu list of documents.
     Each service is a level-1 menu item, and each interface in it is a sub menu item.
     The API URL may be: 
     http://localhost:9195/apidoc/getDocMenus
      
2、 API details.
     The API URL may be: 
     http://localhost:9195/apidoc/getDocItem?id=010fd856-f788-4814-b09a-d2bba507a22e

3、 API details tab - common request parameters (headers) and common response parameters
     There are two implementation methods: front-end configuration (JSON file) or back-end API return.

4、 Run test.
      The API URL may be: 
     http://localhost:9195/sandbox/testRun

**Comment by yu199195** [comment]
good job~

**Comment by yu199195** [comment]
We look forward to your contributions, which you can send to   mail list (dev@shenyu.apache.org)

**Comment by lianjunwei** [comment]
done.
