### ISSUE TITLE
[BUG] There are no state control buttons in the MetaData editing interface

### ISSUE THREAD

**Issue by lichenliang666** [apache/incubator-shenyu#3242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are no state control buttons in the MetaData editing interface
![image](https://user-images.githubusercontent.com/35353971/163135186-67233f80-001b-473d-b1a0-140c87d5d812.png)
![image](https://user-images.githubusercontent.com/35353971/163135302-fe085b5a-e003-42ff-a661-d65998f166f4.png)

### Steps To Reproduce

open edit panel of MetaData 

### Environment

```markdown
ShenYu version(s):2.4.3
```

**Comment by yu199195** [comment]
maybe if want to update `status `,  used separate button and not on the edit page，

**Comment by lichenliang666** [comment]
It doesn't seem to work, the interface returns the information that the parameter is missing:
> Validation failed for argument [0] in public org.apache.shenyu.admin.model.result.ShenyuAdminResult org.apache.shenyu.admin.controller.MetaDataController.createOrUpdate(org.apache.shenyu.admin.model.dto.MetaDataDTO): [Field error in object 'metaDataDTO' on field 'enabled': rejected value [null]; codes [NotNull.metaDataDTO.enabled,NotNull.enabled,NotNull.java.lang.Boolean,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [metaDataDTO.enabled,enabled]; arguments []; default message [enabled]]; default message [不能为null]]
