### ISSUE TITLE
[BUG] <Swagger request param currentPage locates in body for get request>

### ISSUE THREAD

**Issue by AhahaGe** [apache/incubator-shenyu#3251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. start admin
2. go to http://localhost:9095/swagger-ui.html#/dashboard-user-controller/queryDashboardUsersUsingGET
3. see currentPage locates in body
![image](https://user-images.githubusercontent.com/6198217/163544427-00a4acc1-2d63-4f10-bfd0-cc49cc4733fe.png)

### Expected Behavior

1. currentPage locates in query

### Environment

```markdown
ShenYu version(s):latest
```

**Comment by AhahaGe** [comment]
I am fixing it.

**Comment by yu199195** [comment]
good job
