### ISSUE TITLE
[Question] Consider only shenyu-bootstrap run mode

### ISSUE THREAD

**Issue by myesn** [apache/incubator-shenyu#3254]
### Question

I ran `shenyu-admin` and `shenyu-bootstrap` through `docker-compose` on Raspberry Pi (arm64) without configuring any plugins, selectors, rules, and found that each of these two services takes up about `1 GB` , and my Raspberry Pi has only` 4 GB` of memory in total. I personally think that `shenyu-admin` is **just a `GUI` interface for configuration**. When the project is mature and stable, all plug-ins, selectors, The rule configuration has been solidified and will not change. In this scenario, `shenyu-admin` should provide a method to export all plugins, selectors, and rule configuration data to static files, such as json format configuration data files, and then `shenyu-bootstrap` loads this static configuration data file into the memory. At this time, it is equivalent to only running `shenyu-bootstrap`, and it is no longer necessary to run the `shenyu-admin` service, which can reduce and optimize the memory usage of the server.

**Comment by zouchangfu** [comment]
The shenyu-admin is not only for configuring selector, rules, but also for other functions, such as checking if the upstream services are online, etc.
