### ISSUE TITLE
[BUG] <Modify context-path of shenyu-admin, website can not access>

### ISSUE THREAD

**Issue by luoweijr** [apache/incubator-shenyu#3257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i modify the context-path configuration of shenyu-admin, then visit website will get a null page

### Expected Behavior

Modify context-path of shenyu-admin, website can visit successfully

### Steps To Reproduce

1. modify context-path in shenyu-admin
![Screenshot_20220416_235713](https://user-images.githubusercontent.com/23328274/163682195-29d87200-ac61-4e38-afd5-b8a599f44169.png)

2. modify code in index.html
![123123](https://user-images.githubusercontent.com/23328274/163683113-97d6b938-dcc4-438f-8e3e-d5285542bdbf.png)

3. visit http://localhost:9095/test/shenyu-admin

4. get a null page
![null](https://user-images.githubusercontent.com/23328274/163682375-3cb7a053-4bdc-4f4a-abc3-91f413617a83.png)

### Environment

```markdown
ShenYu version(s):2.3.0
```

### Anything else?

I check the source code about shenyu-admin, find a ${domain} placehold in index.html
![3333](https://user-images.githubusercontent.com/23328274/163683220-67a263e5-0227-433f-976e-5b48c181174c.png)

then i try to find a keyword "domain" in IndexController.java and change the code as below
![111](https://user-images.githubusercontent.com/23328274/163682734-1e8c0ef3-5f94-4049-9267-0399ab6df71e.png)

visit  http://localhost:9095/test/shenyu-admin/index, then it works
![444444444444444444444444](https://user-images.githubusercontent.com/23328274/163683375-96aa9a18-8697-48ab-a983-2cde6c169fd1.png)

**Comment by zouchangfu** [comment]
The latest version should have fixed it

**Comment by yu199195** [comment]
hi， you can startup shenyu-admin add this ： `-Dshenyu.httpPath=xxx`

**Comment by luoweijr** [comment]
> hi， you can startup shenyu-admin add this ： `-Dshenyu.httpPath=xxx`

I setup shenyu.httpPath, it works well! Thanks for your help!! @yu199195
