### ISSUE TITLE
[BUG] upgrade dubbo due to cve(s)

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-shenyu#3260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current dependency in trunk has a vulnerability. https://github.com/advisories/GHSA-v2rg-8cwr-75g8

Probably best to go to 2.7.15 to avoid some other CVEs - see https://mvnrepository.com/artifact/org.apache.dubbo/dubbo to see which versions have CVEs,

### Expected Behavior

Upgrade dubbo

### Environment

```markdown
ShenYu version(s): dev
```

**Comment by dragon-zhang** [comment]
Agree, the upgrade can also improve the performance of `dubbo generalization calls`.

**Comment by yu199195** [comment]
@pjfanning  hi ，can you provide this pr （upgrade dubbo version）

**Comment by pjfanning** [comment]
@yu199195 I added https://github.com/apache/incubator-shenyu/pull/3265

**Comment by yu199195** [comment]
@pjfanning  Thank you for your help~
