### ISSUE TITLE
[Task] Improve the unit test coverage of shenyu-plugin-rewrite

### ISSUE THREAD

**Issue by HaiqiQin** [apache/incubator-shenyu#3292]
### Description

At present, the unit test coverage of shenyu-plugin-rewrite is 50%，and we can increase it to more than 80%.

### Task List

1.Improve the unit test coverage of shenyu-plugin-rewrite to more than 80%.

**Comment by wklong** [comment]
Hello, Can I have a try?

**Comment by HaiqiQin** [comment]
Sorry, this is the task I applied for myself. You can browse other tasks.

**Comment by wklong** [comment]
OK
