### ISSUE TITLE
[Task] Add shenyu webfilter unit test

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#3299]
###  medium task

You can check the code coverage of ShenYu at this [site](https://app.codecov.io/gh/apache/incubator-shenyu).

### Task List

- [x]  add  HealthFilterTest for org.apache.shenyu.web.filter.HealthFilter @wklong 
- [x]  add LocalDispatcherFilterTest for org.apache.shenyu.web.filter.LocalDispatcherFilter @moremind 

###  How to contributor 

You can see this : https://shenyu.apache.org/community/contributor-guide

**Comment by wklong** [comment]
Hi ,can you assigin org.apache.shenyu.web.filter.HealthFilter to me? thanks

**Comment by yu199195** [comment]
@wklong  good luck~

**Comment by Mayank-KS** [comment]
I would like to try contributing to the other task so can you assign it to me? Also it there any other way I can join the Shen-Yu contributor group as WeChat is banned in my country? Thanks

**Comment by yu199195** [comment]
@Mayank-KS  hi

1. Of course you can, and if you want, any contribution is welcome.
2. You can subscribe dev@sheyu.apache.org mail list , see this : https://shenyu.apache.org/community/contributor-guide#join-the-discussion.

**Comment by moremind** [comment]
Hi, @yu199195 ,I try to commit `LocalDispatcherFilterTest `, can you assign this task for me?

**Comment by yu199195** [comment]
@moremind  ok， i will assign to you

**Comment by yu199195** [comment]
@wklong @moremind  You can add me on WeChat and I will invite you to join the contributor group~

**Comment by moremind** [comment]
> a commit to moremind/incubator-shenyu that refere
My WeChat is yijia1949

> @wklong @moremind You can add me on WeChat and I will invite you to join the contributor group~

thanks,I can't find your WeChat,My WeChat is `yijia1949`

**Comment by wklong** [comment]
> @wklong @moremind You can add me on WeChat (xixy199195) and I will invite you to join the contributor group~

I've joined the contributor group, thks

**Comment by yu199195** [comment]
hi guys， this task already done， i will close this issue~
