### ISSUE TITLE
[BUG] MemoryLimiter.acquireInterruptibly may keep waiting unexpectedly

### ISSUE THREAD

**Issue by Albertsirius** [apache/incubator-shenyu#3318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I wrote unit test cases for `org.apache.shenyu.common.concurrent.MemoryLimiter`(#3275),  I have found a potential bug: if it invokes `acquireInterruptibly` method, it may keep waiting unexpectedly in spite of having been notified previously.

### Expected Behavior

While waiting after calling `acquireInterruptibly`, it will acquire memory immediately if receiving a notify signal and the memory is sufficient.

### Steps To Reproduce

1. Invoke the `MemoryLimiter.acquireInterruptibly(o)` with the memory size of `o` plus Memory.getCurrentMemory not sufficient to `MemoryLimiter.memoryLimit` 
2. Start other Thread, call `MemoryLimiter.release` in order to meet the memory ( memory size of `o` plus Memory.getCurrentMemory is less than `memoryLimit`) and notify
3. `acquireInterruptibly` still waits unexpetedly

### Environment

```markdown
ShenYu version(s): current
```

### Anything else?

Line 217 - 220 at acquireInterruptibly：
<img width="474" alt="Screen Shot 2022-04-25 at 10 41 04" src="https://user-images.githubusercontent.com/1999408/165011988-d73a98d8-e001-4ee1-b337-0cc47f3a90ca.png">
if it is notified, but sum doesn't change so `sum + objectSize` is still large than memoryLimit, and enter `await `again

Compare to `acquire` （line 184 - 189)
<img width="498" alt="Screen Shot 2022-04-25 at 10 46 26" src="https://user-images.githubusercontent.com/1999408/165012387-bd98e6bf-1356-494a-bb02-47f2057ea78e.png">
I think use `memory.sum()` to replace sum, can solve this bug.

**Comment by dragon-zhang** [comment]
I think yes, can you fix it ?

**Comment by Albertsirius** [comment]
I can fix it @dragon-zhang 
> I think yes, can you fix it ? @Albertsirius

**Comment by dragon-zhang** [comment]
> I can fix it @dragon-zhang
> 
> > I think yes, can you fix it ? @Albertsirius

Thanks, looking forward to your contribution.

**Comment by dragon-zhang** [comment]
please close this issue.
