### ISSUE TITLE
[BUG] sql script lost uri plugin data

### ISSUE THREAD

**Issue by moremind** [apache/incubator-shenyu#3336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/20184263/165243819-fcbc77b1-f19f-4bba-942b-bd11c58d2700.png)

### Expected Behavior

need add uri plugin data.

### Environment

```markdown
ShenYu version(s):
```

**Comment by yu199195** [comment]
Hi

uri plugin is default, not in sql script~

**Comment by moremind** [comment]
oh, thanks
