### ISSUE TITLE
[Task] refactor the places which maybe need muti values

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3346]
### Description

Now `ParameterData#builder` has only one return value, which is not rigorous enough in some cases (such as `cookie`and `header`). You need to find these places (maybe not only `ParameterData#builder` has this problem) and refactor it. If you want to contribute or find places similar to `ParameterData#builder`, please leave a message and I will assign it to you.

### Task List

1.  - [ ] refactor `org.apache.shenyu.plugin.base.condition.data.ParameterData#builder`;
2. - [ ] refactor `org.apache.shenyu.plugin.base.condition.data.HeaderParameterData`;
3. - [ ] refactor `org.apache.shenyu.plugin.base.condition.data.CookieParameterData`;
4. - [ ] find places which maybe need muti values;

**Comment by erdengk** [comment]
@dragon-zhang 
I think we can consider tagging these issues as `good second issues` .

**Comment by dragon-zhang** [comment]
> @dragon-zhang I think we can consider tagging these issues as `good second issues` .

good idea

**Comment by dragon-zhang** [comment]
@erdengk could you do this ?

**Comment by erdengk** [comment]
> @erdengk could you do this ?

@dragon-zhang 
oh， thanks for you suggestion
I have some other tasks.
Leave this task to other volunteers.

**Comment by dragon-zhang** [comment]
Got it.

**Comment by ChineseTony** [comment]
hello, I add muti values support ,Can you assigned this issue to me?

**Comment by dragon-zhang** [comment]
Sorry, guys, if this feature is merged now, it will cause some obvious performance loss. Therefore, I will close this issue.
