### ISSUE TITLE
[Question] </shenyu/plugin/selectorAndRules can`t access>

### ISSUE THREAD

**Issue by ZhangJiaLei123** [apache/incubator-shenyu#3358]
### Question
Version: 2.5.0-SNAPSHOT and 2.4.3
get Error on http://127.0.0.1:9195/shenyu/plugin/selectorAndRules.
![微信截图_20220428110533](https://user-images.githubusercontent.com/40969169/165668667-faf35db7-f8b2-46e1-bfe7-af069bb3db10.png)
![微信截图_20220428110549](https://user-images.githubusercontent.com/40969169/165668678-96aac06e-821f-444a-9148-ba2f27e2e53b.png)

**Comment by yu199195** [comment]
can you config this ?

shenyu
     local
        enable: true

**Comment by ZhangJiaLei123** [comment]
thanks
