### ISSUE TITLE
does have any plan to update to Spring boot latest version？

### ISSUE THREAD

**Issue by flyingbeecd** [apache/incubator-shenyu#3359]
### Question

does have any plan to update to Spring boot latest version?

**Comment by li-keguo** [comment]
yes, Some community members are doing it

**Comment by dragon-zhang** [comment]
see https://github.com/apache/incubator-shenyu/pull/3438 , there are other jobs mentioned in the PR, if you are interested you can participate. Please close this issue if you think it's ok.
