### ISSUE TITLE
[Task] <GRPC plugin is not compatible with low versions(such as: version 1.6.0 ) and json and documentation issues>

### ISSUE THREAD

**Issue by hutaishi** [apache/incubator-shenyu#3374]
### 1. MethodDescriptor.Marshaller get defaultInstance field not compatible with low versions.
<img width="1224" alt="图片" src="https://user-images.githubusercontent.com/12478263/166394186-72cc7fad-960e-4003-9151-bed89b772f1b.png">

### Compatibility recommendations
```java      
if (requestMarshaller instanceof MethodDescriptor.PrototypeMarshaller) {
   MethodDescriptor.PrototypeMarshaller<?> prototypeMarshaller = (PrototypeMarshaller<?>) requestMarshaller;
   REQUEST_PARAMS_CLASS_MAP.put(fullMethodName, prototypeMarshaller.getMessagePrototype().getClass());
}
```
---
### 2.MethodDescriptor get serviceName field not compatible with low versions.
<img width="1206" alt="图片" src="https://user-images.githubusercontent.com/12478263/166395468-e1a1f594-3d53-45ca-b307-d7d17ffba497.png">

## Compatibility recommendations
No exception is thrown if the field is empty, and the service name is set if the field is not empty.

---
### 3.The output json field is not standardized
not standardized json output:
<img width="542" alt="图片" src="https://user-images.githubusercontent.com/12478263/166394767-f4370025-89d7-45d6-9d34-7acb73f2e8b6.png">

standardized json output:
<img width="390" alt="图片" src="https://user-images.githubusercontent.com/12478263/166394816-87fb9f32-25e4-43da-9572-e8f999c91536.png">

### Improvements that can be considered
json serialization of each element in the value at the gateway

**Comment by midnight2104** [comment]
Hi, @hutaishi , are you willing to fix these problems? Also, consider whether the Json service is necessary?

**Comment by hutaishi** [comment]
> Hi, @hutaishi , are you willing to fix these problems? Also, consider whether the Json service is necessary?

Very happy to improve the plugin
