### ISSUE TITLE
[BUG] compatibility problem when use `NettyHttpClientPlugin`

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using `NettyHttpClientPlugin`, the implementation of `org.apache.shenyu.plugin.api.result.ShenyuResult#contentType` is incompatible.

### Expected Behavior

No compatibility problem.

### Steps To Reproduce

1. run `ShenyuAdminBootstrap`;
2. run `ShenyuTestHttpApplication`;
3. enable `NettyHttpClientPlugin` and run `ShenyuBootstrapApplication`;
4. send request:
```http
POST http://localhost:9195/http/shenyu/client/hello
Accept: application/json
Content-Type: application/json
```

### Environment

```markdown
ShenYu version(s): master
```

### Debug logs

nop

### Anything else?

nop

**Comment by dragon-zhang** [comment]
```java
    default MediaType contentType(ServerWebExchange exchange, Object formatted) {
        //fixme not compatible with NettyHttpClientPlugin
        final ClientResponse clientResponse = exchange.getAttribute(Constants.CLIENT_RESPONSE_ATTR);
        if (Objects.nonNull(clientResponse) && clientResponse.headers().contentType().isPresent()) {
            return clientResponse.headers().contentType().get();
        }
        return MediaType.APPLICATION_JSON;
    }
```
Is anyone willing to fix it?

**Comment by hutaishi** [comment]
I Can fix it. thinks

**Comment by dragon-zhang** [comment]
Sorry, it has been done in `org.apache.shenyu.plugin.response.strategy.NettyClientMessageWriter`.
