### ISSUE TITLE
[Question] shenyu-client/register-uri not found

### ISSUE THREAD

**Issue by chariles** [apache/incubator-shenyu#3393]
### Question

When I import the shenyu-admin-2.4.2.jar into my own project, request http://localhost:9095/shenyu-client/register-uri  not found,can you give me some advice?

**Comment by li-keguo** [comment]
Can you elaborate on your problem?
If you want to know more, please refer to: [admin guide](https://shenyu.apache.org/docs/2.4.2/user-guide/admin-usage/data-permission)
