### ISSUE TITLE
[Question] what is the role of the scheduler bean config?

### ISSUE THREAD

**Issue by tonyxu721** [apache/incubator-shenyu#3397]
### Question

I am testing the "shenyu-examples-http" example project, and i found there is a "Scheduler" bean config, just see the pic:<img width="742" alt="image" src="https://user-images.githubusercontent.com/23226155/167585028-1812cd0c-641f-40c8-ba84-3da940bbf470.png">
 Can anyone can tell me what’s the role of this config and where it is used?

**Comment by yu199195** [comment]
hi，This is just a demo, how to use depends on your spring project！

**Comment by tonyxu721** [comment]
> hi，This is just a demo, how to use depends on your spring project！

I know this is just a demo, but i think the config is confused, maybe the bean is used to change webflux server thread pool model, but i don't know
