### ISSUE TITLE
文档可以写的easy一点么，好让初学者入门，文档看的我高血压都犯了。

### ISSUE THREAD

**Issue by zkna** [apache/incubator-shenyu#3398]
### Volunteer help

先讲述一下我的经历，想尝试一下shenyu网关：
第一步，得部署一个admin网关项目吧，
![image](https://user-images.githubusercontent.com/19741934/167808516-c4137741-1e43-418f-841d-01e3e2482a90.png)
这个图没错吧，就问你的maven打包可以成功么？
好吧，终于一步一步探索，把项目导入到idea，把一些杂七杂八的项目去掉了，shenyu-admin才能跑起来

第二步，因为我要尝试一下spring cloud的项目，还是跟第一步一样，新起一个spring cloud项目。

第三步，重要的一步来了，当我跟着文档走，配置对应的转发规则的时候，对应的配置规则没了，就戛然而止了，如下图，如下链接
![image](https://user-images.githubusercontent.com/19741934/167810774-0d99308e-8878-48fc-9b13-06ff6a3c533a.png)

[对应图片链接](https://shenyu.apache.org/zh/docs/quick-start/quick-start-springcloud)

官网readme更是奇葩，直接给了一个请求参数，关键你这请求参数不变还行呀，你这一变，谁知道你参数变成啥了呀
![image](https://user-images.githubusercontent.com/19741934/167811178-f5ab07ee-8bd7-4dbe-81a4-7d2ba3fa0c01.png)

我是看过liteflow的文档，有看了shenyu的文档的，希望改进一下文档 ->祝好
https://github.com/dromara/liteflow

**Comment by zouchangfu** [comment]
@zkna 
Thank you for your suggestion, at present shenyu is in the development stage, if you are interested,  welcome to join us to solve these problems.

**Comment by moremind** [comment]
@zkna 
shenyu will optimize these documents, welcome join us to contribute your document on `https://github.com/apache/incubator-shenyu-website`
