### ISSUE TITLE
[BUG] Websocket异常关闭会导致文件描述符一直增加

### ISSUE THREAD

**Issue by kevinw66** [apache/incubator-shenyu#3400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

启用Websocket之后，如果web端没有关闭websocket而直接关闭了整个页面，会导致文件描述符占用一直增加

### Expected Behavior

web端异常退出的时候能正确关闭websocket

### Environment

```markdown
ShenYu version(s):2.1.0
但是查阅过最新代码，websockethandler相关的并没有太大改动
```

### Debug logs

# lsof -p 1 | grep sock | wc -l
68
# lsof -p 1 | grep sock | wc -l
69
# lsof -p 1 | grep sock | wc -l
69
# lsof -p 1 | grep sock | wc -l
70

**Comment by dragon-zhang** [comment]
Can you see if this problem still exists in version 2.4.3 ?
