### ISSUE TITLE
[Task] Add the unit test of shenyu-plugin-motan

### ISSUE THREAD

**Issue by HaiqiQin** [apache/incubator-shenyu#3405]
### Description

Now the unit test of Motan plug-in has not been written, I will write it

### Task List

1.Add the unit test of shenyu-plugin-motan

**Comment by dragon-zhang** [comment]
oh, thanks







------------------ Original ------------------
From: qinghai777 ***@***.***&gt;
Date: Sun,May 15,2022 2:34 PM
To: apache/incubator-shenyu ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [apache/incubator-shenyu] [Task] Add the unit test of shenyu-plugin-motan (Issue #3405)





 
Description
 
Now the unit test of Motan plug-in has not been written, I will write it
 
Task List
 
1.Add the unit test of shenyu-plugin-motan
