### ISSUE TITLE
[Task] sofa and tars using shared thread pool

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3406]
### Description

As a subtask of https://github.com/apache/incubator-shenyu/issues/3026, the sofa plugin and tars plugin do not use the shared thread pool.

As for mqtt, divide, springcloud and websocket plugins, they are not supported because their IO model is different from that applicable to shared thread pool.

### Task List

1. - [x] support shared thread pool for sofa plugin, You can find some helpful information in https://github.com/sofastack/sofa-rpc/issues/1186 and https://github.com/sofastack/sofa-rpc/pull/1194;
2. - [x] support shared thread pool for tars plugin;

**Comment by lahmXu** [comment]
Please assign to me, thanks!

**Comment by dragon-zhang** [comment]
Thanks for your contribution! @lahmXu
