### ISSUE TITLE
[BUG] modify metadata error

### ISSUE THREAD

**Issue by k11hao** [apache/incubator-shenyu#3431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

编辑已添加的元数据时，当点击保存按钮时报错，
![image](https://user-images.githubusercontent.com/6235692/170244478-5213e180-3626-4c7f-9cbd-cf3affa75029.png)

### Environment

```markdown
ShenYu version(s): 2.4.3
```

**Comment by MichaelDeSteven** [comment]
![image](https://user-images.githubusercontent.com/51652084/170275296-10c3b4ed-7c2a-4f5a-822e-07d7e02aeee2.png)
添加metadata界面有Status也就是enabled，但是更改metadata前端界面没有这个选项，导致enabled为空。这个应该是前端界面的问题

**Comment by MichaelDeSteven** [comment]
我又试了一下，对需要修改的条目，点击批量启动后，这个问题就没有了

**Comment by li-keguo** [comment]
hi ,it fixed
see: https://github.com/apache/incubator-shenyu-dashboard/pull/202
