### ISSUE TITLE
[Task] detailed metadata of springCloud / springMvc client registration

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3436]
### Description

Now SpringMvcClient does not register metadata by default, it needs to be registered by default.

And for SpringCloudClient, the registered metadata is not specific enough(for example, now only has `/test-springCloud/**`), we need more detaild metaData such as `/test-springCloud/aaaa/bbbb` for future usage.

### Task List

1. - [x] SpringMvcClient register metadata by default, @renzhuyan ;
2. - [ ] SpringCloudClient register more detaild metadata, @dragon-zhang ;

**Comment by dragon-zhang** [comment]
task 2 is mine.

**Comment by renzhuyan** [comment]
Please assign task1 to me. Thank you

**Comment by dragon-zhang** [comment]
> Please assign task1 to me. Thank you

thanks, too.
