### ISSUE TITLE
[Question] How about add a new proxy plugin named `BrpcPlugin`?

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3437]
### Question

Here is the homepage of [brpc](https://github.com/apache/incubator-brpc) ,and we can use [brpc-java](https://github.com/baidu/brpc-java) to implments `BrpcPlugin`.

The following is the official introduction:
brpc is an industrial-grade RPC framework used throughout [Baidu](http://ir.baidu.com/phoenix.zhtml?c=188488&p=irol-irhome), with 1,000,000+ instances(not counting clients) and thousands kinds of services.

**Comment by JooKS-me** [comment]
I think it's a good idea and the licenses are all Apache 2.0

**Comment by dragon-zhang** [comment]
Then I will create the task for community.

**Comment by dragon-zhang** [comment]
see https://github.com/apache/incubator-shenyu/issues/3450
