### ISSUE TITLE
[BUG] tars plugin can not config other thread pool field 

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/38336731/170828285-40acff0b-0799-48e8-a34f-a950042d8d29.png)
missed other fields.
bug is in `shenyu-admin/src/main/resources/sql-script/h2/schema.sql`
![image](https://user-images.githubusercontent.com/38336731/170828314-afdd17ed-aa3d-4a55-8555-0703f10dce66.png)

### Environment

```markdown
ShenYu version(s): master
```

**Comment by lahmXu** [comment]
OK, I will fix this bug.
