### ISSUE TITLE
[Question] about spring-boot-starter typo

### ISSUE THREAD

**Issue by MichaelDeSteven** [apache/incubator-shenyu#3452]
### Question

I review some class, then find **many** class doc have the **same** problem. 
![image](https://user-images.githubusercontent.com/51652084/170834920-64ae954d-c4f0-419a-95bf-90e11ac92f7a.png)
![image](https://user-images.githubusercontent.com/51652084/170835032-c7d4d91f-a103-4fcb-ba02-e38d09d2b68f.png)
![image](https://user-images.githubusercontent.com/51652084/170835041-40b0333e-2920-45a9-a08f-97bc0643e6f8.png)

Are they redundant? If so, I will fix it.

**Comment by KevinClair** [comment]
Looking forward to your pr.
