### ISSUE TITLE
[Question] <Why does shenyu client not support nacos registry>

### ISSUE THREAD

**Issue by LBJWt** [apache/incubator-shenyu#3459]
### Question

Why does shenyu client not support nacos registry

**Comment by yu199195** [comment]
Hi  we already support nacos， can you see this ：https://shenyu.apache.org/docs/next/user-guide/register-center-access#nacos-registry-config

**Comment by chengyan0079** [comment]
> Hi we already support nacos， can you see this ：https://shenyu.apache.org/docs/next/user-guide/register-center-access#nacos-registry-config

404..
