### ISSUE TITLE
Data synchronization problem caused by websocket disconnection ( ShenyuWebsocketClient#healthCheck）

### ISSUE THREAD

**Issue by como-ca** [apache/incubator-shenyu#3460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After using Apache Shenyu V 2.4.3, it was found that after a period of time, the websocket of the gateway instance and Shenyu Admin would be disconnected. It was initially suspected that there was a problem with the heartbeat of websockt and the processing of the timer's time wheel. Later, the internal emergency repair method was to rewrite the ShenyuWebsocketClient to use the ScheduledThreadPoolExecutor to execute the healthCheck method regularly to ensure the heartbeat of the websocket and fix this problem. So please officially check the timing scheduling ( Timer, TimerTask ) of healthCheck v2.4.3.

### Expected Behavior

After Apache Shenyu Admin releases or modifies the configuration, the Shenyu gateway instance can receive data synchronization from websocket at any time

### Steps To Reproduce

1、Check the websocket configuration of the shenyu gateway instance, deploy success
2、After the deployment is successful, immediately publish or modify the configuration in the shenyu admin. Through the log observation of the Shenyu gateway instance, it is found that the gateway instance can normally receive any data from the shenyu admin websocket
3、When I go to step 2 above again on the second or third day, the gateway instance has not received the websockt data from shenyu admin , and I also checked the logs of Apache Shenyu Admin, and no 
 " org.apache.shenyu.admin.listener.websocket.WebsocketCollector - websocket on client[*.*.*.*] open successful, maxTextMessageBufferSize:10240 " log .
4、Previously, we turned the log level of the gateway instance to debug level, but on the second or third day after the gateway instance was deployed, the "websocket send to [{}] ping message successful in the ShenyuWebsocketClient # healthCheck() method was not found. " 's log

### Environment

```markdown
ShenYu version(s):2.4.3
```

### Debug logs

Shenyu gateway instance： websocket send to [{}] ping message successful
Shenyu admin : org.apache.shenyu.admin.listener.websocket.WebsocketCollector - websocket on client[*.*.*.*] open successful, maxTextMessageBufferSize:10240 " log 

### Anything else?

I can participate in the troubleshooting and problem process at any time, and you can contact me by email to make apache shenyu better together ,  1176372741@qq.com

**Comment by yu199195** [comment]
Hi

thanks for you issue，

We noticed the problem and have made the relevant fixes in master, not sure if it has been fixed, can you move closer to the master branch?

BTW, in version 2.4.2 is using the ScheduledThreadPoolExecutor to execute the healthCheck

**Comment by como-ca** [comment]
Hi,
Thank you for your reply.
My current internal emergency repair solution is to use ScheduledThreadPoolExecutor to handle, because the 2.4.3 version has been fully upgraded, so I have rewritten ShenyuWebsocketClient class to achieve the repair.



In addition, the master you mentioned has been fixed, and you should wait for the next version to be released .


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-shenyu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月31日(星期二) 中午12:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/incubator-shenyu] Data synchronization problem caused by websocket disconnection ( ShenyuWebsocketClient#healthCheck） (Issue #3460)





 
Hi
 
thanks for you issue，
 
We noticed the problem and have made the relevant fixes in master, not sure if it has been fixed, can you move closer to the master branch?
 
BTW, in version 2.4.2 is using the ScheduledThreadPoolExecutor to execute the healthCheck

**Comment by yu199195** [comment]
Hi

you can see this : https://github.com/apache/incubator-shenyu/pull/3297


BTW, If you are a company, can you help register more use cases in  https://github.com/apache/incubator-shenyu/issues/68?
