### ISSUE TITLE
[Question] test code about tars-plugin

### ISSUE THREAD

**Issue by MichaelDeSteven** [apache/incubator-shenyu#3463]
### Question

when I run test in the tars-plugin, I found some test is fail.
Here are error test list and message.
![image](https://user-images.githubusercontent.com/51652084/171318097-49d645ca-a072-4471-9f1c-f41253bfa1ce.png)
![image](https://user-images.githubusercontent.com/51652084/171318127-38e743e8-6961-4b2e-bc22-6565323febcd.png)
![image](https://user-images.githubusercontent.com/51652084/171318154-e9f9550c-9e64-4aa3-8bd9-001fec037b9e.png)
Is anything I did wrong, or just the test code bug.

**Comment by moremind** [comment]
this maybe bug.

**Comment by lahmXu** [comment]
It's my fault. I'll fix it
