### ISSUE TITLE
Proposal: add support for apollo

### ISSUE THREAD

**Issue by dengliming** [apache/incubator-shenyu#348]
https://github.com/ctripcorp/apollo

**Comment by yu199195** [comment]
可以作为一种实现

**Comment by yu199195** [comment]
maybe we should support it

**Comment by dengliming** [comment]
Duplicate of [https://github.com/apache/incubator-shenyu/issues/1537](https://github.com/apache/incubator-shenyu/issues/1537)

**Comment by wklong** [comment]
Is the project still going on?
