### ISSUE TITLE
[Task] simplify the use of client annotations with @AliasFor

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3485]
### Description

For example, below is how we use `@ShenyuXXXXClient` now:
```java
@RestController
@RequestMapping("/order")
@ShenyuSpringCloudClient(path = "/order")
public class OrderController {

    /**
     * Save order dto.
     *
     * @param orderDTO the order dto
     * @return the order dto
     */
    @PostMapping("/save")
    @ShenyuSpringCloudClient(path = "/save")
    public OrderDTO save(@RequestBody final OrderDTO orderDTO) {
        orderDTO.setName("hello world spring cloud save order");
        return orderDTO;
    }

}
```
After use `@AliasFor` with `@ShenyuSpringCloudClient` like below:
```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface ShenyuSpringCloudClient {

    /**
     * Path string.
     *
     * @return the string
     */
    @AliasFor(attribute = "path")
    String value() default "";

    /**
     * Path string.
     *
     * @return the string
     */
    @AliasFor(attribute = "value")
    String path() default "";

    /**
     * Rule name string.
     *
     * @return the string
     */
    String ruleName() default "";

    /**
     * Desc string.
     *
     * @return String string
     */
    String desc() default "";

    /**
     * Enabled boolean.
     *
     * @return the boolean
     */
    boolean enabled() default true;
}
```
We can simplify client annotation usage to:
```java
@RestController
@RequestMapping("/order")
@ShenyuSpringCloudClient("/order")
public class OrderController {
    
    /**
     * Save order dto.
     *
     * @param orderDTO the order dto
     * @return the order dto
     */
    @PostMapping("/save")
    @ShenyuSpringCloudClient("/save")
    public OrderDTO save(@RequestBody final OrderDTO orderDTO) {
        orderDTO.setName("hello world spring cloud save order");
        return orderDTO;
    }
    
}
```
You can refer to the implementation scheme of `shenyu-client-springcloud`, don't forget to use `org.springframework.core.annotation.AnnotatedElementUtils#findMergedAnnotation`.

And if you have some great ideas, please leave a message below, let's discuss it.

### Task List

1. - [x] simplify @ShenyuDubboClient in `alibaba dubbo`; @sunshujie1990
2. - [x] simplify @ShenyuDubboClient in `apache dubbo`; @sunshujie1990
3. - [x] simplify @ShenyuGrpcClient; @weihubeats
4. - [x] simplify @ShenyuSpringMvcClient; @Albertsirius 
5. - [x] simplify @ShenyuMotanClient; @ChineseTony 
6. - [x] simplify @ShenyuSofaClient; @ShawnSiao
7. - [x] simplify @ShenyuTarsClient; @weihubeats
8. - [x] simplify @ShenyuSpringWebSocketClient; @weihubeats

**Comment by Albertsirius** [comment]
Hi, @dragon-zhang , can you assign ShenyuSpringMvcClient task to me?

**Comment by ShawnSiao** [comment]
Can i take task 6，thank you.

**Comment by ChineseTony** [comment]
Can i take task 5，thank you.

**Comment by weihubeats** [comment]
Can i take task 3，thank you.

**Comment by weihubeats** [comment]
Can i take task 8，thank you.

**Comment by dragon-zhang** [comment]
> Can i take task 8，thank you.

sure, thanks

**Comment by weihubeats** [comment]
Can i take task 7，thank you.

**Comment by dragon-zhang** [comment]
Thanks for your contribution !

**Comment by dragon-zhang** [comment]
If you have other great ideas, please submit a new ISSUE .
