### ISSUE TITLE
[Task] upgrade shenyu dependency task1

### ISSUE THREAD

**Issue by moremind** [apache/incubator-shenyu#3511]
### Description

upgrade shenyu dependency and make sure dependency version test case.

### Task List

1. 1.  [x] upgrade shenyu resilience4j plugin dependency and test. @moremind 
2. 2.  [x] upgrade shenyu hystrix plugin dependency and test. @moremind 
3. 3.  [x] upgrade shenyu jwt plugin dependency and test. @moremind 
4. 4.  [x] upgrade shenyu logging-rocketmq plugin dependency and test. @moremind 
5. 5.  [x] upgrade shenyu motan plugin dependency and test. @renzhuyan 
6. 6.  [x] upgrade mybatis , druid, pagehelper version and test. @renzhuyan 
7. 7.  [x] upgrade tool packages, for example: common-collectiions, gson, common-lang and xstream and so so, @renzhuyan

**Comment by moremind** [comment]
@li-keguo please assgin to @renzhuyan

**Comment by li-keguo** [comment]
He has to leave a message so I can find him from the list
@renzhuyan

**Comment by renzhuyan** [comment]
> He has to leave a message so I can find him from the list @renzhuyan

I will do it, Thank you.

**Comment by moremind** [comment]
I have upgrade sentinel to 1.8.3, resilience4j to 1.7.1, hystrix to 1.5.18

**Comment by moremind** [comment]
this task have finished. I will close it.
