### ISSUE TITLE
[Question] dubbo+nacos，gateway not success

### ISSUE THREAD

**Issue by LBJWt** [apache/incubator-shenyu#3512]
### Question

The client keeps returning：
`c.d.s.ShenyuClientURIExecutorSubscriber : host:192.168.56.1, port:20888 connection failed, will retry`
sync and The registry use nacos .

**Comment by moremind** [comment]
please describe this question with your shenyu version and your debug log.

**Comment by LBJWt** [comment]
> please describe this question with your shenyu version and your debug log.

shenyu : 2.4.3
shenyu-admin  config :
`shenyu:
  register:
    registerType: nacos #http #zookeeper #etcd #nacos #consul
    serverLists: nacos:8848 #http://localhost:2379 #localhost:8848
#    registerType: zookeeper #http #zookeeper #etcd #nacos #consul
#    serverLists: localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      sessionTimeout: 5000
      connectionTimeout: 2000
      checked: true
      zombieCheckTimes: 5
      scheduledTime: 10
      nacosNameSpace: 1c10d748-af86-43b9-8265-75f48748517c
  sync:
    nacos:
      url: nacos:8848
      namespace: 1c10d748-af86-43b9-8265-75f48748517c
      username: nacos
      password: nacos`
shenyu-bootstrap config : 
`shenyu: 
       sync:
          nacos:
            url: nacos:8848
            namespace: 1c10d748-af86-43b9-8265-75f48748517c
            username: nacos
            password: nacos`
client  config:
`shenyu:
  register:
    registerType: nacos #zookeeper #etcd #nacos #consul
    serverLists: nacos:8848 #localhost:2181 #http://localhost:2379 #localhost:8848
    props:
      username: nacos
      password: nacos
      nacosNameSpace: 1c10d748-af86-43b9-8265-75f48748517c
  client:
    dubbo:
      props:
        contextPath: /dubbo
        appName: dubbo

dubbo:
  application:
    name: test-dubbo-service
  registry:
    protocol: nacos
    address: nacos:8848
  protocol:
    name: dubbo
    port: 20889` 
request http://localhost:9195/dubbo/findById?id=666    ， response is：
{
code: -106,
message: "Can not find url, please check your configuration!"
}

the admin is reported successfull.
![image](https://user-images.githubusercontent.com/16012187/173023548-f63707f7-1d24-47f9-96e5-0b940b9c60be.png)

**Comment by moremind** [comment]
please check nacos exist service？

**Comment by moremind** [comment]
if nacos is not exist service please check nacos url

**Comment by LBJWt** [comment]
![image](https://user-images.githubusercontent.com/16012187/173048329-d47c7cc8-1963-4699-be47-e5f694a8c7a2.png)

**Comment by moremind** [comment]
do you try shenyu master? I will try test it.

**Comment by LBJWt** [comment]
yes ,same result

**Comment by LBJWt** [comment]
I changed the synchronization method to websocket and it was successful

**Comment by LBJWt** [comment]
The problem is solved. The reason is that the nacos sync package is not import. The master's bootstrap only has nacos without the import of the sync package. Others are import. this https://shenyu.apache.org/zh/docs/deployment/deployment-quick/  package is the same  question .
```
        <!-- apache shenyu data sync start use nacos-->
        <dependency>
            <groupId>org.apache.shenyu</groupId>
            <artifactId>shenyu-spring-boot-starter-sync-data-nacos</artifactId>
            <version>${project.version}</version>
        </dependency>
```

**Comment by moremind** [comment]
> 

do you want to contribute to shenyu? if yes, please fork and contribute to shenyu

**Comment by moremind** [comment]
> The problem is solved. The reason is that the nacos sync package is not import. The master's bootstrap only has nacos without the import of the sync package. Others are import. this https://shenyu.apache.org/zh/docs/deployment/deployment-quick/ package is the same question .
> 
> ```
>         
>         <dependency>
>             <groupId>org.apache.shenyu</groupId>
>             <artifactId>shenyu-spring-boot-starter-sync-data-nacos</artifactId>
>             <version>${project.version}</version>
>         </dependency>
> ```

do you want to contribute to shenyu? if yes, please fork and contribute to shenyu
