### ISSUE TITLE
[Task] add integration tests for shared thread pool

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3521]
### Description

As a subtask of https://github.com/apache/incubator-shenyu/issues/3026, we need to add some integration tests to make sure that shared thread pool is working fine.

### Task List

1. - [x] add integration test in `shenyu-integrated-test-alibaba-dubbo`; @renzhuyan
2. - [x] add integration test in `shenyu-integrated-test-apache-dubbo`; @dragon-zhang 
3. - [x] add integration test in `shenyu-integrated-test-grpc`; @MichaelDeSteven
4. - [x] add integration test in `shenyu-integrated-test-motan`; @sunshujie1990 
5. - [x] add integration test in `shenyu-integrated-test-sofa`; @ShawnSiao
6. - [ ] add integration test in `shenyu-integrated-test-combination`; @dragon-zhang

**Comment by dragon-zhang** [comment]
I will do task2 and task6, the other tasks are yours. It is recommended that other tasks by referring to task2 after I complete it.

**Comment by renzhuyan** [comment]
Please assign 1 to me, thank you!

**Comment by MichaelDeSteven** [comment]
plz asign task3 to me, thx.

**Comment by ShawnSiao** [comment]
Please assign 5 to me, thank you!

**Comment by sunshujie1990** [comment]
Please assign task 4 to me, thank you!

**Comment by sunshujie1990** [comment]
@dragon-zhang Hi dragon. While adding the `shenyu.sharedPool.enable` property, my ide (IntelliJ IDEA) autocomplete the property key to `shenyu.shared-pool.enable` which results shared thread pool not effective. I think this is because of the implemention does not follow spring-boot's specification.

Shenyu implemention:
```
    @Bean
    @ConditionalOnProperty(name = "shenyu.sharedPool.enable", havingValue = "true")
```

spring-boot doc:
```
	/**
	 * The name of the properties to test. If a prefix has been defined, it is applied to
	 * compute the full key of each property. For instance if the prefix is
	 * {@code app.config} and one value is {@code my-value}, the full key would be
	 * {@code app.config.my-value}
	 * <p>
	 * Use the dashed notation to specify each property, that is all lower case with a "-"
	 * to separate words (e.g. {@code my-long-property}).
	 * @return the names
	 */
	String[] name() default {};
```

https://github.com/spring-projects/spring-boot/blob/2.6.x/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnProperty.java

**Comment by dragon-zhang** [comment]
> @dragon-zhang Hi dragon. While adding the `shenyu.sharedPool.enable` property, my ide (IntelliJ IDEA) autocomplete the property key to `shenyu.shared-pool.enable` which results shared thread pool not effective. I think this is because of the implemention does not follow spring-boot's specification.
> 
> Shenyu implemention:
> 
> ```
>     @Bean
>     @ConditionalOnProperty(name = "shenyu.sharedPool.enable", havingValue = "true")
> ```
> 
> spring-boot doc:
> 
> ```
> 	/**
> 	 * The name of the properties to test. If a prefix has been defined, it is applied to
> 	 * compute the full key of each property. For instance if the prefix is
> 	 * {@code app.config} and one value is {@code my-value}, the full key would be
> 	 * {@code app.config.my-value}
> 	 * <p>
> 	 * Use the dashed notation to specify each property, that is all lower case with a "-"
> 	 * to separate words (e.g. {@code my-long-property}).
> 	 * @return the names
> 	 */
> 	String[] name() default {};
> ```
> 
> https://github.com/spring-projects/spring-boot/blob/2.6.x/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/condition/ConditionalOnProperty.java

Can you help me find and deal with other similar places?

**Comment by sunshujie1990** [comment]
Sure. I will create a new issue to track the problem later.
