### ISSUE TITLE
[Task] add AOP for almost all examples

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3523]
### Description

you need to add some `aspects` in `example` module that forcing spring container to create `AOP Proxy`, so we can make sure that all proxy client sdk works fine when users use AOP.

you can find some useful informations in https://github.com/apache/incubator-shenyu/pull/2834.

if you find some bug, PRs are welcomed.

### Task List

1. - [x] add AOP test for `shenyu-client-alibaba-dubbo`; @weihubeats
2. - [x] add AOP test for `shenyu-client-apache-dubbo`; @weihubeats
3. - [x] add AOP test for `shenyu-client-grpc`; @MichaelDeSteven
4. - [x] add AOP test for `shenyu-client-springcloud`; @renzhuyan 
5. - [x] add AOP test for `shenyu-client-springmvc`; @gaochuang98
6. - [x] add AOP test for `shenyu-client-motan`; @sunshujie1990 
7. - [x] add AOP test for `shenyu-client-sofa`; @ShawnSiao
8. - [x] add AOP test for `shenyu-client-websocket`; @Albertsirius 
9. - [x] remove duplicate code; @dragon-zhang

**Comment by weihubeats** [comment]
Please give me tasks 1 and 2, thank you

**Comment by MichaelDeSteven** [comment]
plz asign task3 to me, thx.

**Comment by gaochuang98** [comment]
plz asign task  5 to me, thx.

**Comment by ShawnSiao** [comment]
please asign task 7 to me, thank you.

**Comment by renzhuyan** [comment]
please asign task 4 to me, thank you.

**Comment by Albertsirius** [comment]
please assign task 8 to me, thanks

**Comment by sunshujie1990** [comment]
please assign task 6 to me, thanks
