### ISSUE TITLE
[Bug] Apache Shenyu's SkyWalking plugin NPE

### ISSUE THREAD

**Issue by wu-sheng** [apache/incubator-shenyu#3592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just want to forward this https://github.com/apache/skywalking/issues/9250 reported by @always-web to SkyWalking

### Anything else?

We are not sure what is going on, so, just sync to Shenyu community.

**Comment by hutaishi** [comment]
Sorry for not fully considering a type context like IgnoredTracerContext.
A fix PR has now been submitted：https://github.com/apache/skywalking-java/pull/215

**Comment by yu199195** [comment]
it be merged ： https://github.com/apache/skywalking-java/pull/215

i will close this issue，thanks
