### ISSUE TITLE
[BUG] <Docker mismatch cannot be resolved>

### ISSUE THREAD

**Issue by ChenchengY** [apache/incubator-shenyu#3606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot run ShenYu through docker since I use arm64 architecture, the localhost:9095 always return the page as l listed below:

![1655963370841](https://user-images.githubusercontent.com/85370951/175224709-1479522a-547c-4fde-ba33-3cca92759635.png)

![1655963303386](https://user-images.githubusercontent.com/85370951/175224585-ed02c589-4698-4f18-99a1-1c4d627c9b82.png)

### Expected Behavior

I think the admin page should prompt out.

### Steps To Reproduce

Windows/Linux environment, follow the docer install guidance of shenyu

### Environment

```markdown
ShenYu version(s):latest
```

**Comment by JooKS-me** [comment]
The image in docker hub can't support amd64 now, but it'll be resolved in the next release.

BTW, if you want to get the latest image, you can also see : https://github.com/apache/incubator-shenyu/pkgs/container/incubator-shenyu%2Fadmin . Unlike on docker hub, here is the latest image built on master.

**Comment by ChenchengY** [comment]
Thank you, it works well
