### ISSUE TITLE
Dubbo请求body的`[]`中包含Number类型字段（包括int、long、float等），都被gson强制转化成double

### ISSUE THREAD

**Issue by sanduoduoys** [apache/incubator-shenyu#3625]
### Question

![image](https://user-images.githubusercontent.com/62974648/175930782-2dcea5e4-c6cf-42a7-8cf1-1fd00800f87f.png)

![image](https://user-images.githubusercontent.com/62974648/175930803-af64042d-44b0-4c08-987a-f078615f5c34.png)

**Comment by yu199195** [comment]
pls used in english
