### ISSUE TITLE
[Task] use path to search

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3631]
### Description

Now `shenyu-admin` use `appName` to search, when an application registers many interfaces, the search results are not accurate enough. It would be nice to use `path` search instead.
<img width="1423" alt="图片" src="https://user-images.githubusercontent.com/38336731/176333886-1a74145b-7257-40e6-987e-b4f054dc1702.png">

### Task List

1. - [x] The backend uses `path` field to search; @Albertsirius 
2. - [x] The front-end call parameters are changed, and the words displayed on the page by default are changed to `path`; @847850277

**Comment by Albertsirius** [comment]
I want to try the task 1

**Comment by 847850277** [comment]
I want to try the task 2，please asign to me 。

**Comment by dragon-zhang** [comment]
> I want to try the task 2，please asign to me 。

check [incubator-shenyu-dashboard](https://github.com/apache/incubator-shenyu-dashboard) project

**Comment by 847850277** [comment]
I've forked it

**Comment by 847850277** [comment]
I've checked it

**Comment by Albertsirius** [comment]
@dragon-zhang 
`MetaDataQuery` class only has two fields: `appName` and `pageParameter`
Do I replace `appName` to `path` or simply add `path` field ?

**Comment by dragon-zhang** [comment]
replace, and don't forget update .js , .html file.&nbsp;





------------------ Original ------------------
From: Zihao Huang ***@***.***&gt;
Date: Sat,Jul 2,2022 10:42 AM
To: apache/incubator-shenyu ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/incubator-shenyu] [Task] use path to search (Issue #3631)





 
@dragon-zhang
 MetaDataQuery class only has two fields: appName and pageParameter
 Do I replace appName to path or simply add path field ?
