### ISSUE TITLE
[Question] How to unregister

### ISSUE THREAD

**Issue by sbinsun** [apache/incubator-shenyu#3645]
### Question
Clients are automatically registered with the gateway when they start. So is there an API to unregister? In the K8S environment, the IP changed when the service was updated, but because the registration was not cancelled in time, there was still an old IP at the gateway, which caused some traffic requests to fail.

**Comment by yu199195** [comment]
pls in english

**Comment by KevinClair** [comment]
Registration information will be automatically deleted after a certain period of time
