### ISSUE TITLE
[Volunteer] Add admin mapper unit test

### ISSUE THREAD

**Issue by renzhuyan** [apache/incubator-shenyu#3655]
### Volunteer help

Add the admin module mapper unit test to make it run through H2, mysql, PG and Oracle normally. You can refer to the existing mapper unit test, such as appauthmappertest.

1. - [x] Add alert-template-sqlmap unit test. @847850277
2. - [x] Add operation-record-log-sqlmap unit test. @MichaelDeSteven 
3. - [x] Add user-role-sqlmap unit test. @Albertsirius

**Comment by 847850277** [comment]
i want to task 1,please asign to me. thank you.

**Comment by Albertsirius** [comment]
Please assign task 3 to me

**Comment by MichaelDeSteven** [comment]
plz assign task2 to me, thx.

**Comment by renzhuyan** [comment]
Thank you for your contribution.
