### ISSUE TITLE
[Question] <title>when body is too long，the body data is truncated，why？

### ISSUE THREAD

**Issue by gongzhibo** [apache/incubator-shenyu#3660]
### Question

![image](https://user-images.githubusercontent.com/19222385/177091148-f20ae41a-bab7-4f1f-9c2b-c6367d9b7ff5.png)

**Comment by moremind** [comment]
ShenYu Version?

**Comment by KevinClair** [comment]
Check this in `GeneralContextPlugin`

**Comment by gongzhibo** [comment]
version：2.4.2

**Comment by moremind** [comment]
in `org.apache.shenyu.plugin.base.RpcParamTransformPlugin` make sure that

```java
    private Mono<Void> body(final ServerWebExchange exchange, final ServerHttpRequest serverHttpRequest, final ShenyuPluginChain chain) {
        return Mono.from(DataBufferUtils.join(serverHttpRequest.getBody())
                .flatMap(body -> {
                    exchange.getAttributes().put(Constants.PARAM_TRANSFORM, resolveBodyFromRequest(body));
                    return chain.execute(exchange);
                }));
    }
```
this is look like https://github.com/apache/incubator-shenyu/issues/3158

**Comment by gongzhibo** [comment]
> in `org.apache.shenyu.plugin.base.RpcParamTransformPlugin` make sure that
> 
> ```java
>     private Mono<Void> body(final ServerWebExchange exchange, final ServerHttpRequest serverHttpRequest, final ShenyuPluginChain chain) {
>         return Mono.from(DataBufferUtils.join(serverHttpRequest.getBody())
>                 .flatMap(body -> {
>                     exchange.getAttributes().put(Constants.PARAM_TRANSFORM, resolveBodyFromRequest(body));
>                     return chain.execute(exchange);
>                 }));
>     }
> ```
> 
> this is look like #3158

Yes, how to reassign the size of the Databuffer in this place

**Comment by moremind** [comment]
> > in `org.apache.shenyu.plugin.base.RpcParamTransformPlugin` make sure that
> > ```java
> >     private Mono<Void> body(final ServerWebExchange exchange, final ServerHttpRequest serverHttpRequest, final ShenyuPluginChain chain) {
> >         return Mono.from(DataBufferUtils.join(serverHttpRequest.getBody())
> >                 .flatMap(body -> {
> >                     exchange.getAttributes().put(Constants.PARAM_TRANSFORM, resolveBodyFromRequest(body));
> >                     return chain.execute(exchange);
> >                 }));
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this is look like #3158
> 
> Yes, how to reassign the size of the Databuffer in this place

not reassign, data buffer is 1024, you can use `return Mono.from(DataBufferUtils.join(serverHttpRequest.getBody())` -> `DataBufferUtils.join()` collect data buffer.

**Comment by moremind** [comment]
> > > in `org.apache.shenyu.plugin.base.RpcParamTransformPlugin` make sure that
> > > ```java
> > >     private Mono<Void> body(final ServerWebExchange exchange, final ServerHttpRequest serverHttpRequest, final ShenyuPluginChain chain) {
> > >         return Mono.from(DataBufferUtils.join(serverHttpRequest.getBody())
> > >                 .flatMap(body -> {
> > >                     exchange.getAttributes().put(Constants.PARAM_TRANSFORM, resolveBodyFromRequest(body));
> > >                     return chain.execute(exchange);
> > >                 }));
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > this is look like #3158
> > 
> > 
> > Yes, how to reassign the size of the Databuffer in this place
> 
> not reassign, data buffer is 1024, you can use `return Mono.from(DataBufferUtils.join(serverHttpRequest.getBody())` -> `DataBufferUtils.join()` collect data buffer.

make sure your code same to above code.

**Comment by moremind** [comment]
```
private Mono<Void> body(final ServerWebExchange exchange, final ServerHttpRequest serverHttpRequest, final ShenyuPluginChain chain) {
    return Mono.from(serverHttpRequest.getBody()
            .flatMap(body -> {
                exchange.getAttributes().put(Constants.PARAM_TRANSFORM, resolveBodyFromRequest(body));
                return chain.execute(exchange);
            }));
}
```
this code not same to 
```
 private Mono<Void> body(final ServerWebExchange exchange, final ServerHttpRequest serverHttpRequest, final ShenyuPluginChain chain) {
        return Mono.from(DataBufferUtils.join(serverHttpRequest.getBody())
                .flatMap(body -> {
                    exchange.getAttributes().put(Constants.PARAM_TRANSFORM, resolveBodyFromRequest(body));
                    return chain.execute(exchange);
                }));
    }
```

second code have `DataBufferUtils#join` method, it keep data intactly.

**Comment by gongzhibo** [comment]
> DataBufferUtils.join

Thank you very much. It has been solved
