### ISSUE TITLE
[BUG] When the client (SpringMVC) is configured with isFull=true, the gateway returns "Divide :Rule not found!"

### ISSUE THREAD

**Issue by fengchangxue** [apache/incubator-shenyu#3679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use full match(isFull=true), but there are problems. Because the client is not fully matched when registering with the gateway. The default registered rule is URI =/ HTTP, which should be URI match/HTTP /**

### Expected Behavior

I use full match(isFull=true), but there are problems. Because the client is not fully matched when registering with the gateway. The default registered rule is URI =/ HTTP, which should be URI match/HTTP /**

### Steps To Reproduce

1.Start the admin
2.Start the gateway
3.Start the"shenyu-examples-http" and set isFull=true
4.Access any HTTP interface where Shenyu-examples-http exists, Divide :Rule not found is displayed.

### Environment

```markdown
ShenYu version(s):2.4.3
```

### Debug logs

2022-07-08 10:56:27 [boundedElastic-4] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - contextPath selector success match , selector name :/http
2022-07-08 10:56:27 [boundedElastic-4] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - contextPath rule success match , rule name :/http
2022-07-08 10:56:27 [boundedElastic-4] INFO  org.apache.shenyu.plugin.base.AbstractShenyuPlugin - divide selector success match , selector name :/http
2022-07-08 10:56:27 [boundedElastic-4] ERROR org.apache.shenyu.plugin.api.utils.WebFluxResultUtils - can not match rule data: divide

**Comment by dragon-zhang** [comment]
Can you change it to register `/http/` with `startsWith`?

**Comment by fengchangxue** [comment]
> Can you change it to register `/http/` with `startsWith`?

Did you say change the URI to "/ HTTP/" to match? If I tried it, I'll get the same error

**Comment by dragon-zhang** [comment]
I tried in the master branch, no problem.

**Comment by dragon-zhang** [comment]
> > Can you change it to register `/http/` with `startsWith`?
> 
> Did you say change the URI to "/ HTTP/" to match? If I tried it, I'll get the same error

check https://github.com/apache/incubator-shenyu/pull/3273 ,
![图片](https://user-images.githubusercontent.com/38336731/177913961-52c933e6-d8c6-454b-a1dd-465e0edf3828.png)
