### ISSUE TITLE
[Task] use `startsWith` operator as default when `isFull` is true

### ISSUE THREAD

**Issue by dragon-zhang** [apache/incubator-shenyu#3690]
### Description

check https://github.com/apache/incubator-shenyu/pull/3273 , change to `startsWith` can get a better performance.

use `startsWith` operator as default when `isFull` is true, now just found `divide`, need to check other plugins.

![图片](https://user-images.githubusercontent.com/38336731/177913961-52c933e6-d8c6-454b-a1dd-465e0edf3828.png)

**Comment by 847850277** [comment]
Hi,I want to try. can assign to me?
