### ISSUE TITLE
Is it nessary to support RocketMQ?

### ISSUE THREAD

**Issue by KevinClair** [apache/incubator-shenyu#660]
##### Is it nessary to support RocketMQ
* Two ways to user it.
    * As a way to data sync from admin to bootstrap.
    * As a plugin to send mq message by request from bootstrap.

**Comment by tydhot** [comment]
A mq pluign is meaning that the soul is a http proxy to mq, right?It sounds like this project https://github.com/confluentinc/kafka-rest

**Comment by KevinClair** [comment]
Yes, we can send a mq message to topic by soul and get the result. In the past, we used to use API to send messages, but now we can send messages by mq plugin.

**Comment by yu199195** [comment]
One way to synchronize data?

**Comment by KevinClair** [comment]
> One way to synchronize data?

Yes,when admin update configuration and send message, bootstrap receive message and update cache.

**Comment by yu199195** [comment]
>One way to synchronize data?

Yes,when admin update configuration and send message, bootstrap receive message and update cache.

good idea,  can you provide this pull reqeust?

**Comment by KevinClair** [comment]
> > Yes,when admin update configuration and send message, bootstrap receive message and update cache.
> 
> good idea, can you provide this pull reqeust?

ok，please assign me later.

**Comment by dengliming** [comment]
IMO, This is not necessary, We already support many ways to synchronize data. like nacos, and Why use `RocketMQ`?

**Comment by KevinClair** [comment]
> IMO, This is not necessary, We already support many ways to synchronize data. like nacos, and Why use `RocketMQ`?

More ways, more choices. If you don't think it's necessary, it's OK.

**Comment by dengliming** [comment]
This is only my personal opinion. We can talk more about the need for this in the community.

**Comment by KevinClair** [comment]
> This is only my personal opinion. We can talk more about the need for this in the community.

ok.

**Comment by lzqdename** [comment]
I do not think it is a good idea to let this gateway heavier... please keep it as smart as possible
it is just a gateway................
