### ISSUE TITLE
SpringCloud plugin register center init

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#958]
Now we used Springcloud plugin like this

1. add register center in soul-boostrap

in yaml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

in pom and add this

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-commons</artifactId>
            <version>2.2.0.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
            <version>2.2.0.RELEASE</version>
        </dependency>

Fetrue:
condition1 ：user config register and enabled to spring-cloud plugin  in the soul-admin 
condition2： this config we sync soul-boostrap
at this time we init springcloud register center。

we support Nacos and eureka and other registry

**Comment by midnight2104** [comment]
pls see https://shenyu.apache.org/docs/design/register-center-design
